### PR TITLE
Create wil.min.js

### PR DESCRIPTION
**Pull request by masdarno**
first req

### CODE REVIEW

**Comment by pnommensen** [comment]
@masdarno Is the official source of this file at https://github.com/masdarno/wil? If so, that needs to be references in the info.ini file. The best practice here is to include an update.json and tag releases in your repository. See the readme file for more information.

**Comment by jimaek** [comment]
Your project needs much more information and documentation to get accepted.

**Comment by masdarno** [comment]
it's my first time using jsdelivr. i'm still learning.tengkyu.

**Comment by masdarno** [comment]
2nd try

**Pull request closed without merging**
