### PR TITLE
Update clappr update.json to use npm

### PR DESCRIPTION
**Pull request by tjenkinson**

### CODE REVIEW

**Comment by jimaek** [comment]
@MartinKolarik Can you check why clappr is not getting updated anymore please?

**Comment by MartinKolarik** [comment]
@jimaek there was a problem caused by existing `media_control_css_animations` and `media_control_youtube` tags and the fact that clappr uses `0.x.y` versions, which are treated slightly differently than "stable" (`1.0.0` and up) versions. I sent PR to the bot repo to fix this.

**Comment by jimaek** [comment]
Thank you

**Comment by jimaek** [comment]
https://github.com/jsdelivr/jsdelivr/pull/10944

**Pull request closed without merging**
