### PR TITLE
Update project sly to v1.6.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project sly to v1.6.0.

@darsain

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "sly",
    "repo": "darsain/sly",
    "files": {
      "basePath": "dist/",
      "include": ["sly.min.js"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/sly",
    "localVersions": ["1.2.3", "1.4.3", "1.4.4", "1.5.0", "1.5.1"],
    "remoteVersions": ["v1.0.0", "v1.0.1", "v1.0.2", "v1.1.0", "v1.2.0", "v1.2.1", "v1.2.2", "v1.2.3", "v1.2.4", "v1.2.5", "v1.2.6", "v1.2.7", "v1.3.0", "v1.4.0", "v1.4.1", "v1.4.2", "v1.4.3", "v1.4.4", "v1.5.0", "v1.5.1", "v1.6.0"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/sly/update.json",
  "version": "v1.6.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/sly/1.6.0",
  "branch": "sly/v1.6.0"
}
```

### CODE REVIEW

**Comment by megawac** [comment]
Whats going on with the api @jimaek 

http://api.jsdelivr.com/v1/jsdelivr/libraries/sly
https://github.com/jsdelivrbot/jsdelivr/tree/sly/v1.6.0/files/sly

**Comment by jimaek** [comment]
The API looks good to me. Not sure what you see

**Comment by megawac** [comment]
Its working now, it was an empty response earlier

**Comment by jimaek** [comment]
Can you ping Austin maybe to debug this problem? We cant have this happening at random

**Pull request merged**
