### PR TITLE
loadCSS

### PR DESCRIPTION
**Pull request by akkumar**

### CODE REVIEW

**Comment by jimaek** [comment]
Only the directory needs to be lowercase, the file itself is best to have the original name

**Comment by akkumar** [comment]
File renamed as per original name (leaving lowercase for dir only).  Let me know if this looks ok.

**Comment by jimaek** [comment]
Can you minify the file by removing the comments as well? Make sure you do safe minification

**Comment by megawac** [comment]
> Can you minify the file by removing the comments as well?

The comment looks fine to me, just tells the user where the code is from. (Weren't we leaning towards requiring that comment too, its an issue on bot somewhere)

**Comment by akkumar** [comment]
Used this minifier - https://github.com/mishoo/UglifyJS2 to minify again. Please verify and let me know if this looks ok.

**Comment by akkumar** [comment]
FYI - Per the feedback above, the comments have been removed now (with a better minifier). Thanks !

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
