### PR TITLE
Update project babylonjs to 2.1-beta

### PR DESCRIPTION
**Pull request by vousk**

### CODE REVIEW

**Comment by jimaek** [comment]
What is your source for this file? I cant find the 2.1 version on the official repo

**Comment by vousk** [comment]
I'm contributing to this project. You'll find the file on the official repo at root folder on master branch (named babylon.2.1-beta.js). 
The file I posted here is not the latest beta version published today, it's a stable beta version compiled two weeks ago.

**Comment by vousk** [comment]
We already have a CDN for the stable version (http://cdn.babylonjs.com/2-0/babylon.js), but it has not SSL access. The purpose of putting the file on jsDelivr is to provide, through an SSL CDN, a beta version not released as final stable but significantly tested (that's why it's not the latest beta) to be considered stable enough for some production projects.

**Comment by jimaek** [comment]
To make sure there is no security risk I would prefer if you added here an official release located in the repo https://github.com/BabylonJS/Babylon.js For example this https://github.com/BabylonJS/Babylon.js/blob/master/babylon.2.1-beta.js ?

Do you think thats possible?

**Comment by vousk** [comment]
I can't put the file currently on the repo because it has not been tested enough yet (in the last weeks we're in the process of adding webworkers compatility, leading to potential bugs and bigger file size). The version I'm uploading to jsdelivr is 100 Ko less than current one and it has been tested in production environnement for some weeks now (release date of this file is 25/04/2014, I don't remember the exact related commit but I can find it)

**Comment by vousk** [comment]
But I understand the security risk you mention. I don't know how to clean this out.

**Comment by jimaek** [comment]
You can create a new branch at https://github.com/BabylonJS/Babylon.js with this code. Or anything else really that shows that the code is official.

**Comment by vousk** [comment]
We do not create new branch in the main repo, branches are only local to devs and there're merged in master. 
To solve the problem we have exported a new beta version valid for production with webworkers deactivated. I'll do a new PR.

**Pull request closed without merging**
