### PR TITLE
Add simpleStorage

### PR DESCRIPTION
**Pull request by SiamKreative**
This PR is for https://github.com/andris9/simpleStorage. I hope I was able to follow the guidelines...

*simpleStorage* is a fork of [jStorage](http://www.jstorage.info/) that only includes the minimal set of features. Basically it is a wrapper for native `JSON` + `localStorage` with some TTL magic mixed in.

### CODE REVIEW

**Comment by SiamKreative** [comment]
I renamed the folder `/simpleStorage/` to `/simplestorage/` (lowercase), so now everything should be fine, right?

**Comment by jimaek** [comment]
Everything is correct. I just want to ask if its possible to add a minified file instead of the current one. Does the author publish it anywhere where our bot could pull from? (bower/npm)

**Comment by SiamKreative** [comment]
There's both a `bower.json` and `package.json` file, so yeah I guess the author publishes on both Bower & NPM.

There's no minified version as of now. Is it possible to add it later on?

**Comment by jimaek** [comment]
Its possible but it would have to be a major version change to avoid breaking sites.
Unless the minified file will have the same name as the current one of course. In any case its much better to have a minified file from the start.
Less stuff that can break plus it makes sense in production, less KB to deliver.

**Comment by SiamKreative** [comment]
@jimaek Dimitry please check out the latest changes. Hopefully you can now merge it :)

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by SiamKreative** [comment]
Thanks :) When will in appear on the site?

**Comment by jimaek** [comment]
Not until the bot can pickup a version. Currently it cant because there is no min.js here https://github.com/andris9/simpleStorage/tree/v0.1.3

**Comment by SiamKreative** [comment]
Alrighty. Is there anything I can do or should do?

**Comment by jimaek** [comment]
The author released a new version with that file included https://github.com/andris9/simpleStorage/tree/v0.1.4
The project is live http://www.jsdelivr.com/projects/simplestorage

**Pull request closed without merging**
