### PR TITLE
Added ajile: async js importing & loading extension

### PR DESCRIPTION
**Pull request by iskitz**
Added all of ajile's available versions and its auto-update config via
this initial commit.

ajile's original source code can be found at

https://github.com/iskitz/ajile/tree/master/code
https://github.com/iskitz/ajile/tree/master/use

### CODE REVIEW

**Comment by iskitz** [comment]
Hi @jimaek, can you please help me with this pull request?

I'm not sure why @jsdelivrbot thinks so many of my static plaintext `.js` files are *__binary__*. I also don't know what it thinks is wrong with my [info.ini](https://github.com/iskitz/jsdelivr/blob/master/files/ajile/info.ini) file and my [update.json](https://github.com/iskitz/jsdelivr/blob/master/files/ajile/update.json) file which I validated using [JSONLint](http://jsonlint.com/).

Thanks,
Mike

**Comment by jimaek** [comment]
@iskitz Can you remove all versions except from the latest one? I dont see any reason to host them all

@megawac Do you know what the bot complains on the update.json and info.ini?

**Comment by iskitz** [comment]
@jimaek ajile's been in production for a few years now so I wanted to make sure all its released versions would be available for anyone who's been using it over the years. Having them all hosted on a CDN also makes it easy to reference them from jsperf tests and other online dev tools like jsfiddle.

**Comment by jimaek** [comment]
Although the formatting of update.json is strange it appears to be correct. I think we can merge it

**Comment by iskitz** [comment]
Thanks @jimaek!

**Pull request merged**
