### PR TITLE
Update project angular-icons to v1.0.2

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project angular-icons to v1.0.2.

@base-apps

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "angular-icons",
    "repo": "base-apps/angular-icons",
    "files": {
      "basePath": "./dist",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/angular-icons",
    "localVersions": [],
    "remoteVersions": ["v0.1.2", "v0.1.3", "v1.0.0", "v1.0.1", "v1.0.2"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/angular-icons/update.json",
  "versions": ["v1.0.2"],
  "updateRemote": true,
  "version": "v1.0.2",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/angular-icons/1.0.2",
  "branch": "angular-icons/v1.0.2"
}
```

### CODE REVIEW

**Comment by soumak77** [comment]
@megawac bit confused as info.ini exist https://github.com/jsdelivr/jsdelivr/blob/master/files/angular-icons/info.ini

**Comment by megawac** [comment]
Yeah this happens when jsdelivr-api takes a while to update

@jimaek do you know why jsdelivr-api takes forever to rescan for new projects?

**Comment by jimaek** [comment]
Not sure, it was running non-stop for a long time and giving errors like "buffer is full. I restarted it.

**Comment by soumak77** [comment]
@megawac can this be merged now? along with https://github.com/jsdelivr/jsdelivr/pull/13422

**Comment by soumak77** [comment]
This can be closed now that https://github.com/jsdelivr/jsdelivr/pull/13483 has been merged, however, there is a new issue with updating the version https://github.com/jsdelivr/jsdelivr/pull/13487.

**Pull request closed without merging**
