### PR TITLE
Update project webfontloader to v1.5.16

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project webfontloader to v1.5.16.

@typekit

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "webfontloader",
    "repo": "typekit/webfontloader",
    "files": {
      "include": ["webfontloader.js"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/webfontloader",
    "localVersions": ["1.1.2", "1.5.2", "1.5.3", "1.5.6", "1.5.8", "1.5.11", "1.5.12", "1.5.13", "1.5.14", "1.5.15"],
    "remoteVersions": ["v1.0.0", "v1.0.1", "v1.0.2", "v1.0.3", "v1.0.4", "v1.0.5", "v1.0.6", "v1.0.7", "v1.0.8", "v1.0.9", "v1.0.10", "v1.0.11", "v1.0.12", "v1.0.13", "v1.0.14", "v1.0.15", "v1.0.16", "v1.0.17", "v1.0.18", "v1.0.19", "v1.0.20", "v1.0.21", "v1.0.22", "v1.0.23", "v1.0.24", "v1.0.25", "v1.0.26", "v1.0.27", "v1.0.28", "v1.0.29", "v1.0.30", "v1.0.31", "v1.1.0", "v1.1.1", "v1.1.2", "v1.2.0", "v1.2.1", "v1.3.0", "v1.3.1", "v1.3.2", "v1.4.0", "v1.4.1", "v1.4.2", "v1.4.3", "v1.4.4", "v1.4.5", "v1.4.6", "v1.4.7", "v1.4.8", "v1.4.9", "v1.4.10", "v1.4.11", "v1.4.12", "v1.5.0", "v1.5.1", "v1.5.2", "v1.5.3", "v1.5.4", "v1.5.5", "v1.5.6", "v1.5.7", "v1.5.8", "v1.5.9", "v1.5.10", "v1.5.11", "v1.5.12", "v1.5.13", "v1.5.14", "v1.5.15", "v1.5.16"],
    "branchVersions": []
  },
  "version": "v1.5.16",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/webfontloader/1.5.16",
  "branch": "webfontloader/v1.5.16"
}
```

### CODE REVIEW

**Comment by hubdotcom** [comment]
this package continues to fail updates: https://github.com/jsdelivr/jsdelivr/search?p=1&q=webfontloader&type=Issues&utf8=%E2%9C%93

Is there any way to address?

**Comment by jimaek** [comment]
The API doesnt include the mainfile fix that we use yet. Once we add it we can modify the bot and these errors will stop

**Comment by hubdotcom** [comment]
Is this something I can add?

**Comment by jimaek** [comment]
No unless you can code in node.js https://github.com/jsdelivr/api-sync

**Comment by UnbounDev** [comment]
@jimaek if you can point me towards the mainfile fix I can look into integrating that w/ api-sync.

**Comment by jimaek** [comment]
@UnbounDev When a project changes the name of the "mainfile" we change it in info.ini, but to make sure all previous links dont break we create a file callled `mainfile` containing the name of the mainfile for that particular version. /g/ prioritizes the separate `mainfile` per version.

For example https://github.com/jsdelivr/jsdelivr/blob/master/files/imagesloaded/2.1.0/mainfile

We should include this in our API so bot could read and stop complaining about missing mainfiles, they are not missing but overwritten by a local version mainfile

**Comment by hubdotcom** [comment]
Good luck @UnbounDev!

**Pull request closed without merging**
