### PR TITLE
Adding Sortable v1.0.1

### PR DESCRIPTION
**Pull request by RubaXa**
Sortable
===
Minimalist JavaScript library for reorderable drag-and-drop lists on modern browsers and touch devices. No jQuery. Supports AngularJS, React, Meteor and any CSS library, e.g. Bootstrap.

 - https://github.com/rubaxa/Sortable
 - http://rubaxa.github.io/Sortable

### CODE REVIEW

**Comment by jimaek** [comment]
Our system is case-sensitive. The included files in this PR start with lower case(sortable.min.js) but the ones in update.json start with capital (Sortable.min.js).
Please change the included files to `Sortable.min.js` along with the mainfile parameter in info.ini

**Comment by RubaXa** [comment]
Done.

**Comment by RubaXa** [comment]
@jimaek Hello from me something else is required?

**Comment by jimaek** [comment]
Looks good, sorry for the delay I must have missed the notification email

**Comment by RubaXa** [comment]
Thanks a lot!

**Pull request merged**
