### PR TITLE
2016 Volumne 2 SP1 version Merge

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**

### CODE REVIEW

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
Based on above suggestion, we have give pull request. But there show some deletion files (e.g) files/ace/1.2.4/min/ace.js. we don't delete or commit those files.we need to merge only "files/syncfusion-javascript/14.2.28/" files.
Please merge asap.

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
any update on this pull request to be merge?

**Comment by megawac** [comment]
sorry didn't see it

**Comment by DheepaKumar123** [comment]
Hi @megawac -Thanks for response 
I have committed script files with 14.2.28 folder.but why there not merge that before commit ?

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac -Thanks for response 
I have committed 14.2.28 folder with updated script files. but why those changes not merged?

**Comment by megawac** [comment]
I had to revert this pull request. Upon review I noticed you had deleted several versions of other libraries

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac  - Thanks for response 
1. we done fork and clone the GitHub "jsDelivr/master" repository , but we have problem like below screenshot.
a). jsDelivr repository view
jsdelivr-local
b). jsDelivr repository in our local view 
jsdelivr-repo
why jsDelivr - Origin/master changes not update in our local jsDelivr - Origin/master?

2. we have done again checkout and update files using above suggestion steps but its show delete some external files.please refer screenshot below.
deletionmode

Please update solution asap.

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac  

any updates on this queries ?

**Comment by DheepaKumar123** [comment]
Hi @megawac  - Thanks for response
1. We done fork and clone the GitHub "jsDelivr/master" repository , but we
have problem like below screenshot.
a). jsDelivr repository view
jsdelivr-local
b). jsDelivr repository in our local view
jsdelivr-repo
Why jsDelivr - Origin/master changes not update in our local jsDelivr -
Origin/master?

2. We have done again checkout and update files using above suggestion
steps but its show delete some external files.please refer screenshot below.
deletionmode

Please update solution asap.

**Comment by DheepaKumar123** [comment]
Hi @megawac,

Please Update me solution asap.because we need to publish immediately. so
please give solution asap.

**Comment by megawac** [comment]
Did this solution (https://github.com/jsdelivr/jsdelivr/pull/13048#issuecomment-237537790) not work after you fixed your ssh key setup or switched the remote to https?

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac  - Thanks for Response.
yes, we have fixed using switched the remote to https. But its have problem like below.

1. We done fork and clone the GitHub "jsDelivr/master" repository , but we
have problem like below screenshot.
a). jsDelivr repository view
jsdelivr-local
b). jsDelivr repository in our local view
jsdelivr-repo
Why jsDelivr - Origin/master changes not update in our local jsDelivr -
Origin/master?

2. We have done again checkout and update files using above suggestion
steps but its show delete some external files.please refer screenshot below.
deletionmode

Please update solution asap.

**Comment by megawac** [comment]
oh I forgot a step, I updated my command list

**Pull request merged**
