### PR TITLE
Add Plyr HTML5 Media Player

### PR DESCRIPTION
**Pull request by Thunderbolt32**
Add files from plyr.io Media Player

### CODE REVIEW

**Comment by megawac** [comment]
Thanks, sorry for the delay merging this

**Comment by Thunderbolt32** [comment]
No problem. Thankyou. I don't get it. Possible that I missed something in the docs. I thought that the files will be added but the folder only exists of the submitted files. The website does not list the library either.

**Comment by megawac** [comment]
Let me take a look

**Comment by megawac** [comment]
Missing `basePath: "dist/"` by the looks of it

**Comment by Thunderbolt32** [comment]
Cool. Thank you!

**Pull request merged**
