### PR TITLE
Added the new version (1.3) of roundSlider 

### PR DESCRIPTION
**Pull request by soundar24**

### CODE REVIEW

**Comment by soundar24** [comment]
Please add the new version of round slider 1.3 in the CDN

**Comment by soundar24** [comment]
Can you please let me know when it will be included in the CDN ? Here i don't need to change the 1.1 and 1.2 version files. I need to include the new files under the 1.3 folder only. Thanks :)

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge
@soundar24 Sorry it took so long

**Comment by soundar24** [comment]
However finally it was added :) .. Thanks :+1:

**Pull request closed without merging**
