### PR TITLE
Update project farel to 0.2.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project farel to 0.2.0.

@rosendi

### Metadata information

```json
{
  "metadata": {
    "packageManager": "npm",
    "name": "farel",
    "files": {
      "basePath": "bundles/",
      "include": ["farel.min.js", "farel.min.js.map"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/farel",
    "localVersions": ["0.1.2"],
    "remoteVersions": ["0.1.2", "0.2.0"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/farel/update.json",
  "version": "0.2.0",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/farel/0.2.0",
  "branch": "farel/0.2.0"
}
```

### CODE REVIEW

**Comment by rosendi** [comment]
@jimaek have I done something wrong? :smile: https://github.com/jsdelivr/jsdelivr/pull/8577

**Comment by rosendi** [comment]
@jimaek  :beer:

**Comment by rosendi** [comment]
@jimaek hmm... https://cdn.jsdelivr.net/farel/0.2.0/farel.min.js 404

**Comment by jimaek** [comment]
There was a delay with deployment. Sorry about that, its live now

**Comment by rosendi** [comment]
Perfect!

**Pull request merged**
