### PR TITLE
github-markdown-css main file is not minimized

### PR DESCRIPTION
**Pull request by tylerlong**
Check https://github.com/sindresorhus/github-markdown-css

I also tried `bower install install github-markdown-css`, the downloaded main file is not minimized.

### CODE REVIEW

**Comment by tylerlong** [comment]
In old versions, the main file is `github-markdown.min.css`

But in recent versions, the main file is `github-markdown.css`

What should we do?

**Comment by jimaek** [comment]
Is there any chance that the author will add the min file to bower or a `dist/` folder in the repo?

**Comment by sindresorhus** [comment]
> Is there any chance that the author will add the min file to bower or a dist/ folder in the repo?

I'm the author. No chance.

**Comment by tylerlong** [comment]
@jimaek how about removing the ancient versions from jsdelivr?

The last solution is we just fork the original project and make any changes necessary since it is MIT licensed.

**Comment by tylerlong** [comment]
:+1:

**Pull request closed without merging**
