### PR TITLE
legal text

### PR DESCRIPTION
**Pull request by jimaek**
Since we are becoming more mainstream a lawyer suggested we make sure we are not liable for any problems. 
Its just a standard legal text that all companies have on their sites.
jsDelivr will always take all possible steps to prevent problems with accessing our service.

### CODE REVIEW

**Comment by jimaek** [comment]
I guess we also need to redeploy the main site after this is merged to update the text there?

**Comment by MartinKolarik** [comment]
This seems more suited to be in ToS document which we don't have yet and I was thinking about recently because of jsdelivr/jsdelivr-backend#191

**Comment by jimaek** [comment]
I know, but since we dont have a TOS, here should be fine as well. It can be anywhere really.

**Comment by MartinKolarik** [comment]
Ok for now let's keep it simple. The website updates automatically from this doc.

**Review by MartinKolarik — APPROVED** [review]

**Pull request merged**
