### PR TITLE
added Hack font

### PR DESCRIPTION
**Pull request by chrissimpkins**
Added Hack font binaries (eot, ttf, woff, woff2, svg) + full and minified CSS files

### CODE REVIEW

**Comment by jimaek** [comment]
Can you please rename the folder to `font-hack`?

**Comment by chrissimpkins** [comment]
Just pushed the requested changes along with several modifications to the css files.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by chrissimpkins** [comment]
thanks!

**Comment by jimaek** [comment]
thank you!

**Comment by chrissimpkins** [comment]
How long does it typically take to go live on the CDN?

**Comment by jimaek** [comment]
The uploads are instant but it takes a while to appear on the website.
Here it is http://www.jsdelivr.com/#!font-hack

**Comment by chrissimpkins** [comment]
thanks again.  I really appreciate it!

**Comment by jimaek** [comment]
Feel free to ping me if you ever need anything :)

**Comment by chrissimpkins** [comment]
Will do.  Greatly appreciate your help.

**Pull request closed without merging**
