### PR TITLE
Add Reddit.js

### PR DESCRIPTION
**Pull request by sahilm**
Reddit API wrapper for the browser

### CODE REVIEW

**Comment by jimaek** [comment]
basePath should be inside "files" 
https://github.com/jsdelivr/libgrabber#add-updatejson-schema

**Comment by sahilm** [comment]
Done.

**Comment by sahilm** [comment]
Would you prefer a squash and rebase?

**Comment by jimaek** [comment]
Sure, that works.

**Comment by jimaek** [comment]
Thank you

**Comment by sahilm** [comment]
Thanks.

**Pull request merged**
