### PR TITLE
Update algoliasearch repository (update.ini)

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
cc @jimaek we changed the repository url of algoliasearch package. I did push a new js client afterwards (before modifying this). Do I need to do smg special?

Also this PR is failing I failed at seeing why (edited on github)

**Comment by jimaek** [comment]
It fails because of this symbol `≥` you can ignore it. You will need to add the new repo to update.json as well

**Comment by vvo** [comment]
Both were merged, do I need to manually upload the 3.20.0 version of algoliasearch that was pushed in between?

**Comment by jimaek** [comment]
If it wasnt uploaded already by the bot then yes.

P.S. Sorry if I take too long to respond or seem distant. We are working on v2 of jsDelivr and I try to focus my resources there.

**Comment by vvo** [comment]
No prob, everything was updatd

**Pull request merged**
