### PR TITLE
Update the plugin (bug fixed)

### PR DESCRIPTION
**Pull request by aamirafridi**
new version is released with bug fixes

### CODE REVIEW

**Comment by jimaek** [comment]
you need to squash your commits into 1

**Comment by aamirafridi** [comment]
squash how? :/

**Comment by jimaek** [comment]
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by pnommensen** [comment]
ping @aamirafridi.

**Pull request closed without merging**
