### PR TITLE
Create info.ini

### PR DESCRIPTION
**Pull request by claudiobarahona**
Librería de procedimientos de compatibilidad con Moodle para www.campusvirtual.unah.edu.hn

### CODE REVIEW

**Comment by claudiobarahona** [comment]
Accent eliminated

**Comment by jimaek** [comment]
Please add more documentation to your project at github and develop it further. Also start tagging your versions. After that we can merge it and enable auto-updates

**Comment by claudiobarahona** [comment]
Basic documentation ready

**Comment by megawac** [comment]
You will need to include an `update.json` file @claudiobarahona for auto updating (see https://github.com/jsdelivr/libgrabber/blob/master/README.md) for now the files won't be added to the cdn

**Comment by claudiobarahona** [comment]
update.json ready!

**Pull request merged**
