### PR TITLE
Add ouibounce

### PR DESCRIPTION
**Pull request by carlsednaoui**
As requested by @bradvogel here: https://github.com/carlsednaoui/ouibounce/issues/94

### CODE REVIEW

**Comment by megawac** [comment]
Thanks

**Comment by carlsednaoui** [comment]
Thanks @megawac :pizza:

**Comment by bradvogel** [comment]
Awesome, when will this be live?

**Comment by jimaek** [comment]
After the bot sent the PR the upload is instant. Your files are here http://www.jsdelivr.com/#!ouibounce

**Pull request merged**
