### PR TITLE
Add Evil Icons

### PR DESCRIPTION
**Pull request by outpunk**
This PR adds Evil Icons http://evil-icons.io

### CODE REVIEW

**Comment by jimaek** [comment]
Do you need the unminified files? Maybe its best to only host the production files?

**Comment by outpunk** [comment]
Well, you're right.

**Comment by jimaek** [comment]
Dont you also need the svg files to make it work? I am not 100% sure how this project works :)

**Comment by outpunk** [comment]
Nope, we don't need the svg files — the sprite is built into the js.

**Comment by jimaek** [comment]
Awesome then, please squash your commits into 1 and its good to go

**Comment by jimaek** [comment]
Thank you

**Comment by outpunk** [comment]
Thanks!

**Pull request merged**
