### PR TITLE
angular directive for chartjs

### PR DESCRIPTION
**Pull request by akkumar**
Angular directive for chart.js .

### CODE REVIEW

**Comment by akkumar** [comment]
The auto check seems to pass here. Let me know if there is anything I need to do on the same. Thanks !

**Comment by jimaek** [comment]
Instead of adding the files how about adding an update.json file? https://github.com/jsdelivr/libgrabber

**Comment by akkumar** [comment]
Thanks, my first stab at update.json here. Let me know if that looks ok.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
