### PR TITLE
Adding Files for Hosting

### PR DESCRIPTION
**Pull request by douglasdeodato**
files added.

### CODE REVIEW

**Comment by douglasdeodato** [comment]
waiting for the merge, thanks!

**Comment by douglasdeodato** [comment]
hey guys when you will merge my changes? thank you.

**Comment by megawac** [comment]
you'll need to create a git tag or github release before auto updating will work

**Comment by douglasdeodato** [comment]
@megawac  I did, is on: https://github.com/douglasdeodato/lovely-icons/releases

**Comment by douglasdeodato** [comment]
@megawac  any  news? thank you.

**Comment by megawac** [comment]
Cheers

**Comment by douglasdeodato** [comment]
@megawac  thank you.

**Pull request merged**
