### PR TITLE
create update.json for MathJax

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by megawac** [comment]
Awesome thanks, osrry for delay

**Comment by SCHOLAR-Graeme** [comment]
@megawac Are you able to look at the MathJax folder:
https://github.com/jsdelivr/jsdelivr/tree/master/files/mathjax 
It's currently stuck on "Fetching latest commit…" and it would be good to get an update before the 30th of April before MathJax switch off their CDN.

**Comment by megawac** [comment]
Hmm, @as-com any ideas? It looks good to me

**Comment by as-com** [comment]
@megawac I don't see an images folder in the MathJax repository. Perhaps that's the issue?

**Comment by megawac** [comment]
Hmm, good catch. I removed that line but still no dice it seems.

**Comment by as-com** [comment]
Hmm...I'm just going to manually add the files. Gigantic pull request coming up!

**Comment by as-com** [comment]
@megawac Do you think the problem is that MathJax simply has too many files?

**Comment by megawac** [comment]
No idea, but there are some repos that have some 500+ files per version. How many mathjax is at?

**Comment by megawac** [comment]
oh, uh jesus. what are all those files?

**Comment by as-com** [comment]
@megawac Most of the files are the image fonts. MathJax uses images for older browsers.

**Comment by pkra** [comment]
Sorry, I should have closed this after emailing with Dmitriy.

FWIW, the image fonts can be excluded if that helps. A quick fix might be to switch to npm as provider (we exclude them from the NPM package already).

**Pull request merged**
