### PR TITLE
add renuo-cms-client

### PR DESCRIPTION
**Pull request by lukaselmer**

### CODE REVIEW

**Comment by sihu** [comment]
Looks good to me

**Comment by jimaek** [comment]
I dont completely understand what this project does and who can use it.
It looks like an API to a proprietary software.

**Comment by lukaselmer** [comment]
This is the frontend to a content management system. In general, it can be used with any backend, but here is the open source backend implementation for it: https://github.com/renuo/renuo-cms-api

**Comment by lukaselmer** [comment]
And here's an example of how to use it: https://github.com/renuo/renuo-cms-client/blob/develop/demo/index.html

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by lukaselmer** [comment]
@jimaek thx!

**Pull request closed without merging**
