### PR TITLE
[author][new] add cutback-js

### PR DESCRIPTION
**Pull request by jlaran**
Adding cutback-js library, any change needed please advice.

Github repo: https://github.com/jlaran/cutback-js

### CODE REVIEW

**Comment by jlaran** [comment]
@jimaek could take a very quick look at this PR please?

**Comment by jlaran** [comment]
Thanks @jimaek , just a question.. in this phase how can I add the js files for my library?

**Comment by jimaek** [comment]
The bot will add them automatically in a while.

**Comment by jlaran** [comment]
Thanks so much @jimaek

**Comment by jlaran** [comment]
last question @jimaek , how much time takes for a new library to appear on the website?

**Comment by jimaek** [comment]
It gets uploaded instantly but it may take some time to appear online

**Pull request merged**
