### PR TITLE
Adding the latest version of GSAP and removing the oldest version

### PR DESCRIPTION
**Pull request by dfedgar**
Adding the latest version of GSAP and removing v12 because it's misleading, it's actually a really old version of GSAP.

### CODE REVIEW

**Comment by dfedgar** [comment]
These changes are intentional.

**Comment by jimaek** [comment]
We dont allow to remove or modify any existing files to ensure we dont break any websites.

**Comment by dfedgar** [comment]
Ok, changed so that it's only adding the latest version of GSAP.

**Comment by jimaek** [comment]
thank you

**Pull request merged**
