### PR TITLE
Create info.ini

### PR DESCRIPTION
**Pull request by Stephan972**

### CODE REVIEW

**Comment by jimaek** [comment]
Both files must be in 1 PR

**Comment by Stephan972** [comment]
Sorry, I'm new to GitHub and the add project process is quite complicate IMO. I don't know how to merge this PR with this one: https://github.com/jsdelivr/jsdelivr/pull/10277

**Comment by jimaek** [comment]
The documentation includes a gif of the process https://cloud.githubusercontent.com/assets/1834071/6826939/4019ce7a-d30d-11e4-8d1b-7821b923dd50.gif
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by Stephan972** [comment]
The gif doesn't explain how to merge the two PR.

**Comment by jimaek** [comment]
You cant merge them, you need to close everything and create a new one with both files in 1 PR

**Pull request closed without merging**
