### PR TITLE
initial version of basscss

### PR DESCRIPTION
**Pull request by akkumar**
BassCSS is a responsive css framework. The most recent version seems to be 6.0.1 added as well. 

info.ini added as well.

### CODE REVIEW

**Comment by jimaek** [comment]
Just the min.css file is enough. Also why 6.0.1 when the latest is 6.0.2

**Comment by akkumar** [comment]
Taken care of the feedback and this is checked in now.

**Comment by pnommensen** [comment]
@akkumar Can you squash your commits please? Thx :)

**Comment by jimaek** [comment]
@jsdelivrbot squash things

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
