### PR TITLE
Angular2

### PR DESCRIPTION
**Pull request by CEikermann**
Added info.ini and update.json for angular2

### CODE REVIEW

**Comment by CEikermann** [comment]
@jimaek I have fixed the syntax error ;) - Is everything ready to merge ?

**Comment by jimaek** [comment]
I am not sure if we should host it. If we enabled auto-updates from the start we would have these useless versions right now:

```
"2.0.0-alpha.1": "2015-02-10T22:21:48.962Z",
"2.0.0-alpha.7.dev": "2015-02-17T21:38:59.732Z",
"2.0.0-alpha.7.prod": "2015-02-17T21:39:05.115Z",
"2.0.0-alpha.8.dev": "2015-02-18T20:54:53.482Z",
"2.0.0-alpha.8.prod": "2015-02-18T20:54:55.365Z",
"2.0.0-alpha.10": "2015-02-25T00:55:10.461Z",
"2.0.0-alpha.11": "2015-02-25T00:58:44.135Z",
"2.0.0-alpha.12": "2015-03-02T19:36:06.005Z",
"2.0.0-alpha.13": "2015-03-14T03:51:04.190Z",
"2.0.0-alpha.14": "2015-03-24T00:24:24.475Z",
"2.0.0-alpha.15": "2015-03-24T16:41:02.466Z",
"2.0.0-alpha.16": "2015-03-26T20:46:00.496Z",
"2.0.0-alpha.17": "2015-03-27T23:27:16.246Z",
"2.0.0-alpha.18": "2015-03-28T00:33:07.385Z",
"2.0.0-alpha.19": "2015-04-13T23:23:10.828Z",
"2.0.0-alpha.20": "2015-04-21T01:15:29.045Z",
"2.0.0-alpha.21": "2015-04-28T19:32:23.397Z",
"2.0.0-alpha.22": "2015-05-07T23:36:43.776Z",
"2.0.0-alpha.23": "2015-05-12T22:32:25.015Z",
"2.0.0-alpha.24": "2015-05-19T22:07:02.003Z",
"2.0.0-alpha.25": "2015-05-22T00:42:16.476Z",
"2.0.0-alpha.26": "2015-06-04T00:41:25.177Z",
"2.0.0-alpha.27": "2015-06-17T04:39:19.358Z",
"2.0.0-alpha.28": "2015-06-25T00:25:16.035Z",
"2.0.0-alpha.29": "2015-07-01T23:39:56.659Z",
"2.0.0-alpha.30": "2015-07-08T04:42:19.521Z",
"2.0.0-alpha.31": "2015-07-14T17:56:18.568Z",
"2.0.0-alpha.32": "2015-07-23T00:03:00.879Z",
"2.0.0-alpha.33": "2015-07-30T21:08:11.665Z",
"2.0.0-alpha.34": "2015-08-06T22:43:46.329Z",
"2.0.0-alpha.35": "2015-08-19T13:16:21.246Z",
"2.0.0-alpha.36": "2015-08-31T19:56:47.096Z",
"2.0.0-alpha.37": "2015-09-10T16:37:44.777Z",
"2.0.0-alpha.38": "2015-10-03T00:47:08.252Z",
"2.0.0-alpha.39": "2015-10-06T19:23:18.393Z",
"2.0.0-alpha.40": "2015-10-09T02:10:35.556Z",
"2.0.0-alpha.41": "2015-10-13T20:04:06.923Z",
"2.0.0-alpha.42": "2015-10-13T23:08:33.571Z",
"2.0.0-alpha.44": "2015-10-15T23:53:32.769Z",
"2.0.0-alpha.45": "2015-10-29T01:33:07.877Z",
"2.0.0-alpha.46": "2015-11-11T21:41:20.882Z",
"2.0.0-alpha.47": "2015-12-01T20:22:41.841Z",
"2.0.0-alpha.48": "2015-12-05T03:07:45.497Z",
"2.0.0-alpha.49": "2015-12-09T02:05:13.336Z",
"2.0.0-alpha.50": "2015-12-09T03:19:58.909Z",
"2.0.0-alpha.51": "2015-12-10T03:48:47.170Z",
"2.0.0-alpha.52": "2015-12-10T08:53:32.193Z",
"2.0.0-alpha.53": "2015-12-13T02:02:57.476Z",
"2.0.0-alpha.54": "2015-12-15T11:07:15.712Z",
"2.0.0-alpha.55": "2015-12-15T17:59:55.166Z",
"2.0.0-beta.0": "2015-12-15T19:13:09.138Z",
"2.0.0-beta.1": "2016-01-08T21:21:51.121Z",
"2.0.0-beta.2": "2016-01-28T19:43:52.695Z",
"2.0.0-beta.3": "2016-02-03T18:16:22.416Z",
"2.0.0-beta.4": "2016-02-10T23:38:20.897Z",
"2.0.0-beta.5": "2016-02-11T00:18:58.856Z",
"2.0.0-beta.6": "2016-02-12T00:06:13.804Z",
"2.0.0-beta.7": "2016-02-18T21:37:46.098Z",
"2.0.0-beta.8": "2016-03-02T20:52:44.543Z",
"2.0.0-beta.9": "2016-03-09T22:59:51.326Z",
"2.0.0-beta.10": "2016-03-17T23:18:02.065Z",
"2.0.0-beta.11": "2016-03-18T21:49:17.607Z",
"2.0.0-beta.12": "2016-03-24T00:13:30.058Z",
"2.0.0-beta.13": "2016-03-31T00:28:56.743Z",
"2.0.0-beta.14": "2016-04-07T17:25:34.720Z",
"2.0.0-beta.15": "2016-04-13T20:53:12.470Z",
"2.0.0-beta.16": "2016-04-26T05:24:15.828Z",
"2.0.0-beta.17": "2016-04-28T18:53:50.992Z"
```

**Comment by CEikermann** [comment]
The Alpha versions are not needed, can we exclude them?

**Comment by jimaek** [comment]
What I mean was that if we enabled auto-updates in 2015 we would have all those versions.
I just think its dangerous to enable auto-updates to avoid future useless updates

**Comment by CEikermann** [comment]
Ah understood, what is your definition of a "useless update" ?

Because each upcoming version could use by everybody

**Comment by CEikermann** [comment]
Additional, do you have some file space concerns, or is that a big problem with these versions?

**Comment by CEikermann** [comment]
Angular is now out of beta:
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

@jimaek It would be great if jsdelivr could also add angular2, cdnjs has angular2 already in: https://cdnjs.com/libraries/angular.js - but I would like to continue use jsdelivr, because of the Multi CDN support ;)

**Comment by CEikermann** [comment]
I will update the pull request today, because angular has renamed the npm package names. 

The new npm packages has also not that many versions anymore ;)

**Comment by jimaek** [comment]
Sorry for the long pause. Basically their project is big with lots of files and a lot of versions. I prefer to avoid that and host only key versions that people will actually use for some time and not for 5 days until a new alpha/beta/rc is out.

**Comment by CEikermann** [comment]
I have to close this pr, because angular is not publishing the compiled/minified js version anymore. 

As soon they have added it again, I will reopen this.

**Pull request closed without merging**
