### PR TITLE
Add goodshare.js

### PR DESCRIPTION
**Pull request by enjoyiacm**

### CODE REVIEW

**Comment by jimaek** [comment]
1. Since this is a jquery plugin please rename the directory to `jquery.goodshare` or `jquery.goodshare.js`
2. You dont  have any tagged versions in Github. The bot will fail

**Comment by enjoyiacm** [comment]
1. How?
2. Tagged as 3.0 my repo https://github.com/enjoyiacm/goodshare.js/tree/3.0

**Comment by enjoyiacm** [comment]
Anybody here?

**Comment by megawac** [comment]
> 1. How?

Rename the folder your plugin is in from `goodshare.js` --> `jquery.goodshare.js`

**Comment by enjoyiacm** [comment]
OK. But HOW? Create new folder? New PR? HOW?

**Comment by enjoyiacm** [comment]
I create new folder ``jquery.goodshare.js`` in this PR, dublicate info.ini & update.json (from old folder ``goodshare.js``). Whats next?

**Comment by megawac** [comment]
Just delete the old folder and we'll be set

**Comment by enjoyiacm** [comment]
Ok. I did.

**Comment by megawac** [comment]
@jsdelivrbot squash & merge

**Pull request closed without merging**
