### PR TITLE
Update project jquery.fancytree to v2.10.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project jquery.fancytree to v2.10.0.

@mar10

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "jquery.fancytree",
    "repo": "mar10/fancytree",
    "files": {
      "basePath": "dist/",
      "include": ["*.min.js", "**/*.min.css", "**/*.gif"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/jquery.fancytree",
    "localVersions": ["2.3.0", "2.4.0", "2.4.1", "2.5.0", "2.6.0", "2.7.0", "2.8.0", "2.8.1", "2.9.0"],
    "remoteVersions": ["v2.0.0-1", "v2.0.0-2", "v2.0.0-3", "v2.0.0-4", "v2.0.0-5", "v2.0.0-6", "v2.0.0-7", "v2.0.0-8", "v2.0.0-9", "v2.0.0-10", "v2.0.0-11", "v2.0.0-12", "v2.0.0", "v2.1.0", "v2.2.0", "v2.3.0", "v2.4.0", "v2.4.1", "v2.5.0", "v2.6.0", "v2.7.0", "v2.8.0", "v2.8.1", "v2.9.0", "v2.10.0"],
    "branchVersions": []
  },
  "version": "v2.10.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/jquery.fancytree/2.10.0",
  "branch": "jquery.fancytree/v2.10.0"
}
```

### CODE REVIEW

**Comment by mar10** [comment]
Yes, I intentionally moved the themes folder.
Anything I should do here?

**Comment by jimaek** [comment]
I am worried that this change could break websites. If people link to these files directly the new version will result in 404 errors for them

**Comment by mar10** [comment]
Good point. I gave a 2nd thought and found a better solution. v2.10.1 is release, you can ignore v2.10.0

**Comment by jimaek** [comment]
Awesome, thanks

**Pull request closed without merging**
