### PR TITLE
Update project js-data to 3.0.0-alpha.7

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project js-data to 3.0.0-alpha.7.

@js-data

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "js-data",
    "repo": "js-data/js-data",
    "files": {
      "basePath": "dist/",
      "include": ["js-data.min.js"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/js-data",
    "localVersions": ["1.5.10", "1.5.11", "1.5.12", "1.5.13", "1.6.0", "1.6.1", "1.6.2", "1.6.3", "1.7.0", "1.8.0", "2.0.0-beta.1", "2.0.0-beta.3", "2.0.0-beta.4", "2.0.0-beta.5", "2.0.0-beta.6", "2.0.0-beta.7", "2.0.0-beta.8", "2.0.0-beta.9", "2.0.0-beta.10", "2.0.0-beta.11", "2.0.0-rc.1", "2.0.0-rc.3", "2.0.0", "2.1.0", "2.2.0", "2.2.1", "2.2.2", "2.2.3", "2.3.0", "2.4.0", "2.5.0", "2.6.0", "2.6.1", "2.7.0", "2.8.0", "2.8.1", "2.8.2", "3.0.0-alpha.1", "3.0.0-alpha.2", "3.0.0-alpha.3", "3.0.0-alpha.6"],
    "remoteVersions": ["0.0.1", "0.2.0", "0.3.1", "0.4.0", "0.4.1", "0.4.2", "1.0.0-alpha.1-0", "1.0.0-alpha.1-1", "1.0.0-alpha.1-2", "1.0.0-alpha.2", "1.0.0-alpha.3-0", "1.0.0-alpha.4-0", "1.0.0-alpha.4-1", "1.0.0-alpha.4-2", "1.0.0-alpha.4-3", "1.0.0-alpha.5-0", "1.0.0-alpha.5-1", "1.0.0-alpha.5-2", "1.0.0-alpha.5-4", "1.0.0-alpha.5-5", "1.0.0-alpha.5-6", "1.0.0-alpha.5-7", "1.0.0-alpha.5-8", "1.0.0-beta.1", "1.0.0-beta.2", "1.0.0", "1.1.0", "1.1.1", "1.2.0", "1.2.1", "1.3.0", "1.4.0", "1.4.1", "1.5.0", "1.5.1", "1.5.2", "1.5.3", "1.5.4", "1.5.5", "1.5.6", "1.5.7", "1.5.8", "1.5.9", "1.5.10", "1.5.11", "1.5.12", "1.5.13", "1.6.0", "1.6.1", "1.6.2", "1.6.3", "1.7.0", "1.8.0", "2.0.0-beta.1", "2.0.0-beta.2", "2.0.0-beta.3", "2.0.0-beta.4", "2.0.0-beta.5", "2.0.0-beta.6", "2.0.0-beta.7", "2.0.0-beta.8", "2.0.0-beta.9", "2.0.0-beta.10", "2.0.0-beta.11", "2.0.0-rc.1", "2.0.0-rc.2", "2.0.0-rc.3", "2.0.0", "2.1.0", "2.2.0", "2.2.1", "2.2.2", "2.2.3", "2.3.0", "2.4.0", "2.5.0", "2.6.0", "2.6.1", "2.7.0", "2.8.0", "2.8.1", "2.8.2", "3.0.0-alpha.1", "3.0.0-alpha.2", "3.0.0-alpha.3", "3.0.0-alpha.5", "3.0.0-alpha.6", "3.0.0-alpha.7"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/js-data/update.json",
  "version": "3.0.0-alpha.7",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/js-data/3.0.0-alpha.7",
  "branch": "js-data/3.0.0-alpha.7"
}
```

### CODE REVIEW

**Comment by tomByrer** [comment]
@megawac @jimaek Is the bot supposed to look at repo branches other than master?  Seems like it is grabbing from an alpha branch, when the [master version](https://github.com/js-data/js-data/blob/master/dist/js-data.min.js) is still in v2.x.  Bot is grabbing versions from the `v3` branch.

This repo is a good example why I don't think alphas belong on a CDN; 3 versions in just a few hours.  If a program is ready to be used publicly, it should not be labeled alpha.

**Comment by jimaek** [comment]
Its not using branches, its using tags https://github.com/js-data/js-data/releases

**Comment by tomByrer** [comment]
So the bot reads the files in the release files, or the actual repo?

**Comment by jimaek** [comment]
This is what its reading https://github.com/js-data/js-data/tree/3.0.0-alpha.7

**Comment by tomByrer** [comment]
Ahhh, now I understand better how GitHub works.  Cheers.

**Pull request merged**
