### PR TITLE
Add Library Spotter_Tools

### PR DESCRIPTION
**Pull request by exactsales**

### CODE REVIEW

**Comment by megawac** [comment]
You're library is going to need some documentation and a tagged release before we can proceed.

**Comment by exactsales** [comment]
Hi, it's done.

This library is just some external tools that we would like to add to our site using your CDN. That's why we don't have a good documentation.

**Comment by megawac** [comment]
jsdelivr is an open source CDN. Libraries hosted here should be open source, documented and applicable to more than just a single site. Sorry.

**Comment by exactsales** [comment]
Hi,

I got it. Sorry about that.

**Pull request closed without merging**
