### PR TITLE
Add dinamical.rcms to jsdelivr

### PR DESCRIPTION
**Pull request by estebanrfp**

### CODE REVIEW

**Comment by megawac** [comment]
What is this? I don't see documentation on the repo. jsdelivr hosts libraries and not assets for specific webspites

**Comment by estebanrfp** [comment]
no, is not an asset, its a core library, to many proyects, this core has de logical as jquery library, but exjecute in vanilla javascript the ajax methods and any other resources

**Comment by megawac** [comment]
No worries about language (you're doing better than I would)! I'll tentatively merge but can you try and get documentation on the github repo for what the project is. Thanks.

**Comment by estebanrfp** [comment]
Yes, i will prepare the documentation initial README.md, and thank you again for help us to continue width our project.

**Pull request merged**
