### PR TITLE
Update web interface instructions to create only one PR

### PR DESCRIPTION
**Pull request by dandv**
Fixes #6207

### CODE REVIEW

**Comment by jimaek** [comment]
I dont think this is accurate, you can simply create a new file by adding it to the same branch

**Comment by dandv** [comment]
I've been using GitHub for 6 years and failed to create the new file in the correct branch. An animated GIF (like the one for creating a file) would help.

**Comment by jimaek** [comment]
Looks like I was wrong. Thanks for the PR

**Comment by dandv** [comment]
:+1:

**Pull request merged**
