### PR TITLE
Changed Riot's update.json (added more files)

### PR DESCRIPTION
**Pull request by aurri**
The next Riot version will include new files: riot+compiler.js and riot+compiler.min.js.
Added them to update.json.

### CODE REVIEW

**Comment by jimaek** [comment]
Any chance to change the filenames? I am afraid that the + symbol could break stuff.

**Comment by aurri** [comment]
Yea, it's a bit unconventional, but I'm not aware of any evidence against using `+` in urls at least. Or do you mean it can break stuff on jsDelivr? Maybe that's a good change to find out then? :)

**Comment by jimaek** [comment]
It will definitely break the combination features when more than files are combined from a single project.
Example URL:
http://cdn.jsdelivr.net/g/jquery@2.1.0,angularjs@1.2.14(angular.min.js+angular-resource.min.js+angular-animate.min.js+angular-cookies.min.js+angular-route.min.js+angular-sanitize.min.js)
([docs](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request))

Technically I can merge it but then this feature wont work for riot

**Comment by aurri** [comment]
Well, you're right. Thanks for explaining!

Seems we could get the same result by just including `riot.min.js` and `compiler.min.js` and requesting them both with: http://cdn.jsdelivr.net/g/riot@2.0(riot.min.js+compiler.min.js)

Going to make that change then in a moment.

Thanks again.

**Comment by aurri** [comment]
Updated the filenames.

**Comment by jimaek** [comment]
Awesome, thank you!

**Pull request merged**
