### PR TITLE
add replay-table

### PR DESCRIPTION
**Pull request by antoniokov**
Add Replay Table project

### CODE REVIEW

**Comment by megawac** [comment]
you'll need to create a `git tag` before auto updating will begin

**Comment by antoniokov** [comment]
@megawac could you please explain where I should create the `git tag`?

**Comment by megawac** [comment]
nevermind me, I didn't realize it was npm sync and not github

**Comment by antoniokov** [comment]
@megawac actually, I've screwed up and packageManager should be github, not npm, so you're right :)
Could you please update the file directly?

**Comment by megawac** [comment]
Can you submit a pull request and create a git tag on the repo
https://help.github.com/articles/working-with-tags/

**Comment by antoniokov** [comment]
@megawac sure, done

**Pull request merged**
