### PR TITLE
Update project qoopido.demand to 1.0.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project qoopido.demand to 1.0.1.

@dlueth

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "qoopido.demand",
    "repo": "dlueth/qoopido.demand",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/qoopido.demand",
    "localVersions": ["1.0.0"],
    "remoteVersions": ["0.0.2", "1.0.0", "1.0.1"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/qoopido.demand/update.json",
  "version": "1.0.1",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/qoopido.demand/1.0.1",
  "branch": "qoopido.demand/1.0.1"
}
```

### CODE REVIEW

**Comment by dlueth** [comment]
Would like to know what is wrong with the info.ini and/or update.json so I can fix that :) There is one in /files/qoopido.demand of this repo and it should, at least as far as I can tell, be correct...

**Comment by jimaek** [comment]
Its an API issue, it didnt update yet. The delay will be fixed very soon.

**Comment by dlueth** [comment]
OK, sorry to have bothered you - just want to fix anything that might annoy you frequently :) Keep on rocking!

**Comment by jimaek** [comment]
np, let me know if you have any problems :)

**Pull request merged**
