### PR TITLE
Update project jquery-popup-window to v1.0.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project jquery-popup-window to v1.0.1.

@gasparesganga

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "jquery-popup-window",
    "repo": "gasparesganga/jquery-popup-window",
    "files": {
      "basePath": "/",
      "include": ["src/*.js", "src/*.css"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/jquery.popupwindow",
    "localVersions": [],
    "remoteVersions": ["v1.0.0", "v1.0.1"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/jquery.popupwindow/update.json",
  "versions": ["v1.0.1"],
  "updateRemote": true,
  "version": "v1.0.1",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/jquery.popupwindow/1.0.1",
  "branch": "jquery-popup-window/v1.0.1"
}
```

### CODE REVIEW

**Comment by gasparesganga** [comment]
Well, it seems both `info.ini` and `update.json` are in place. The library has just been merged and added to jsDelivr.

**Comment by megawac** [comment]
I think the issue is with the api? Its not retrieving http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery.popupwindow properly.

**Comment by gasparesganga** [comment]
It's working now, I haven't changed anything so it seems you did something to fix it, thank you!

**Comment by megawac** [comment]
Awesome :tada:

**Pull request merged**
