### PR TITLE
update info.ini

### PR DESCRIPTION
**Pull request by sutara79**

### CODE REVIEW

**Comment by megawac** [comment]
Are these not correct https://github.com/jsdelivr/jsdelivr/tree/master/files/jquery.ajax-combobox?

**Comment by sutara79** [comment]
These are correct.
I wanted to re-send `info.ini` for following instruction.

> Looks like the info.ini has a few problems
> jquery.ajax-combobox has no info.ini file buddy

https://github.com/jsdelivr/jsdelivr/pull/5528

**Comment by megawac** [comment]
Ah, don't worry about that - its an API syncing error. It happens frequently on the first auto update sync

**Comment by sutara79** [comment]
I see.
Thank you.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
@megawac Any idea why it doesnt like this PR?

**Comment by megawac** [comment]
Because there will be a merge conflict (this is a dupe)

**Comment by jimaek** [comment]
Oh I get it now :) Thanks

**Pull request closed without merging**
