### PR TITLE
adding autocompeter

### PR DESCRIPTION
**Pull request by peterbe**
See https://autocompeter.com

### CODE REVIEW

**Comment by jimaek** [comment]
Its not a good idea to have the version number in the filename. Once the version changes it could break functionality. Can you rename it please?

**Comment by peterbe** [comment]
@jimaek it's not a version number. It's part of the name. The server is a REST interface that puts a general version number on it. See the endpoints being mentioned in [the documentation](http://autocompeter.readthedocs.org/en/latest/api/).

**Comment by peterbe** [comment]
If you think it's a really bad idea, I can drop it (but keep it on the REST API) and use the semver directory structure instead.

**Comment by jimaek** [comment]
My only problem is that if you change the filename we will have to update info.ini with the new filename and then upload a custom mainfile override for all previous versions to ensure any combined URLs continue to work.

**Comment by jimaek** [comment]
Its up to you to decide. The rest looks good

**Comment by peterbe** [comment]
Hmm. Maybe you're right. I didn't think I'd have the pleasure of this nice semver system I get with jsdelivr. 

I think I'll drop the version number.

**Comment by peterbe** [comment]
@jimaek Ok. You convinced me. I decided to drop the `-v1` suffix in the filenames of the static files. 

Lastly I rebased it back into just one commit. Sadly, now I can't re-open this pull request. Can you?

**Comment by jimaek** [comment]
Haha awesome :)

Sorry cant open it, github wont let me https://www.dropbox.com/s/vgavxlov50taq08/Screenshot%202015-02-23%2021.31.23.png?dl=0

**Comment by peterbe** [comment]
[this then](https://github.com/jsdelivr/jsdelivr/pull/3574)

**Pull request closed without merging**
