### PR TITLE
Add update.json for isotope

### PR DESCRIPTION
**Pull request by hubdotcom**
Automatically update to latest releases of isotope

### CODE REVIEW

**Comment by pnommensen** [comment]
Looks like 'jquery.isotope.js' was included in all previous versions. Users who are using that file in production will face errors if they are using the /latest/ feature. 

@jimaek  thoughts?

**Comment by hubdotcom** [comment]
jquery.isotope.js is still included, it's in the /js directory, will update the json to reflect this

**Comment by hubdotcom** [comment]
@pnommensen how's this? https://github.com/hubdotcom/jsdelivr/commit/a4b68cb42dc5db6da82f31ad1cf885aabd10049c

**Comment by jimaek** [comment]
isotope.js is not the same as jquery.isotope.js

If you dropped the jquery from the name completely then there is nothing we can do, you can remove the js file and leave only dist/

**Comment by hubdotcom** [comment]
okay, so we are good to go with this?
```
{
  "packageManager": "github",
  "name": "isotope",
  "repo": "metafizzy/isotope",
  "files": {
    "basePath": "dist/"
  }
}
```

**Comment by jimaek** [comment]
Yes, looks good

**Comment by hubdotcom** [comment]
Single commit PR at https://github.com/jsdelivr/jsdelivr/pull/4292 - is this the preferred method of commiting to jsdelivr?

**Comment by jimaek** [comment]
Yes, we have a max of 2 commits per PR

**Pull request closed without merging**
