### PR TITLE
Adding new version of CSS Mint [v1.3.7]

### PR DESCRIPTION
**Pull request by ArunMichaelDsouza**

### CODE REVIEW

**Comment by ArunMichaelDsouza** [comment]
@jimaek can you please merge this PR. Thanks.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
Sorry it took so long. You can setup auto-updates if you want https://github.com/jsdelivr/jsdelivr#auto-updating

**Comment by ArunMichaelDsouza** [comment]
Sure no prob @jimaek :) Ill check it out.

**Pull request closed without merging**
