### PR TITLE
Astro updates the new file name

### PR DESCRIPTION
**Pull request by Ting-y**
- info.json and update.json both updated the new main file name

### CODE REVIEW

**Comment by Ting-y** [comment]
Should i remove the old releases from `jsdelivr/jsdelivr/files/astro/`? The latest release have renamed the core file.

**Comment by jimaek** [comment]
Dont remove anything. In info.ini leave the mainfile that is going to be added in all future versions, and in previous versions please create a new file called `mainfile` and write inside `astro-wp-element.min.js`

**Comment by Ting-y** [comment]
@jimaek i have edited my releases by adding the mainfile, see  https://github.com/getastro/Astro/releases

Inside the mainfile, i put the filename 'astro-wp-element.min.js', not the source code of 'astro-wp-element.min.js'

Let me know if i did it right

Thanks,

**Comment by Ting-y** [comment]
@jimaek I have seen the 0.3.0 is updated https://www.jsdelivr.com/?query=Astro, but the main file is not updated, could you give me a hint on what is happening in my repository. Thanks

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
