### PR TITLE
Update project matreshka to v0.4.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project matreshka to v0.4.1.

@finom

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "matreshka",
    "repo": "finom/matreshka",
    "files": {
      "include": ["matreshka.min.js", "matreshka.js", "matreshka.min.map"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/matreshka",
    "localVersions": ["0.3.0", "0.3.1", "0.3.2"],
    "remoteVersions": ["v0.0", "0.0.1", "0.0.2", "0.0.3", "v0.0.4", "v0.1.0", "v0.2.0", "v0.3.0", "v0.3.1", "v0.3.2", "v0.4.0", "v0.4.1"],
    "branchVersions": []
  },
  "version": "v0.4.1",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/matreshka/0.4.1",
  "branch": "matreshka/v0.4.1"
}
```

### CODE REVIEW

**Comment by finom** [comment]
@jimaek I've pushed the latest version of matreshka recently but jsdelivr didn't update "latest" folder. What's wrong?
http://cdn.jsdelivr.net/matreshka/latest/matreshka.min.js
http://cdn.jsdelivr.net/matreshka/0.4.1/matreshka.min.js

**Comment by jimaek** [comment]
/latest/ takes 7 days to purge the cache to make sure users see performance benefits from using jsDelivr.

I purged the /latest/ file manually for you. If this is important for you then send me an email and I will give you the instructions how to purge the cache of jsDelivr yourself. (just make sure you dont make it public to avoid abuse)

**Comment by finom** [comment]
@jimaek a[ухо]odessite.com.ua

Thanks!

**Comment by jimaek** [comment]
Email sent

**Pull request merged**
