### PR TITLE
Added apiNG plugin for wikipedia

### PR DESCRIPTION
**Pull request by JohnnyTheTank**
Added https://github.com/JohnnyTheTank/apiNG-plugin-wikipedia

### CODE REVIEW

**Comment by JohnnyTheTank** [comment]
@fczuardi hi, could you merge?

**Comment by jimaek** [comment]
@MartinKolarik @megawac Can one of you please check this and merge if its good? Im traveling and cant review it (internet super sucks)

**Comment by jimaek** [comment]
@megawac Thank you!

**Comment by JohnnyTheTank** [comment]
thx

**Comment by megawac** [comment]
sure thing @jimaek

**Pull request merged**
