### PR TITLE
Showdownjs Create info.ini

### PR DESCRIPTION
**Pull request by tivie**
There's already an older version of showdown registered but I couldn't get it to update

### CODE REVIEW

**Comment by tivie** [comment]
https://github.com/tivie/jsdelivr/tree/patch-2

**Comment by jimaek** [comment]
What do you mean? Your PR is here under review https://github.com/jsdelivr/jsdelivr/pull/5006

**Comment by tivie** [comment]
I was referring to https://github.com/jsdelivr/jsdelivr/tree/master/files/showdown

It's the same library (someone must've added it to jsdelivr) but your bot complained about a non-existing minified version or something. Do you mind deleting the old reference?

**Comment by tivie** [comment]
The only reference to showdown I could find in issues was this one (https://github.com/jsdelivr/jsdelivr/pull/733)

**Pull request closed without merging**
