### PR TITLE
Update tablesorter

### PR DESCRIPTION
**Pull request by Mottie**
* The `info.ini` contained outdated information
* Added `update.json`

### CODE REVIEW

**Comment by Mottie** [comment]
The site does not seem to be updating... I just released [v2.28.1](https://github.com/Mottie/tablesorter/releases/tag/v2.28.1), but jsdelivr hasn't updated yet: http://www.jsdelivr.com/?query=tablesorter (still set to v2.17.4). Did I miss something?

**Comment by megawac** [comment]
Not sure, it should be picking that up.

I pushed https://github.com/jsdelivr/jsdelivr/commit/6d029bcac4589bdc81f77d1b9e0209be57160676 as an attempt fix but if it doesn't I'll look into further

**Comment by Mottie** [comment]
Do I need to push a release to trigger another update?

**Comment by megawac** [comment]
No the existing ones should be fine. The bot works by polling all observed
repos

**Comment by megawac** [comment]
@MartinKolarik any thoughts here?

**Comment by MartinKolarik** [comment]
Not sure right now - libgrabber downloads the files but fails on `git commit`

**Comment by Mottie** [comment]
It's working great now thanks!

**Pull request merged**
