### PR TITLE
Add slimmage 0.4.1

### PR DESCRIPTION
**Pull request by perosb**
adding slimmage

### CODE REVIEW

**Comment by perosb** [comment]
Can auto update download from github releases?
If so is there an example of such a file?

In the slimmage case the .min.js is not packaged in anyway.

https://github.com/imazen/slimmage/releases/download/0.4.1/slimmage.min.js

**Comment by jimaek** [comment]
Here you go https://github.com/jsdelivr/jsdelivr#auto-updating

**Comment by perosb** [comment]
Thanks. Need to look at that later. The documentation only describes when the files are part of the dist tarball.
In this case it is not, only as separate download.

**Comment by jimaek** [comment]
Do you deploy the min file to npm or bower? Our bot can work with that too

**Comment by perosb** [comment]
I dont think so. I'm not the developer nor maintainer, but asked if it can be included in future releases.

Thanks!

**Comment by jimaek** [comment]
Yeah unfortunately I dont see any other way. Its either github tags, npm or bower. Maybe add the min somewhere to we could enable auto-updates?

**Comment by perosb** [comment]
Well, the min.js is added as a separate download in the tag/release: https://github.com/imazen/slimmage/releases/tag/0.4.1

Not sure if the bot can pull single files like that?
https://github.com/imazen/slimmage/releases/download/0.4.1/slimmage.min.js

**Comment by jimaek** [comment]
This is what the bot sees https://github.com/imazen/slimmage/tree/v0.2.6

**Pull request merged**
