### PR TITLE
Update project bootswatch to v3.3.5+2

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project bootswatch to v3.3.5+2.

@thomaspark

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "bootswatch",
    "repo": "thomaspark/bootswatch",
    "files": {
      "exclude": ["2/**", "api/**", "assets/**", "bower_components/**", "custom/**", "default/**", "global/**", "help/**", "tests/**", "*(.gitignore|.travis.yml|CNAME|Gemfile|Gruntfile.js|LICENSE|README.md|_config.yml|bower.json|composer.json|favicon.ico|index.html|package.json)"],
      "include": ["**/*"]
    },
    "path": "/home/jsdelivr/files/bootswatch",
    "localVersions": ["3.0.0", "3.0.3-b", "3.1.0", "3.1.1", "3.3.2"],
    "remoteVersions": ["v2.0.0", "v2.0.1", "v2.0.2", "v2.0.3", "v2.0.4", "v2.1.0", "v2.1.1", "v2.1.1+1", "v2.2.2", "v2.2.2+1", "v2.2.2+2", "v2.3.0", "v2.3.0+1", "v2.3.0+2", "v2.3.1", "v2.3.1+1", "v2.3.2", "v3.0.0-rc1", "v3.0.0-rc2", "v3.0.0", "v3.0.1", "v3.0.2+1", "v3.0.2+2", "v3.0.2", "v3.0.3+1", "v3.0.3", "v3.1.0", "v3.1.0+1", "v3.1.1", "v3.1.1+1", "v3.2.0+3", "v3.2.0+1", "v3.2.0+2", "v3.2.0+4", "v3.2.0", "v3.3.0", "v3.3.1", "v3.3.1+1", "v3.3.1+2", "v3.3.1+3", "v3.3.2", "v3.3.4", "v3.3.4+1", "v3.3.5+1", "v3.3.5", "v3.3.5+2"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/bootswatch/update.json",
  "version": "v3.3.5+2",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/bootswatch/3.3.5",
  "branch": "bootswatch/v3.3.5+2"
}
```

### CODE REVIEW

**Comment by markcarver** [comment]
@jimaek, this looks much, much better :) We're definitely getting really close.

This PR has brought up three major concerns/inconsistencies for me:

1. Older/all versions are not picked up. I'm not sure what the problem is on this one. You will notice that https://github.com/thomaspark/bootswatch/tree/v3.0.2 exists, but is not in https://github.com/jsdelivr/jsdelivr/tree/master/files/bootswatch. At first I thought it was just because the bot only checks what has changed past the latest version in the repo. However, if this were the case, it should have picked up version 3.3.4 in this PR, but it did not. Why not?
2. The "amelia" theme was removed in 3.3.0 (and subsequently all versions moving forward), yet currently exists in version 3.3.2 of jsDelivr's copy: https://github.com/jsdelivr/jsdelivr/tree/master/files/bootswatch/3.3.2/amelia. As you can see, there is no "amelia" at the source: https://github.com/thomaspark/bootswatch/tree/v3.3.2.
3. I originally didn't exclude the source files was because they already exist in existing jsDevlir/boowswatch folders, see: https://github.com/jsdelivr/jsdelivr/tree/master/files/bootswatch/3.0.0/cerulean (which contains bootswatch.less, index.html, thumbnail.png and variables.less). However, I would imagine that these should also be excluded (if needed, they should be using the source to begin with).

Due to the previous manual iterations of this project on jsDelivr, would it make more sense to just remove the existing versions/folder and let the bot populate everything automatically to remedy these inconsistencies?

**Comment by jimaek** [comment]
1. The bot adds only the latest version. We dont try to host every single version, just the latest
2. Looks like a bug. We can ignore if I believe

Like I said in the other topic we cant remove any files, only improve the next versions

**Comment by markcarver** [comment]
> We dont try to host every single version

I think you're missing the point... these _must_ be fixed, either that or http://api.jsdelivr.com/v1/bootstrap/libraries/bootswatch needs to be changed to reflect what is actually _served_ by jsDelivr.

**Comment by markcarver** [comment]
Which is an issue for themes in CMS' like Drupal, who utilize this api to provide a UI toggle to switch themes: https://www.drupal.org/node/2452617

**Comment by jimaek** [comment]
Indeed im missing something. You want me to add all the missing versions?

**Comment by markcarver** [comment]
http://api.jsdelivr.com/v1/bootswatchlibraries does not exist.

The only recourse is to use http://api.jsdelivr.com/v1/bootstrap/libraries/bootswatch (which is technically from https://github.com/MaxCDN/bootstrap-cdn and they have all of Bootswatch's versions/themes).

However, since this is just and API (with no default base_url btw), I'm left with having to choose how to construct this URL.

I'm saying that there are inconsistencies between what jsDelivr API _says exists_ and _what is actually_ in jsDelivr's repo.

That's why I was saying that the folders should just be removed and it be repopulated with the _correct_ repo information. I'd rather have the bot do this automatically, than me having to do this manually.

I know _in theory_ it could possibly break someone's site... but this is actually _very highly unlikely_. We'd still have the same files (albeit minus source files like `*.less` and whatnot, but those wouldn't/shouldn't be used anyway).

**Comment by jimaek** [comment]
This is the jsDelivr API call for bootswatch http://api.jsdelivr.com/v1/jsdelivr/libraries/bootswatch
This http://api.jsdelivr.com/v1/bootstrap/libraries/bootswatch is https://github.com/MaxCDN/bootstrap-cdn/tree/develop/public/bootswatch

I don't see any inconsistencies, and they cant be any, the API pulls the data from the repo.

**Comment by markcarver** [comment]
Ok, maybe this will help clear up some confusion on my part. To avoid having to initiate multiple requests, I'm simply using http://api.jsdelivr.com/v1/bootstrap/libraries and then parsing that entire JSON data ([source](http://cgit.drupalcode.org/bootstrap/tree/includes/cdn.inc#n49)).

Because there is no "base path/url" provided by the API (as I have brought up in https://github.com/jsdelivr/api/issues/56#issuecomment-108691577), I inadvertently used ([source](http://cgit.drupalcode.org/bootstrap/tree/includes/cdn.inc#n189)):

`//cdn.jsdelivr.net/bootstrap/$version`
`//cdn.jsdelivr.net/bootswatch/$version`

When they should, in fact, be using:

`//maxcdn.bootstrapcdn.com/bootstrap/$version`
`//maxcdn.bootstrapcdn.com/bootswatch/$version`

Unfortunately, maxcdn.bootstrapcdn.com is just one CDN, not the multi-architecture that comes with jsDelivr. I would much rather keep these URLs at cdn.jsdelivr.net. The reason I started this auto-update process for bootswatch is because I noticed that when I started switching themes (especially past 3.3.2), the site would become un-styled (missing assets). This led me to start digging and found out that jsDelivr's bootswatch repo wasn't being automatically updated (hence the PRs). I also assumed that this would fill in the missing pieces.

If this were still a manual process, I may have been forced to switch the URLs to maxcdn.bootstrapcdn.com. However, now that the jsDelivr bootswatch repo is updated automatically, I think it will be safe to continue using cdn.jsdelivr.net/bootswatch; that is if I manually fill in the missing 3.x.x versions.

**Comment by jimaek** [comment]
I see. Well I guess then we fixed this and you can keep using jsDelivr?
Thanks for using our CDN over others btw :)

Feel free to ping me if you ever need anything

**Comment by markcarver** [comment]
It's partially fixed, I will submit another PR very shortly that manually adds the missing versions.

**Pull request closed without merging**
