### PR TITLE
Added Countly Web SDK

### PR DESCRIPTION
**Pull request by ar2rsawseen**

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
Hmm, website works normally, is there a way to restart bot?

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by ar2rsawseen** [comment]
Hello,
we pushed new version on Friday (19th Feb.) but nothing still appeared on jsdeliver cdn, are there any problems?

**Comment by jimaek** [comment]
@MartinKolarik Can you please take a look? I cant find any config problem. Could it be a bot bug?

**Comment by MartinKolarik** [comment]
@jimaek It's a bug in libgrabber, or more precisely in semvish, which libgrabber heavily relies upon. It can't parse the version number `16.02.0` because of the leading zero in the second group.

**Comment by MartinKolarik** [comment]
Also, there's a problem with `info.ini`. `mainfile` should be `countly.min.js`, not `lib/countly.min.js`.

**Comment by jimaek** [comment]
Yeah I saw the info.ini issue. Can you fix libgrabber please?

**Comment by MartinKolarik** [comment]
Sent you a PR.

**Comment by ar2rsawseen** [comment]
Sorry for the inconvenience, should I make another PR for the main file?

**Comment by jimaek** [comment]
@ar2rsawseen Its live now http://www.jsdelivr.com/projects/countly-sdk-web
No need to change anything

**Comment by ar2rsawseen** [comment]
Thank you :)

**Pull request closed without merging**
