### PR TITLE
Add Esri Leaflet

### PR DESCRIPTION
**Pull request by patrickarlt**
Note `esri-leaflet.js` is a minified file. Its just following Leaflets conventions for `file.js` and `file-src.js`

### CODE REVIEW

**Comment by patrickarlt** [comment]
@jimaek Not sure what to do about this name mismatch. Is this a known issue with the bot if the name of the package on NPM is different then the folder name in jsdelivr?

**Comment by megawac** [comment]
Thanks @patrickarlt big fan (of you and esri leaflet), be a sec (I want to see this on here was going to add it myself a couple months ago)

**Comment by megawac** [comment]
@patrickarlt any reason your calling it `leaflet.esri` instead of `esri-leaflet`? (thats all the issue is)
https://github.com/jsdelivr/bot/blob/7d2171527224582a466d0695ae902a3dbc08f1ce/util/validate_update_json.py

**Comment by patrickarlt** [comment]
@jimaek mentioned he would prefer it as `leaflet.esri` in https://github.com/jsdelivr/jsdelivr/pull/4474#issuecomment-96042795 since this is a plugin for Leaflet. It looks like that the pattern for a lot of other stuff like `angular.all` or `bootstrap.calender`. I suppose I could just change the `packageManager` to `github` to get around this but it does look like a validation bug in the bot.

@jimaek Your call. I'm more then happy to reopen using `github` as opposed to NPM if you want.

**Comment by megawac** [comment]
`npm` is no prob, I just made a stupid decision to validate the repo name matches the jsdelivr name in bot (I'll get around to it)

**Pull request merged**
