### PR TITLE
Create IranAddressJS.js folder

### PR DESCRIPTION
**Pull request by HosseinRashno**
Hi
I add to js file for IranAddressJS jquery plugin.
IranAddressJS is a jQuery plugin that provides selection for city and province fields (of Iran) in a form.
Best regards.
H.Rashno

### CODE REVIEW

**Comment by pnommensen** [comment]
Is the non minified file necessary for production use? Please add https://github.com/hossein361224/IranAddressJS to the github param in info.ini.

**Comment by HosseinRashno** [comment]
I delete minified file an now i just have one file. and i correct the info.ini file.

**Comment by jimaek** [comment]
@pnommensen Check it out when you can please

**Comment by pnommensen** [comment]
I do not see the minified version here. Also, please squash your commits.

**Comment by megawac** [comment]
This seems fine unminified (it's pretty small). I'm just going to merge

@jsdelivrbot squash and merge s.v.p.

**Pull request closed without merging**
