### PR TITLE
Create HubSpot drop / update.json

### PR DESCRIPTION
**Pull request by dandv**
Continues PR #6206

### CODE REVIEW

**Comment by jimaek** [comment]
Please use 1 PR per project and include all files there.

**Comment by dandv** [comment]
How can I create two files in the same PR, as the [web interface instructions](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md#web-interface-recommended) recommends?

**Comment by jimaek** [comment]
https://help.github.com/articles/using-pull-requests/#sending-the-pull-request
>After your pull request is sent, any new commits pushed to your branch will automatically be added to the pull request. This is especially useful if you need to make more changes.

**Comment by dandv** [comment]
That's nice but a specific should be added to the instructions. It didn't happen naturally as I created the second file.

**Pull request closed without merging**
