### PR TITLE
Update project jquery to 1.12.0 and 2.2.0

### PR DESCRIPTION
**Pull request by swcheon**
Please check this commit. :-)

### CODE REVIEW

**Comment by swcheon** [comment]
Could you check this commit manually?

**Comment by tomByrer** [comment]
@swcheon the bot warned you that you changed the file names.  It is correct.

**Comment by jimaek** [comment]
Thank you

**Comment by tomByrer** [comment]
Thanks @swcheon

**Comment by swcheon** [comment]
@tomByrer My pleasure :)

**Pull request merged**
