### PR TITLE
Update project jquery.placeholder to v2.1.0 (and enable Auto-Updating)

### PR DESCRIPTION
**Pull request by thekondrashov**
[HTML5 Placeholder jQuery Plugin](https://github.com/mathiasbynens/jquery-placeholder)

### CODE REVIEW

**Comment by thekondrashov** [comment]
@jimaek add new version please

**Comment by jimaek** [comment]
Can you please squash your commits into 1?

**Comment by thekondrashov** [comment]
No. Sorry about the 7 commits; still using web client.

**Comment by jimaek** [comment]
I cant merge it like this. If you want you can create a new PR with only the info.ini and update.json. The bot will update the version itself.

**Comment by thekondrashov** [comment]
Thank you. Of course, I'll do it. But it will cost two commits in the web client. The bot will be able to upgrade in this case?

**Comment by jimaek** [comment]
2 commits is better than 7. Yes the bot will add the files automatically

**Pull request closed without merging**
