### PR TITLE
Adding file 525icons

### PR DESCRIPTION
**Pull request by runestro**
I hope I have done it right. Thanks!
runestro@gmail.com

### CODE REVIEW

**Comment by jimaek** [comment]
There are no tags here https://github.com/runestro/525icons/releases
The bot will fail

**Comment by runestro** [comment]
Hi 
Thank you. I have added a tag now. I was'n aware that it was necessary.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by runestro** [comment]
Thank you very much! Awesome!

**Pull request closed without merging**
