### PR TITLE
Add ol3.layerswitcher

### PR DESCRIPTION
**Pull request by balmeras**

### CODE REVIEW

**Comment by jimaek** [comment]
Please rename the directory to `openlayers.layerswitcher`

**Comment by balmeras** [comment]
Done (openlayers instead of ol3)

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by walkermatt** [comment]
@balmeras thanks, is there anything I need to do or be aware of other than tag versions in future?

**Comment by balmeras** [comment]
Thank you @walkermatt :)
Maybe one thing you can do: could you please provide a minified version of your js code ?

**Pull request closed without merging**
