### PR TITLE
Update project imagesloaded to v3.1.8

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project imagesloaded to v3.1.8.

@desandro

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "imagesloaded",
    "repo": "desandro/imagesloaded",
    "files": {
      "include": ["imagesloaded.js", "imagesloaded.min.js", "imagesloaded.pkgd.js", "imagesloaded.pkgd.min.js"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/imagesloaded",
    "localVersions": ["2.1.0", "3.0.1", "3.0.4", "3.1.0", "3.1.4", "3.1.6"],
    "remoteVersions": ["v1.0.0", "v1.0.1", "v1.0.2", "v1.0.3", "v1.0.4", "v1.1.0", "v1.2.0", "v1.2.1", "v1.2.2", "v1.2.3", "v1.2.4", "v2.0.0", "v2.0.1", "v2.1.0", "v2.1.1", "v2.1.2", "v3.0.0", "v3.0.1", "v3.0.2", "v3.0.3", "v3.0.4", "v3.1.0", "v3.1.1", "v3.1.2", "v3.1.3", "v3.1.4", "v3.1.5", "v3.1.6", "v3.1.7", "v3.1.8"],
    "branchVersions": []
  },
  "version": "v3.1.8",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/imagesloaded/3.1.8",
  "branch": "imagesloaded/v3.1.8"
}
```

### CODE REVIEW

**Comment by hubdotcom** [comment]
See conversation with developer here https://github.com/desandro/imagesloaded/issues/187

The file imagesloaded.min.js has been removed as it is not useful on it's own (the packaged script is the essential lib). Can we can get this request approved to pull 3.1.8?

**Comment by jimaek** [comment]
Why such a big change happened between minor versions? 3.1.6 had it and 3.1.8 does not?

In this case we will have to manually add this file until a more major version is released where we can do the change.

**Comment by hubdotcom** [comment]
Essentially the main file has changed from imagesloaded.js to imagesloaded.pkgd.js - this was changed in the 3.1.5 release https://github.com/desandro/imagesloaded/releases/tag/v3.1.5

A core developer has stated there is no use for the imagesloaded.min.js in a production environment and therefore he prefers not to include it. So we would have to manually include a minified script that has no use indefinitely

**Comment by jimaek** [comment]
We need to add this file manually until they release a major update. For example 3.2.x
Because people that use this file with version aliasing will end up with broken websites otherwise

**Comment by hubdotcom** [comment]
No problem, will get that updated

**Pull request closed without merging**
