### PR TITLE
Easing - created jquery.easing.1.3.min.js

### PR DESCRIPTION
**Pull request by Arg0n4th**
Created the min version of jquery.easing.1.3.js --> jquery.easing.1.3.min.js

### CODE REVIEW

**Comment by jimaek** [comment]
What are you trying to do? You have 90 commits in this PR

**Comment by Arg0n4th** [comment]
I'm trying to commit only a brach at time, but I don't know how to kill all the old commits. I tryed to delete all the files but you refused this PR. Please help me to clean my repository :)

**Comment by jimaek** [comment]
just delete your repo and reclone it, that would be the easiest way. Otherwise just google it

**Comment by Arg0n4th** [comment]
I found where to delete the repo online. I reacreate a new for/branch and proposed only 1 file :)

**Pull request closed without merging**
