### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Petrovich-Z**
Add my script to your cdn, please.

### CODE REVIEW

**Comment by megawac** [comment]
fyi i merged, but you'll need to create a git tag before auto updating will take place

**Comment by Petrovich-Z** [comment]
What I'm doing wrong? I added a tag to my project yesterday, but my project folder contains only info.ini and update.json.

**Comment by megawac** [comment]
gss4tilda.min.js doesn't exist in the root directory. You should add basePath `src/js`

**Comment by Petrovich-Z** [comment]
Thank you.

**Pull request merged**
