### PR TITLE
Added autocomplete.js

### PR DESCRIPTION
**Pull request by redox**
[algolia/autocomplete.js](https://github.com/algolia/autocomplete.js) is a JS library providing a fast and fully-featured auto-completion menu.

### CODE REVIEW

**Comment by jimaek** [comment]
Is this a jquery plugin? If so then can you rename the directory to `jquery.autocomplete.js` or `jquery.autocomplete` please?

**Comment by redox** [comment]
Hi @jimaek,

currently only a jQuery build is available but we plan to add an Angular.js (and probably others) in the future. Is it OK to keep that name?

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
@redox Sure, thanks for the PR :+1:

**Comment by redox** [comment]
Thank you very much @jimaek :+1:

**Pull request closed without merging**
