### PR TITLE
sparkly

### PR DESCRIPTION
**Pull request by Asaf-S**

### CODE REVIEW

**Comment by Asaf-S** [comment]
Thank you!

**Comment by Asaf-S** [comment]
Hey there,
may I know why was this PR closed instead of being merged?

Thx,
Asaf

**Comment by jimaek** [comment]
We are preparing to launch our new backend which will automatically work with your project. Wait a couple of days and then check out our readme for instructions.

**Comment by Asaf-S** [comment]
Hey thanks for the quick answer!

I'd really appreciate if you'll approve my PR sooner, preferably now,
because we have a tight deadline and unfortunately I cannot wait that
long...
I promise to update any file needed in order to work with your new backend
- the minute it will be available! So there is no need to withhold the PR
in order to ensure that my files will be updated...

Please reconsider,
Asaf.

**Comment by jimaek** [comment]
http://cdn.jsdelivr.net/gh/Asaf-S/sparkly@v1.0/timeline.min.js

**Comment by Asaf-S** [comment]
THXXXXXXX!!!!

Looking forward for an update about your new shiny backend :)

Asaf.

**Comment by Asaf-S** [comment]
Hey, is the new backend ready?
I want to update some files.

Thx,
Asaf

**Comment by jimaek** [comment]
The new backend is live. To update files you need to either update your repo or npm. 
Instructions https://github.com/jsdelivr/jsdelivr#usage

**Pull request closed without merging**
