### PR TITLE
jquery.payment - Add all files from project to include minified version as well

### PR DESCRIPTION
**Pull request by delmicio**
Get all files from project not just the main unminified version.

### CODE REVIEW

**Comment by jimaek** [comment]
why?

**Comment by delmicio** [comment]
@jimaek to include the minified version. Right now only the unminified version is grabbed by the boot.

**Comment by delmicio** [comment]
@jimaek why is not the minified version available yet in http://www.jsdelivr.com/projects/jquery.payment? is the bot not getting this change?

**Comment by jimaek** [comment]
because there are no new versions released. The change will apply only to new versions and not to old.

**Comment by delmicio** [comment]
A new version may not come soon, months even.
Can it be applied to the latest at least?

**Comment by jimaek** [comment]
It must be done manually, if you want you can open a PR adding that file

**Pull request merged**
