### PR TITLE
Add sprintf.js

### PR DESCRIPTION
**Pull request by MartinKolarik**

### CODE REVIEW

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by MartinKolarik** [comment]
>jsdelivrbot squash and merge

Wow, that's a cool trick!

**Comment by jimaek** [comment]
yup, I love it :)

**Comment by MartinKolarik** [comment]
@jimaek Is there a problem with the API? It still doesn't list this project.

**Comment by jimaek** [comment]
yes, the files are uploaded but the API is delayed.

**Pull request closed without merging**
