### PR TITLE
Update project Buttons.css to v1.1.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project Buttons.css to v1.1.0.

@Dog2puppy

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "Buttons.css",
    "repo": "Dog2puppy/Buttons.css",
    "files": {
      "basePath": "/",
      "include": ["buttons.css", "buttons.min.css"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/buttons.css",
    "localVersions": ["1.0.1"],
    "remoteVersions": ["0.1", "1.0", "v1.0.1", "v1.1.0"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/buttons.css/update.json",
  "versions": ["v1.1.0"],
  "updateRemote": true,
  "version": "v1.1.0",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/buttons.css/1.1.0",
  "branch": "Buttons.css/v1.1.0"
}
```

### CODE REVIEW

**Comment by Dog2puppy** [comment]
Uh oh...

**Comment by megawac** [comment]
let me know if you want me to merge @Dog2puppy (mainfile will need to be updated)

**Comment by Dog2puppy** [comment]
Why would it need updated?

**Comment by megawac** [comment]
if you were to try to use a url that maps to th emainfile, such as below, it won't map correctly

https://cdn.jsdelivr.net/g/buttons.css

**Pull request merged**
