### PR TITLE
Update project cilantro to 2.3.9

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project cilantro to 2.3.9.

@chop-dbhi

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "cilantro",
    "repo": "chop-dbhi/cilantro",
    "files": {
      "basePath": "cdn/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/cilantro",
    "localVersions": ["2.2.22", "2.2.23", "2.2.24", "2.2.25", "2.2.26", "2.2.27", "2.2.28", "2.2.29", "2.2.30", "2.2.31", "2.2.32", "2.2.35", "2.2.36", "2.3.0", "2.3.1", "2.3.2", "2.3.3", "2.3.4", "2.3.5", "2.3.6", "2.3.7", "2.3.8"],
    "remoteVersions": ["2.0.0", "2.0.1", "2.0.10", "2.1.0", "2.1.1", "2.1.2", "2.1.3", "2.1.4", "2.1.5", "2.1.6", "2.2.0", "2.2.1", "2.2.2", "2.2.3", "2.2.4", "2.2.5", "2.2.6", "2.2.7", "2.2.8", "2.2.9", "2.2.10", "2.2.11", "2.2.12", "2.2.13", "2.2.14", "2.2.15", "2.2.16", "2.2.17", "2.2.18", "2.2.19", "2.2.20", "2.2.21", "2.2.22", "2.2.23", "2.2.24", "2.2.25", "2.2.26", "2.2.27", "2.2.28", "2.2.29", "2.2.30", "2.2.31", "2.2.32", "2.2.33", "2.2.34", "2.2.35", "2.2.36", "2.3.0", "2.3.1", "2.3.2", "2.3.3", "2.3.4", "2.3.5", "2.3.6", "2.3.7", "2.3.8", "2.3.9"],
    "branchVersions": []
  },
  "version": "2.3.9",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/cilantro/2.3.9",
  "branch": "cilantro/2.3.9"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@bruth Hey, no more `css/style.css.map` or is this a bug?

**Comment by bruth** [comment]
@jimaek No more `css/style.css.map`. In fact [it should have never been there](https://github.com/chop-dbhi/cilantro/blob/2.3.x/Gruntfile.js#L129).. but I it may have been a bug in the node sass module.

**Comment by jimaek** [comment]
Awesome, thanks

**Comment by bruth** [comment]
Thank _you_ and for checking about the file.

**Pull request merged**
