### PR TITLE
highcharts ng initial version

### PR DESCRIPTION
**Pull request by akkumar**
Initial Version of highcharts-ng : 

Available at: https://github.com/pablojim/highcharts-ng

### CODE REVIEW

**Comment by jimaek** [comment]
Please rename the directory to `angular.highcharts`.
The rest looks good

**Comment by akkumar** [comment]
There seems to be another different project as well ( called https://github.com/rootux/angular-highcharts-directive ) , independent of this.  Hence, using the same name as the original author had used. 

Let me know if this looks ok.

**Comment by jimaek** [comment]
For that project we could use `angular.highcharts-directive`

**Comment by akkumar** [comment]
Renamed the package as per the discussion.

**Pull request merged**
