### PR TITLE
roundSlider plugin added1

### PR DESCRIPTION
**Pull request by soundar24**
1) A new plugin roundSlider was added. You can find more details form here: http://roundsliderui.com/

2) GitHub repository link: https://github.com/soundar24/roundSlider

### CODE REVIEW

**Comment by soundar24** [comment]
From the above i need to delete the failed files, the remaining two files are the correct. What can i do now ? Please let me know how to push the remaining two files only.

**Comment by soundar24** [comment]
Hi, what should i do now ? when it will be included in the CDN ? where can i get the further details ?

**Comment by jimaek** [comment]
Please rename the directory to `jquery.roundslider`

**Comment by soundar24** [comment]
renamed the directory to jquery.roundslider

But note that the file inside this folder having the name roundslider.min.js only, changing this name is not possible. Because it cause the overall the filename change of my plugin. And also in all other places  I used this file name only. So please consider this.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
@soundar24 http://www.jsdelivr.com/#!jquery.roundslider

**Comment by soundar24** [comment]
@jimaek  Thank you ... :+1:

**Pull request closed without merging**
