### PR TITLE
Update imagesloaded to latest

### PR DESCRIPTION
**Pull request by hubdotcom**
Apologies for the 4 commits - didn't want to clone the entire repo to get this added

### CODE REVIEW

**Comment by jimaek** [comment]
What is the source for these files? The repo doesnt have the min file anymore

**Comment by hubdotcom** [comment]
Compressed with UglifyJS2 default settings via http://refresh-sf.com/

Author has stated he no longer sees any point to support the imagesloaded.min.js - he said it's useless without the packages so only the pkgd min will be uploaded (#4296).

**Comment by jimaek** [comment]
@hubdotcom Just add the min file. I merged the other files from the bot's PR

**Comment by hubdotcom** [comment]
Should we still add the imagesloaded.min.js or should we phase this out?

**Comment by pnommensen** [comment]
There should always be a min file. Mind asking the author of this lib to include in the packaged build?

**Comment by hubdotcom** [comment]
I did - see thread above. Author says the non packaged file is useless without the dependencies so a min file would not be suitable for a production environment

**Comment by hubdotcom** [comment]
Author changed the name of the core file from the .min.js to the .pkdg.min.js in v3.1.5. Anyone that continues to use the /latest/ min.js will have their scripts break anyway

**Pull request closed without merging**
