### PR TITLE
[request] SocialMedia.js dynamic link sharing

### PR DESCRIPTION
**Pull request by bovidiu**

### CODE REVIEW

**Comment by megawac** [comment]
Hi you will need to include a version of your library (either with an update.json or an initial version) along with this PR

**Comment by bovidiu** [comment]
@megawac Please let me know if the file is correct. I've decided to use the update.json so that I can learn/see the file structure required by the system. 
Thank you.

**Comment by megawac** [comment]
you'll also need to create a git tag on your repo for updating to start taking place

**Comment by bovidiu** [comment]
@megawac is there a documentation that i can read for doing the tag ?

**Comment by megawac** [comment]
https://githowto.com/tagging_versions

**Pull request merged**
