### PR TITLE
Create update.json

### PR DESCRIPTION
**Pull request by redmunds**
I hope I'm doing this correctly.

Up until v2, balance-text was a jquery plugin named jquery.balancetext.js, and I want to maintain existing libs for older versions.

Starting with v3, balance-text lib no longer has jquery dependency so it's now balancetext.js .

### CODE REVIEW

**Comment by megawac** [comment]
Please also include an info.ini (https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md)

**Comment by redmunds** [comment]
@megawac I created info.ini in PR #16506. I'm not sure how to create second commit to existing branch via web interface.

**Comment by redmunds** [comment]
Sorry about extra commit. Please squash when merging.

**Comment by megawac** [comment]
no worries thanks

**Pull request merged**
