### PR TITLE
Create info.ini

### PR DESCRIPTION
**Pull request by goessner**

### CODE REVIEW

**Comment by goessner** [comment]
first commit of g2.mec

**Comment by megawac** [comment]
Hey @goessner you're going to have to start creating `git tags` for updating to work

https://github.com/goessner/g2-mec/releases

**Comment by goessner** [comment]
thanks for the hint ... done !

**Comment by goessner** [comment]
i don't know what to do else ...

* I copied a complete branch to my desktop 
* I reselved all my conflicts in g2.mec (also in previously working g2 and v2)
* I suddenly get scary conflicts in scrollreveal.min.js, which is not mine and which I didn't touch.

I'm quite clueless now .. sorry

**Pull request closed without merging**
