### PR TITLE
Update project highcharts to v5.0.5

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project highcharts to v5.0.5.

@highcharts

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "highcharts",
    "repo": "highcharts/highcharts",
    "files": {
      "basePath": "lib/",
      "exclude": ["*.src.js", "*.md", "*.json"],
      "include": ["**/*"]
    },
    "path": "/home/libgrabber/jsdelivr/files/highcharts",
    "localVersions": ["highmaps-v1.1.10", "highstock-v2.1.10", "2.2.4", "2.3.0", "2.3.2", "2.3.3", "3.0.1", "3.0.4", "3.0.7", "3.0.9", "4.0.0", "4.0.1", "4.0.3", "4.0.4", "4.1.0", "4.1.1", "4.1.2", "4.1.3", "4.1.4", "4.1.5", "4.1.6", "4.1.7", "4.1.8", "4.1.9", "4.2.3", "4.2.4", "4.2.5", "4.2.6", "5.0.2", "5.0.3", "5.0.4"],
    "remoteVersions": ["highstock-v1.1.6", "highstock-v1.2.0", "highstock-v1.2.1", "highstock-v1.2.2", "highstock-v1.2.3", "highstock-v1.2.4", "highstock-v1.2.5", "highstock-v1.3.0", "highstock-v1.3.1", "highstock-v1.3.2", "highstock-v1.3.3", "highstock-v1.3.4", "highstock-v1.3.5", "highstock-v1.3.6", "highstock-v1.3.7", "highstock-v1.3.8", "highstock-v1.3.9", "highstock-v1.3.10", "highstock-v2.0.0", "highstock-v2.0.1", "highstock-v2.0.3", "highstock-v2.0.4", "highstock-v2.1.0", "highstock-v2.1.1", "highstock-v2.1.2", "highstock-v2.1.3", "highstock-v2.1.4", "highstock-v2.1.5", "highstock-v2.1.6", "highstock-v2.1.7", "highstock-v2.1.8", "highstock-v2.1.9", "highstock-v2.1.10", "v2.0.2", "v2.0.3", "v2.0.4", "v2.0.5", "v2.1.0", "v2.1.1", "v2.1.2", "v2.1.3", "v2.1.4", "v2.1.5", "v2.1.6", "v2.1.7", "v2.1.8", "v2.1.9", "v2.2.0", "v2.2.1", "v2.2.2", "v2.2.3", "v2.2.4", "v2.2.5", "v2.3Beta", "v2.3.0", "v2.3.1", "v2.3.2", "v2.3.3", "v2.3.5", "v3.0Beta", "v3.0.0", "v3.0.1", "v3.0.2", "v3.0.3", "v3.0.4", "v3.0.5", "v3.0.6", "v3.0.7", "v3.0.8", "v3.0.9", "v3.0.10", "v4.0.0", "v4.0.1", "v4.0.3", "v4.0.4", "v4.1.0", "v4.1.1", "v4.1.2", "v4.1.3", "v4.1.4", "v4.1.5", "v4.1.6", "v4.1.7", "v4.1.8", "v4.1.9", "v4.1.10", "v4.2.0", "v4.2.1", "v4.2.2", "v4.2.3", "v4.2.4", "v4.2.5", "v4.2.6", "v4.2.7", "v5.0.0", "v5.0.1", "v5.0.2", "v5.0.3", "v5.0.4", "v5.0.5"],
    "branchVersions": ["highstock-v1.3.10", "v2.3.5", "v3.0.10", "v4.2.7", "v5.0.0"]
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/highcharts/update.json",
  "versions": ["v5.0.5"],
  "updateRemote": true,
  "version": "v5.0.5",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/highcharts/5.0.5",
  "branch": "highcharts/v5.0.5"
}
```

### CODE REVIEW

**Comment by megawac** [comment]
@MartinKolarik fyi: libgrabber is parsing these versions incorrectly. `highmaps-v1.1.10` should probably be considered `0.0.0-highmaps-v1.1.10` right now its considered graeter than 5.0.5

**Comment by MartinKolarik** [comment]
@megawac Actually, based on the output above, it seems to be sorted correctly?

**Comment by megawac** [comment]
Looking at https://github.com/jsdelivrbot/jsdelivr/tree/cb050e6e66a7f21c53eb9d18236eaae606fcd319/files/highcharts I would expect it to compare `5.0.4` to `5.0.5`

**Comment by MartinKolarik** [comment]
Are you talking about the file structure comparison?

**Comment by megawac** [comment]
oh wait a second I'm dumb sorry to bother you. That's a bot issue not libgrabber :p

**Comment by MartinKolarik** [comment]
>That's a bot issue not libgrabber :p

Yep :smile:

**Pull request closed without merging**
