### PR TITLE
xenixstudio html design guide

### PR DESCRIPTION
**Pull request by rinno83**
xenixstudio html design guide js, css files

### CODE REVIEW

**Comment by rinno83** [comment]
everything ok?

**Comment by jimaek** [comment]
What changed from here https://github.com/jsdelivr/jsdelivr/pull/3917 ?

**Comment by rinno83** [comment]
info.ini -> github, homepage 
file naming

**Comment by jimaek** [comment]
Thats not the problem. Please read what megawac said

**Comment by rinno83** [comment]
document modify.
please recheck.

**Comment by rinno83** [comment]
I'm waiting

when merge my project?

**Comment by jimaek** [comment]
Its not, megawac explained the reason here https://github.com/jsdelivr/jsdelivr/pull/3917

**Pull request closed without merging**
