### PR TITLE
Compressed Jquery 1.10.2

### PR DESCRIPTION
**Pull request by sms200207**
min.js was not compressed.
So I re-compressed it

### CODE REVIEW

**Comment by sms200207** [comment]
@jimaek @megawac 
It has file structure problem.
I think it's because it's old version of jquery.

**Comment by sms200207** [comment]
But I think it can merged.

**Comment by sms200207** [comment]
@jimaek @megawac @jsdelivrbot

**Comment by jimaek** [comment]
We dont allow the modification of old files so I cant merge this PR. Sorry

**Pull request closed without merging**
