### PR TITLE
Update project magneticmediajs to v1.3.5

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project magneticmediajs to v1.3.5.

@arnaudleyder

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "magneticmediajs",
    "repo": "arnaudleyder/magneticmediajs",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/magneticmediajs",
    "localVersions": ["1.3.1", "1.3.2", "1.3.3", "1.3.4"],
    "remoteVersions": ["1.0.2", "1.0.3", "1.1.0", "1.1.1", "1.1.2", "v1.3.0", "v1.3.1", "v1.3.2", "v1.3.3", "v1.3.4", "v1.3.5"],
    "branchVersions": ["v1.3.3", "v1.3.4"]
  },
  "version": "v1.3.5",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/magneticmediajs/1.3.5",
  "branch": "magneticmediajs/v1.3.5"
}
```

### CODE REVIEW

**Comment by arnaudleyder** [comment]
Hi, 

I need to change the file structure to be consistent with my bower releases and other industry standard. I am aware that it is not recommended to change file structure but I really would like this to happen as the project owner and I will provide a note on the documentation.

I am not sure how to change the info.ini file vs. this pull request. Let me know how to proceed.

Sorry for this change request I will try to be  more farsighted in the future.
	
Thanks
Arnaud

**Comment by megawac** [comment]
@arnaudleyder thats fine, but could you do the file change as part of a minor release instead of a patch. It's reasonably common for people to request

```
//cdn.jsdelivr.net/jquery/1.11/jquery.js
```

**Comment by arnaudleyder** [comment]
Pushed 1.4.0 in #3273 
Can we still push 1.3.5 with the old file structure to not break continuity?
Thanks

**Comment by megawac** [comment]
Definitely, feel free to submit a follow up pr - just don't want to break links to your project for people following a relatively common practice

**Pull request closed without merging**
