### PR TITLE
Add thymol.js "JavaScript emulation of Thymeleaf, the popular java templating system"

### PR DESCRIPTION
**Pull request by jjbenson**
First attempt!

### CODE REVIEW

**Comment by pnommensen** [comment]
@jjbenson Looks good overall. Can you squash your commits?

**Comment by jjbenson** [comment]
@pnommensen thanks for helping. Is this rebase ok? (First attempt at this too!)

**Comment by jimaek** [comment]
Sorry but no. Currently this PR has 8 commits, it should have only 1.

Thanks

**Comment by jjbenson** [comment]
Thanks for your patience guys. Is this ok?

**Comment by jimaek** [comment]
Looks good, thank you

**Pull request merged**
