### PR TITLE
add redux-toastr

### PR DESCRIPTION
**Pull request by diegoddox**
add redux-toastr: https://github.com/diegoddox/redux-toastr

### CODE REVIEW

**Comment by jimaek** [comment]
The fonts needs to be inside the version folder.
Also your auto-update doesnt include the fonts which will break the project
Plus you dont need to add the files themselves. The bot will add them automatically if you configure correctly update.json

**Comment by diegoddox** [comment]
Thanks @jimaek I will fix that.

**Comment by diegoddox** [comment]
@jimaek what about the folder version, do I need to create them or the bot will do that?

**Comment by jimaek** [comment]
The bot will do that. You only to add 2 config files and nothing else.

**Comment by diegoddox** [comment]
@jimaek thanks very much.

**Pull request closed without merging**
