### PR TITLE
Update project metadata.js to v0.9.201

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project metadata.js to v0.9.201.

@oknosoft

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "metadata.js",
    "repo": "oknosoft/metadata.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/metadata",
    "localVersions": ["0.9.199", "0.9.200"],
    "remoteVersions": ["v0.9.194", "v0.9.195", "v0.9.196", "v0.9.197", "v0.9.198", "v0.9.199", "v0.9.200", "v0.9.201"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/metadata/update.json",
  "versions": ["v0.9.201"],
  "version": "v0.9.201",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/metadata/0.9.201",
  "branch": "metadata.js/v0.9.201"
}
```

### CODE REVIEW

**Comment by unpete** [comment]
> Where is the metadata's mainfile (metadata.min.js) in v-0.9.201

metadata's mainfile file is located in the v-0.9.201 in dist/metadata.min.js which corresponds to the rule in update.json ("files": {"basePath": "dist/", "include": ["\*\*/*"] }}

> Is dhtmlx.min.js (0.9.201) properly minimized?

yes, file dhtmlx.min.js is properly minimized

> .cur (on imgs/custom_web/pan_black.cur) seems odd to want to host?

file imgs/custom_web/pan_black.cur used in metadata.css

**Comment by jimaek** [comment]
1. Do we need all those new files in production?
2. There are 2 files missing

**Comment by unpete** [comment]
> Do we need all those new files in production?

Unfortunately, drawing interface in the current edition, used a lot of png files. Quickly convert to fonticon can not, but such task is in the plans. Although a lot of files, their total size of 300Kb. 
This should not cause problems.

> There are 2 files missing

Missing one file metadata.js. I decided to leave in production only compressed metadata.min.js. The fact that the jsdelivrbot does not find the file dist/metadata.min.js, probably a bug

**Comment by unpete** [comment]
> Do we need all those new files in production?

Unfortunately, drawing interface in the current edition, used a lot of png files. Quickly convert to fonticon can not, but such task is in the plans. Although a lot of files, their total size of 300Kb. 
This should not cause problems.

> There are 2 files missing

Missing one, but not two files. I decided to leave in production only compressed metadata.min.js and remove uncompressed metadata.js. The fact that the jsdelivrbot does not find the file dist/metadata.min.js, probably a bug

**Comment by jimaek** [comment]
I am sorry but I cant merge such a big change between minor versions.
Missing files are acceptable only between major version changes. Even if its only the unminified file

**Pull request closed without merging**
