### PR TITLE
Added inrdeals js file

### PR DESCRIPTION
**Pull request by akash2411**
Added a new JS file which converts all users website links into their affiliate links automatically.

### CODE REVIEW

**Comment by akash2411** [comment]
Can you tell me why my pull request is not merged.
Any reasons?

**Comment by jimaek** [comment]
I have explained this many times. We no longer accept pull requests. Read the documentation about how it works.

**Comment by akash2411** [comment]
screenshot from 2017-07-23 14-41-06

This is on your website and I did the same.

**Comment by jimaek** [comment]
This is outdated. Here are the docs https://github.com/jsdelivr/jsdelivr#note-our-backend-changed-learn-how-to-use-the-new-jsdelivr

**Comment by akash2411** [comment]
Please Update it on your website also.

Thanks

**Pull request closed without merging**
