### PR TITLE
Update project flag-icon-css to 0.7.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project flag-icon-css to 0.7.1.

@lipis

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "flag-icon-css",
    "repo": "lipis/flag-icon-css",
    "files": {
      "include": ["./css/**/*", "./flags/**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/flag-icon-css",
    "localVersions": ["0.6.0"],
    "remoteVersions": ["0.1.0", "0.2.0", "0.3.0", "0.4.0", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.3", "0.6.4", "0.6.5", "0.7.0", "0.7.1"],
    "branchVersions": []
  },
  "version": "0.7.1",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/flag-icon-css/0.7.1",
  "branch": "flag-icon-css/0.7.1"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@megawac This doesnt look correct. These files exist https://github.com/lipis/flag-icon-css/blob/0.7.1/flags/4x3/zw.svg
Can we fix it?

**Comment by megawac** [comment]
Theres a chance the bot exceeded it's ratelimit

**Comment by jimaek** [comment]
I see, well the PR looks good me. Do you agree its good to merge?

(I forgot how hard it is without the bot)

**Comment by megawac** [comment]
Yeah it looks good some of the files it suggests are missing are there https://github.com/jsdelivrbot/jsdelivr/blob/flag-icon-css/0.7.1/files/flag-icon-css/0.7.1/flags/4x3/sx.svg.

Related to the issue with the API trucating files

**Pull request merged**
