### PR TITLE
Create info.ini

### PR DESCRIPTION
**Pull request by developermj**
Adding jquery.validation.unobtrustive from Microsoft

### CODE REVIEW

**Comment by jimaek** [comment]
info.ini is not enough, you have to create update.json as well if you want the bot to auto-update the project

**Comment by developermj** [comment]
Added an update.json

**Comment by pnommensen** [comment]
@developermj Could you remove the non-min file? It's not necessary for production (CDN) use.

**Comment by developermj** [comment]
Removed non min file. Ready to review pull request.

**Comment by developermj** [comment]
@pnommensen @jimaek Ready to review pull request again. Thanks.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge please

**Comment by jimaek** [comment]
@dejanstojanovic Thanks

**Pull request closed without merging**
