### PR TITLE
Added cookieBAR

### PR DESCRIPTION
**Pull request by ToX82**

### CODE REVIEW

**Comment by jimaek** [comment]
You are completely missing the `info.ini` file. Please check the README

**Comment by ToX82** [comment]
My bad, it should be there now

**Comment by jimaek** [comment]
If you are going to add almost every single file in that directly then instead of include use exclude to exclude LICENSE, README and the others.
It will also fix an error in your include parameter

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
