### PR TITLE
Fastclick version update 1.0.4 to 1.0.6

### PR DESCRIPTION
**Pull request by madssj**
Added FastClick versions from 1.0.4 to 1.0.6 with their own `.min.js` file, which is ~2.5 KiB smaller, than the previously provided.

### CODE REVIEW

**Comment by madssj** [comment]
Uhm, well, I didn't touch that version, but fair enough, I'll take one for the team.

**Comment by jimaek** [comment]
Why all the versions and not just the latest one?

**Comment by madssj** [comment]
@jimaek for completeness. Someone might really need `1.0.5` and it'd be a shame to disappoint them.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
Thank you

**Pull request closed without merging**
