### PR TITLE
Update project leaflet.esri to v2.0.0-beta.8

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project leaflet.esri to v2.0.0-beta.8.

@esri

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "leaflet.esri",
    "repo": "esri/esri-leaflet",
    "files": {
      "basePath": "dist/",
      "exclude": ["README.md"],
      "include": ["**/*"]
    },
    "path": "/home/libgrabber/jsdelivr/files/leaflet.esri",
    "localVersions": ["1.0.0-rc.7", "1.0.0-rc.8", "1.0.0", "1.0.1", "1.0.2", "1.0.3", "2.0.0-beta.4", "2.0.0-beta.5", "2.0.0-beta.6", "2.0.0-beta.7"],
    "remoteVersions": ["v0.0.1-beta.1", "v0.0.1-beta.2", "v0.0.1-beta.3", "v0.0.1-beta.4", "v0.0.1-beta.4-patch-1", "v0.0.1-beta.5", "v0.0.1-beta.6", "v0.0.1-rc1", "v0.0.1-rc.2", "v1.0.0-rc.1", "v1.0.0-rc.2", "v1.0.0-rc.3", "v1.0.0-rc.4", "v1.0.0-rc.5", "v1.0.0-rc.6", "v1.0.0-rc.7", "v1.0.0-rc.8", "v1.0.0", "v1.0.1", "v1.0.2", "v1.0.3", "v2.0.0-beta.1", "v2.0.0-beta.2", "v2.0.0-beta.3", "v2.0.0-beta.4", "v2.0.0-beta.5", "v2.0.0-beta.6", "v2.0.0-beta.7", "v2.0.0-beta.8"],
    "branchVersions": ["v2.0.0-beta.3"]
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/leaflet.esri/update.json",
  "versions": ["v2.0.0-beta.8"],
  "updateRemote": true,
  "version": "v2.0.0-beta.8",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/leaflet.esri/2.0.0-beta.8",
  "branch": "leaflet.esri/v2.0.0-beta.8"
}
```

### CODE REVIEW

**Comment by jgravois** [comment]
hi there @jimaek.  we've changed the naming structure of our plugin slightly.  now `esri-leaflet.js` is the minified code w/ sourcemap and [`esri-leaflet-debug.js`](https://github.com/Esri/esri-leaflet/tree/v2.0.0-beta.8/dist) contains whitespace and an inline sourcemap.

what should i be submitting to ensure that the bot can merge releases automatically going forward?
do i need to modify the `update.json` to exclude the new file?

```
"exclude": ["README.md", "esri-leaflet-debug.js"]
```

**Comment by jimaek** [comment]
Hey, yes that is correct.

**Comment by patrickarlt** [comment]
@jimaek I would like the debug file to be available from CDN too could you merge this anyway so the files can update?

**Comment by jimaek** [comment]
Ok. Do you want me to merge the beta or wait for the stable ones?

**Comment by patrickarlt** [comment]
Please merge the beta. Thanks!

**Pull request closed without merging**
