### PR TITLE
Update project jQuery-QueryBuilder to 1.4.2

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project jQuery-QueryBuilder to 1.4.2.

@mistic100

### Metadata information

```json
{
  "metadata": {
    "packageManager": "bower",
    "name": "jQuery-QueryBuilder",
    "repo": "mistic100/jQuery-QueryBuilder",
    "files": {
      "basePath": "dist/",
      "include": ["./js/*.min.*", "./css/*.min.*", "./i18n/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/jquery.query-builder",
    "localVersions": ["2.3.0", "2.3.1"],
    "remoteVersions": ["1.0.0", "1.1.0", "1.2.0", "1.2.1", "1.3.0", "1.4.0", "1.4.1", "1.4.2", "2.0.0", "2.0.1", "2.1.0", "2.2.0", "2.2.1", "2.3.0", "2.3.1"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/jquery.query-builder/update.json",
  "versions": ["1.4.2"],
  "updateRemote": true,
  "version": "1.4.2",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/jquery.query-builder/1.4.2",
  "branch": "jQuery-QueryBuilder/1.4.2"
}
```

### CODE REVIEW

**Comment by mistic100** [comment]
@jimaek Why the bot suddenly grabbed an old version ?

**Comment by jimaek** [comment]
Lots of people requested to keep updated older branches, so we added this feature.

**Comment by mistic100** [comment]
But it failed somehow...
there are only language files https://github.com/jsdelivr/jsdelivr/tree/master/files/jquery.query-builder/1.4.2/

**Comment by jimaek** [comment]
Yes, because the current update.json works only for the 2.x versions.
We can add the other files too if you want

**Comment by mistic100** [comment]
I people want older versions of the lib the yes, other files are necessary.

Should I make a PR to update update.json ? In any case the mainFile in info.ini will be incorrect.

**Comment by jimaek** [comment]
Dont update update.json, just add the missing files to this version directory. The bot wont upload any other old versions

**Comment by mistic100** [comment]
ok, any tip to do that without cloning the whole repo ? (even with --depth 1 it's rather huge)

**Comment by jimaek** [comment]
You can use the web interface if you want. it will be much faster

**Comment by mistic100** [comment]
That mean 6 commits right ? But I remember you have the awesome "squash & merge" from the bot

**Comment by jimaek** [comment]
Yup, 6 commits are not a problem

**Pull request merged**
