### PR TITLE
Update project zhihu-card to 0.0.4

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project zhihu-card to 0.0.4.

@laike9m

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "zhihu-card",
    "repo": "laike9m/zhihu-card",
    "files": {
      "basePath": "jsdelivr/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/zhihu-card",
    "localVersions": ["0.0.3"],
    "remoteVersions": ["0.0.1", "0.0.2", "0.0.3", "0.0.4"],
    "branchVersions": ["0.0.2"]
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/zhihu-card/update.json",
  "versions": ["0.0.4"],
  "updateRemote": true,
  "version": "0.0.4",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/zhihu-card/0.0.4",
  "branch": "zhihu-card/0.0.4"
}
```

### CODE REVIEW

**Comment by laike9m** [comment]
@jimaek
> .html (on theme/github.html) seems odd to want to host
It's frustrating to see validation fail due to non-existent issue. Is this "HTML check" has to be an error instead of a warning?

**Comment by laike9m** [comment]
Seems like it's going to fail every time I update version in the future 😭

**Comment by laike9m** [comment]
@megawac

**Comment by megawac** [comment]
I'm thinking about removing that if it comes up in past files

**Pull request merged**
