### PR TITLE
Added joola.sdk v0.8.6

### PR DESCRIPTION
**Pull request by orweinberger**

### CODE REVIEW

**Comment by jimaek** [comment]
Thank you

**Comment by orweinberger** [comment]
@jimaek Thanks for the merge. How does the build process for jsdelivr.com work? How soon should I expect to see this live in the CDN?

**Comment by jimaek** [comment]
The deploy is instant but the website might take a while to get updated http://www.jsdelivr.com/#!joola.sdk

**Comment by orweinberger** [comment]
Perfect, thanks again!

**Comment by jimaek** [comment]
You can also enable auto-updates if you want https://github.com/jsdelivr/jsdelivr#auto-updating

**Pull request merged**
