### PR TITLE
updated Hack font to v2.013

### PR DESCRIPTION
**Pull request by chrissimpkins**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
These file name changes were intentional and consistent with bug fixes that were introduced in this new release.  Please advise.

**Comment by chrissimpkins** [comment]
The change in file paths between versions is intentional and a part of the bug fix release.  Please advise.  Thanks.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
@chrissimpkins thank you

**Comment by chrissimpkins** [comment]
Thank you!

**Pull request closed without merging**
