### PR TITLE
Update project instantsearch.js to 0.11.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project instantsearch.js to 0.11.0.

@algolia

### Metadata information

```json
{
  "metadata": {
    "packageManager": "npm",
    "name": "instantsearch.js",
    "repo": "algolia/instantsearch.js",
    "files": {
      "basePath": "dist/",
      "exclude": ["debug.css"],
      "include": ["**/*"]
    },
    "path": "/home/jsdelivr/files/instantsearch.js",
    "localVersions": ["0.2.2", "0.3.0", "0.4.0", "0.4.1", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.4", "0.6.5", "0.7.0", "0.8.0", "0.8.1", "0.8.2", "0.9.0", "0.10.0"],
    "remoteVersions": ["0.1.0", "0.2.2", "0.3.0", "0.4.0", "0.4.1", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.3", "0.6.4", "0.6.5", "0.7.0", "0.8.0", "0.8.1", "0.8.2", "0.9.0", "0.10.0", "0.11.0"],
    "branchVersions": ["0.8.0"]
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/instantsearch.js/update.json",
  "version": "0.11.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/instantsearch.js/0.11.0",
  "branch": "instantsearch.js/0.11.0"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@vvo default.min.css is empty https://raw.githubusercontent.com/jsdelivrbot/jsdelivr/instantsearch.js/0.11.0/files/instantsearch.js/0.11.0/themes/default.min.css
Is that normal?

**Comment by vvo** [comment]
No indeed, I will submit another release because this one was not good.

**Comment by vvo** [comment]
Can I just close this?

**Comment by jimaek** [comment]
Close after tagging a new release otherwise the bot will submit the same one

**Pull request merged**
