### PR TITLE
Add jquery.layout 1.4.3

### PR DESCRIPTION
**Pull request by tylerlong**
Source code was copied from https://github.com/allpro/layout/tree/master/source/stable

### CODE REVIEW

**Comment by tylerlong** [comment]
Source code was copied from https://github.com/allpro/layout/tree/master/source/stable

I think it is the right content to add.  Is there any body to help me to review and confirm?

Thank you!

**Comment by jimaek** [comment]
Please remove all the new unminified files

**Comment by tylerlong** [comment]
@jimaek

I made the following change:

1. if a file has a minified version, delete unminified version
1. if a file doesn't have a minified version, keep it as it is

I think the current output is the mininal set of files possible.

By the way, I don't think the previous versions can pass jsdelivrbot's checking.

**Comment by jimaek** [comment]
Looks good, just bring `jquery.layout.js` back, it was in the old version. We need it for consistency.
Thank you

**Comment by tylerlong** [comment]
@jimaek 

In version `1.3.0rc30.79`  it is jquery.layout**-latest**.js   https://github.com/jsdelivr/jsdelivr/tree/master/files/jquery.layout/1.3.0rc30.79
Do you think it is a mistake in that version? Do we need to be consistent with that version?

**Comment by jimaek** [comment]
dont add the latest files. It should be fine

**Comment by tylerlong** [comment]
@jimaek  done

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
