### PR TITLE
added bootstrap-sortable

### PR DESCRIPTION
**Pull request by drvic10k**
plugin for sorting HTML tables
https://github.com/drvic10k/bootstrap-sortable

### CODE REVIEW

**Comment by pnommensen** [comment]
@drvic10k: possible to minify the CSS? Then, please squash your commits too.

**Comment by drvic10k** [comment]
@pnommensen minified and squashed

**Comment by pnommensen** [comment]
sorry, one more thing. since it's a bootstrap thing then make it bootstrap.sortable to follow the structure defined in readme.

**Comment by drvic10k** [comment]
I was thinking about this, but I already have nuget and bower packages with the same name, so I wanted to keep the naming

**Pull request merged**
