### PR TITLE
First PR

### PR DESCRIPTION
**Pull request by ecoslado**

### CODE REVIEW

**Comment by tomByrer** [comment]
I believe you had it correct at ` "include": ["dist/doofinder.min.js"]`.  Also the bot will handle uploading files, so `0.0.1` folder is not needed & in fact is confusing.  When accepted, the bot will [find current version is 0.11.0](https://github.com/doofinder/js-doofinder/releases), so just that will be uploaded for you.

If you *really need* older versions, those should be added later in a separate PR IMHO.  But since you're still in beta/alpha, I don't think is needed.

**Comment by ecoslado** [comment]
OK, I've just done these changes. Everything ok? Thanks.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by tomByrer** [comment]
That's a sweet trick!

**Comment by ecoslado** [comment]
Hi, you merged our project but it seem's to be empty in the cdn. I tried to access it and there's no file. Could you help me? Thanks so much.

**Comment by tomByrer** [comment]
Sorry @ecoslado!  Strange, it is [in the GH repo](https://github.com/jsdelivr/jsdelivr/blob/master/files/doofinder/0.11.0/doofinder.min.js).
@jimaek ?

**Comment by jimaek** [comment]
There was a problem with the deployment. I opened a support ticket to ask why it failed.
In the meantime the file is online. Sorry about that

**Pull request closed without merging**
