### PR TITLE
Create update.json

### PR DESCRIPTION
**Pull request by tivie**

### CODE REVIEW

**Comment by pnommensen** [comment]
@tivie Hey, non min files won't be necessary for production (CDN) use. Could you remove them?

**Comment by tivie** [comment]
sure

**Comment by jimaek** [comment]
commit int this one

**Comment by tivie** [comment]
Done. Shall I also add info.ini to this branch?

**Comment by jimaek** [comment]
I missed that you are updating the wrong directory. Please add the file to http://www.jsdelivr.com/#!showdown

**Comment by hubdotcom** [comment]
Added, please close PR https://github.com/jsdelivr/jsdelivr/blob/master/files/showdown/update.json

**Comment by tivie** [comment]
thank you

**Pull request closed without merging**
