### PR TITLE
i have added php melody template files

### PR DESCRIPTION
**Pull request by topvd**

### CODE REVIEW

**Comment by pnommensen** [comment]
Hello, please remove the non minified files as they are not necessary for production. Then, you can squash your commits. Thanks.

**Comment by topvd** [comment]
is this ok know ?

**Comment by pnommensen** [comment]
No, please squash your commits. https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by megawac** [comment]
@jsdelivrbot squash and merge

Thanks @topvd

**Pull request closed without merging**
