### PR TITLE
Rate-it - jquery 5 stars ranking system

### PR DESCRIPTION
**Pull request by Arg0n4th**
Rate-it - jquery 5 stars ranking system

### CODE REVIEW

**Comment by jimaek** [comment]
What is the source of these files? The official repo has a different structure

**Comment by Arg0n4th** [comment]
mmh , they moved. When I took these files there was a github project active.

Now the actual version is different. I think these file may be useful for backward compatibility. If you think they violate the requirements I will delete them.

**Comment by jimaek** [comment]
Where did you download these files?

**Comment by Arg0n4th** [comment]
I don'r remember sincerely, but I guess on rate-it github repo when it was active.

**Comment by jimaek** [comment]
The latest files are located over here http://rateit.codeplex.com/
So if you want you can use them instead. Or you can close the PR.

**Comment by jimaek** [comment]
Again the formatting in that repo is different. There are no css/ js/ folders plus there are images included in the css. So either we host everything or we host only js

**Pull request closed without merging**
