### PR TITLE
Add JavaScript cryptographic library 'jsrsasign'

### PR DESCRIPTION
**Pull request by evorios**
Not sure of the correct this settings:
```"basePath": "lib/"```

### CODE REVIEW

**Comment by evorios** [comment]
It looks like something went wrong.

**Comment by jimaek** [comment]
That 1 file is enough for production and works in the browser?

**Comment by evorios** [comment]
@jimaek , yes, I install this module at node-server for testing, and folder contains this file "jsrsasign.js".

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
