### PR TITLE
Update project mark.js to 6.3.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project mark.js to 6.3.0.

@julmot

### Metadata information

```json
{
  "metadata": {
    "packageManager": "bower",
    "name": "mark.js",
    "repo": "julmot/mark.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/mark.js",
    "localVersions": ["1.0.0", "2.0.0", "2.0.1", "2.1.0", "2.1.1", "2.2.0", "2.2.1", "2.2.2", "2.3.0", "2.3.1", "2.3.2", "2.3.3", "2.4.0", "3.0.0", "3.1.0", "3.1.1", "3.1.2", "3.1.3", "4.0.0", "4.0.1", "4.0.2", "5.0.0", "5.1.0", "5.2.0", "5.2.1", "5.2.2", "5.2.3", "6.0.0", "6.0.1", "6.1.0", "6.2.0"],
    "remoteVersions": ["1.0.0", "2.0.0", "2.0.1", "2.1.0", "2.1.1", "2.2.0", "2.2.1", "2.2.2", "2.3.0", "2.3.1", "2.3.2", "2.3.3", "2.4.0", "3.0.0", "3.1.0", "3.1.1", "3.1.2", "3.1.3", "4.0.0", "4.0.1", "4.0.2", "5.0.0", "5.1.0", "5.2.0", "5.2.1", "5.2.2", "5.2.3", "6.0.0", "6.0.1", "6.1.0", "6.2.0", "6.3.0"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/mark.js/update.json",
  "versions": ["6.3.0"],
  "updateRemote": true,
  "version": "6.3.0",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/mark.js/6.3.0",
  "branch": "mark.js/6.3.0"
}
```

### CODE REVIEW

**Comment by julmot** [comment]
@jimaek Isn't it possible to stop those errors? They seem to occure on every release...

**Comment by jimaek** [comment]
@megawac Any ideas?

**Comment by julmot** [comment]
@jimaek Well, in my opinion the updater should only check things that are related to that specific release, in this case 6.3.0.

Also, when adding a new project only the last releases of each major version are included. Therefore it makes no sense to check for all previous version on new releases.

**Comment by megawac** [comment]
Need to add support for https://github.com/jsdelivr/bot/issues/10

**Pull request merged**
