### PR TITLE
Create backbone-metal

### PR DESCRIPTION
**Pull request by megawac**
Created via https://github.com/megawac/cdn-it

### CODE REVIEW

**Comment by jimaek** [comment]
whats wrong with the bot?

**Comment by megawac** [comment]
Looks like it got an error page from the github api

**Comment by jimaek** [comment]
Ok, then the same question as here https://github.com/jsdelivr/jsdelivr/pull/6034

**Comment by jimaek** [comment]
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md
>If the project is a plugin of a library, prepend the name of the library, like jquery.blurjs or bootstrap.select.

So it would be `backbone.metal`

**Pull request closed without merging**
