### PR TITLE
Patch 2 - AnyPicker

### PR DESCRIPTION
**Pull request by nehakadam**
Created info.ini and update.json files inside newly created anypicker folder.

### CODE REVIEW

**Comment by jimaek** [comment]
Same issues as your other PR

**Comment by nehakadam** [comment]
Modified PR according to your suggestions.

**Comment by jimaek** [comment]
It looks good. Now please rename the directory to `jquery.anypicker` and its ready to go

**Comment by nehakadam** [comment]
Done

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by nehakadam** [comment]
Thanks!

**Pull request closed without merging**
