### PR TITLE
Update project scrollreveal.js to v3.0.0

### PR DESCRIPTION
**Pull request by jlmakes**
Everything looks nice and tidy for the new release. I also removed an ancient version of ScrollReveal that hasn’t been supported for over a year.

### CODE REVIEW

**Comment by jlmakes** [comment]
:+1:

**Comment by jimaek** [comment]
I am sorry but we dont allow the removal of existing files, if someone was using it it would break their site.

**Comment by jimaek** [comment]
Actually I just merged https://github.com/jsdelivr/jsdelivr/pull/8495 since everything was ok. 
Future updates should just work just fine as well

**Comment by jlmakes** [comment]
Thanks @jimaek, but the problem is that file case has changed, and the `mainfile` entry is now incorrect. It reads `scrollReveal.js` but should be `scrollreveal.js`. Also the library description was updated, and disregarded.

I understand not wanting to break people's sites, but now there's a 404 on the jsdeliver site...

**Comment by jimaek** [comment]
It should be fixed now, sorry about that

**Comment by jlmakes** [comment]
@jimaek cheers!

**Pull request closed without merging**
