### PR TITLE
places.js update

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
@jimaek I am unsure if I call jsdelirv bot squash and merge it will work?

**Comment by jimaek** [comment]
It should. I believe it worked the previous time you did it, right?

**Comment by vvo** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
But you already have added that project here https://github.com/jsdelivr/jsdelivr/tree/master/files/places

**Comment by vvo** [comment]
Argh sorry I messed up.. I need places.js not places. How can I fix that? Remove places project?

**Comment by jimaek** [comment]
Since you added it very recently if you haven't advertised that URL anywhere then yes, remove it.

**Pull request closed without merging**
