### PR TITLE
Update project bootswatch to v3.3.5+2

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project bootswatch to v3.3.5+2.

@thomaspark

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "bootswatch",
    "repo": "thomaspark/bootswatch",
    "files": {
      "include": ["./*/bootstrap.css", "./*/bootstrap.min.css"],
      "exclude": ["*(2|api|assets|bower_components|custom|default|fonts|global|help|tests|.gitignore|.travis.yml|CNAME|Gemfile|Gruntfile.js|LICENSE|README.md|_config.yml|bower.json|composer.json|favicon.ico|index.html|package.json)"]
    },
    "path": "/home/jsdelivr/files/bootswatch",
    "localVersions": ["3.0.0", "3.0.3-b", "3.1.0", "3.1.1", "3.3.2"],
    "remoteVersions": ["v2.0.0", "v2.0.1", "v2.0.2", "v2.0.3", "v2.0.4", "v2.1.0", "v2.1.1", "v2.1.1+1", "v2.2.2", "v2.2.2+1", "v2.2.2+2", "v2.3.0", "v2.3.0+1", "v2.3.0+2", "v2.3.1", "v2.3.1+1", "v2.3.2", "v3.0.0-rc1", "v3.0.0-rc2", "v3.0.0", "v3.0.1", "v3.0.2+1", "v3.0.2+2", "v3.0.2", "v3.0.3+1", "v3.0.3", "v3.1.0", "v3.1.0+1", "v3.1.1", "v3.1.1+1", "v3.2.0+3", "v3.2.0+1", "v3.2.0+2", "v3.2.0+4", "v3.2.0", "v3.3.0", "v3.3.1", "v3.3.1+1", "v3.3.1+2", "v3.3.1+3", "v3.3.2", "v3.3.4", "v3.3.4+1", "v3.3.5+1", "v3.3.5", "v3.3.5+2"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/bootswatch/update.json",
  "version": "v3.3.5+2",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/bootswatch/3.3.5",
  "branch": "bootswatch/v3.3.5+2"
}
```

### CODE REVIEW

**Comment by markcarver** [comment]
> No mainfile property provided

@jimaek, is this a hard requirement? I can't tell from existing [documentation](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md#file-structure). It's also not very applicable here. If we _have_ to put something, is `"mainfile": "cerulean/bootstrap.css"` applicable?

**Comment by jimaek** [comment]
Its a hard requirement for most projects but in this case we can ignore it. 
Its also set in the info.ini file not in update.json

**Comment by markcarver** [comment]
Yes, currently it's just set to `mainfile=""`, yet the bot still gave a warning. Should it be set to something else so we don't have to worry about it again?

**Comment by jimaek** [comment]
Dont worry about it

**Pull request closed without merging**
