### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by jimaek** [comment]
No [tags](https://github.com/JavaScriptPostalService/jsps-client/releases) and no documentation

**Comment by wski** [comment]
fixed

**Comment by jimaek** [comment]
I cant install your package using npm
```
 npm install jsps-client
npm WARN package.json cborjs-typedarray-decoder@0.1.1 No repository field.
npm http GET https://registry.npmjs.org/jsps-client
npm http 404 https://registry.npmjs.org/jsps-client
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)

```

**Comment by wski** [comment]
Right we haven't made a module yet that is compatible with npm. If it is
required that we have it on npm to use jsdelivr I can go ahead and add
something

**Comment by wski** [comment]
I went ahead and published the module to npm

**Pull request closed without merging**
