### PR TITLE
Fixed typed.js

### PR DESCRIPTION
**Pull request by fatbattk**
v1.1 format.

### CODE REVIEW

**Comment by jimaek** [comment]
Why no more min files?

**Comment by fatbattk** [comment]
There never was a min file below 1.1 release. Min file was added to `master` later but no new release yet.

**Comment by jimaek** [comment]
Can we get the author to include it? Because for production we need the min file

**Comment by megawac** [comment]
It looks like its fine as is; feel free to comment otherwise
https://github.com/mattboldt/typed.js/tree/master/dist

**Pull request closed without merging**
