### PR TITLE
Update project dush to v1.1.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project dush to v1.1.0.

@tunnckoCore

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "dush",
    "repo": "tunnckoCore/dush",
    "files": {
      "include": ["dist/dush.min.js", "dist/dush.standalone.min.js"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/dush",
    "localVersions": ["1.0.0"],
    "remoteVersions": ["v0.1.0", "v1.0.0", "v1.1.0"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/dush/update.json",
  "version": "v1.1.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/dush/1.1.0",
  "branch": "dush/v1.1.0"
}
```

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@jimaek can we remove `v1.1.0` somehow? i unpublished it from npm.
Or should remove the tag from github? that would be bad.

**Comment by jimaek** [comment]
There is no way to do that on your side. I can do it manually but I prefer not to to make sure no websites will break in case someone is using this version

**Comment by tunnckoCore** [comment]
@jimaek no one using it and it cant be used cuz it is with old dist from `1.0.0`. I just released it and after 1min realize that i forgot to run `npm run build` to build the new `dist`

**Comment by jimaek** [comment]
Ok then, send a PR to remove that version from the repo

**Pull request merged**
