### PR TITLE
Spider's Web Skin

### PR DESCRIPTION
**Pull request by sms200207**
Spider's Web is markquery's tistory skin.
MIT License.

### CODE REVIEW

**Comment by sms200207** [comment]
@megawac
@jimaek

**Comment by megawac** [comment]
Any reason you're using your fork instead of pointing to the parent repository. Also a lot of those files (e.g. jquery, ie.min) are hosted on the cdn already. Your `mainfile` probably should be `app.js`

**Comment by sms200207** [comment]
OK. Thanks I'll Fix It!

**Comment by sms200207** [comment]
I thinks author changed some libraries, so I'll still include them. ( I removed few things more. )

**Comment by sms200207** [comment]
@megawac
@jimaek
Now I thinks it is ok.

**Comment by megawac** [comment]
@jsdelivrbot squash & merge

**Comment by sms200207** [comment]
Thanks!

**Pull request closed without merging**
