### PR TITLE
Add Photo-Sphere-Viewer

### PR DESCRIPTION
**Pull request by mistic100**
http://mistic100.github.io/Photo-Sphere-Viewer (page is broken waiting for dns.js.org approval)

### CODE REVIEW

**Comment by mistic100** [comment]
@jimaek I don't understand the check error :s

**Comment by jimaek** [comment]
1. Why are you using a fork and not the original repo?
2. Why are you trying to add `./`? It makes no sense in this case

**Comment by mistic100** [comment]
1. My fork diverged from the original project in many ways, the author didn't want to publish to Bower, I do.
2. I take my other repo as reference and your comment https://github.com/jsdelivr/jsdelivr/pull/6433#discussion_r37149962, re-reading the doc `*.min.*` should be enough

**Comment by jimaek** [comment]
I recommend renaming the folder to something like `mistic100-photo-sphere-viewer` to make it clear that its not the original project.

**Comment by mistic100** [comment]
I disagree for two reason :
1. it's against your rules of choosing a simple name
2. considering the amount of work I put in this it's more my work that his, it's just the same base idea. I would a have created a bare new repository you won't have noticed.

Beside that's what the point of making it "clear" ? People (me first) usually don't care who created what, they just want simple to use and appending the same of someone in front of the package is not simple.

**Comment by jimaek** [comment]
1. What do you mean?
2. The amount of work doesnt matter. You decided to use the exact same name as an other popular project, plus you used it as the base. If you want name your project differently.
What happens when the original author decides to add his project to jsDelivr as well?

By "clear" I mean people that use the original project will look for it on jsDelivr and will expect it to be the exact same thing and not a different fork under the exact same name.

**Comment by mistic100** [comment]
Considering the name on Bower does not contain "mistic100" as well as the domain name on js.org it will be as confusing.

Now as none of us wants to change it's mind I close this request. Thank you anyway.

**Pull request closed without merging**
