### PR TITLE
Update project scrollReveal to v3.0.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project scrollReveal to v3.0.1.

@jlmakes

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "scrollReveal",
    "repo": "jlmakes/scrollReveal.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/scrollreveal.js",
    "localVersions": ["0.1.2", "2.3.2", "3.0.0"],
    "remoteVersions": ["v2.0.0", "v2.0.1", "v2.0.2", "v2.0.3", "v2.0.4", "v2.0.5", "v2.1.0", "v2.2.0", "v2.3.0", "v2.3.1", "v2.3.2", "v3.0.0", "v3.0.1"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/scrollreveal.js/update.json",
  "version": "v3.0.1",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/scrollreveal.js/3.0.1",
  "branch": "scrollReveal/v3.0.1"
}
```

### CODE REVIEW

**Comment by jlmakes** [comment]
Hey @jimaek 

I made some important updates in v3.0.1, but it looks like jsDelivr is still misconfigured. Can you help out again on this one, and fix the error so that this can be automated in the future? I think it's the capitalization of the file...

**Comment by jimaek** [comment]
Its not a bug. That file is indeed new https://github.com/jsdelivr/jsdelivr/tree/master/files/scrollreveal.js/3.0.0
The bot is correct. If I merge this PR this notification wont popup again and future updates should auto-merge.

Should I merge it? Do you want the unminified file on the CDN?

**Comment by jlmakes** [comment]
Hey @jimaek, thanks for your help I really appreciate it.

I’m not sure I see a reason to host the unminified file, what's your opinion? I was thinking you might be able to help change the meta data to something like:
```diff
{
  "metadata": {
    "packageManager": "github",
    "name": "scrollReveal",
-   "repo": "jlmakes/scrollReveal.js",
+   "repo": "jlmakes/scrollreveal.js",
    "files": {
      "basePath": "dist/",
-     "include": ["**/*"],
+     "include": ["scrollreveal.min.js"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/scrollreveal.js",
    "localVersions": ["0.1.2", "2.3.2", "3.0.0"],
    "remoteVersions": ["v2.0.0", "v2.0.1", "v2.0.2", "v2.0.3", "v2.0.4", "v2.0.5", "v2.1.0", "v2.2.0", "v2.3.0", "v2.3.1", "v2.3.2", "v3.0.0", "v3.0.1"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/scrollreveal.js/update.json",
  "version": "v3.0.1",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/scrollreveal.js/3.0.1",
  "branch": "scrollReveal/v3.0.1"
}
```

**Comment by jlmakes** [comment]
Rapid fire! bumped to v3.0.2... https://github.com/jsdelivr/jsdelivr/pull/8612

**Comment by jimaek** [comment]
I merged 3.0.2. I think we can keep the unmin for debug purposes.

**Pull request closed without merging**
