### PR TITLE
Lytebox JS library content viewer

### PR DESCRIPTION
**Pull request by Fede72**
Lytebox is a lightweight, cross-browser compatible and mobile friendly
Javascript library and content viewer

Restore original file structure

### CODE REVIEW

**Comment by Fede72** [comment]
The files are correct, I restored original file structure

**Comment by jimaek** [comment]
Update info.ini with the new structure as well. (you dont need to close it and create a new one. Just commit the change and squash your commits)

**Comment by Fede72** [comment]
I think I've done. I hope right :)

**Comment by jimaek** [comment]
Thank you

**Pull request merged**
