### PR TITLE
add redux-thunk

### PR DESCRIPTION
**Pull request by arronmabrey**
add redux-thunk

### CODE REVIEW

**Comment by arronmabrey** [comment]
@jimaek Thanks for merging my other two redux PRs. It would be super helpful for me, if you could merge this sometime today, if that's an inconvenience no worries, I can manage, but it would be awesome! :-) 

Thanks so much for your hard work! 

-- Arron

**Comment by jimaek** [comment]
:+1:

**Comment by arronmabrey** [comment]
@jimaek Sweet! Thanks!

**Comment by arronmabrey** [comment]
@jimaek about how long does it take to propagate to the CDN after a merge?

**Comment by jimaek** [comment]
It should be instant if there are no issues. Its live now http://www.jsdelivr.com/projects/redux.thunk

**Comment by arronmabrey** [comment]
:+1:

**Pull request merged**
