### PR TITLE
Update project algoliasearch to 3.0.5

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project algoliasearch to 3.0.5.

@algolia

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "algoliasearch",
    "repo": "algolia/algoliasearch-client-js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/algoliasearch",
    "localVersions": ["2.4.4", "2.4.6", "2.4.7", "2.5.1", "2.5.2", "2.5.3", "2.6.0", "2.6.1", "2.6.2", "2.6.3", "2.6.4", "2.6.5", "2.6.6", "2.7.0", "2.7.1", "2.7.2", "2.7.3", "2.7.4", "2.7.5", "2.8.0", "2.8.1", "2.8.2", "2.8.3", "2.8.4", "2.8.5", "2.8.6", "2.9.0", "2.9.1", "2.9.2", "2.9.3", "2.9.4", "3.0.0", "3.0.1", "3.0.2", "3.0.3"],
    "remoteVersions": ["2.0.0", "2.0.1", "2.1.0", "2.2.0", "2.3.0", "2.3.1", "2.3.2", "2.3.3", "2.3.4", "2.3.6", "2.3.7", "2.3.8", "2.4.0", "2.4.1", "2.4.3", "2.4.4", "2.4.6", "2.4.7", "2.5.0", "2.5.1", "2.5.2", "2.5.3", "2.6.0", "2.6.1", "2.6.2", "2.6.3", "2.6.4", "2.6.5", "2.6.6", "2.7.0", "2.7.1", "2.7.2", "2.7.3", "2.7.4", "2.7.5", "2.8.0", "2.8.1", "2.8.2", "2.8.3", "2.8.4", "2.8.5", "2.8.6", "2.9.0", "2.9.1", "2.9.2", "2.9.3", "2.9.4", "2.9.5", "3.0.0", "3.0.1", "3.0.2", "3.0.3", "3.0.4", "3.0.5"],
    "branchVersions": ["3.0.3", "3.0.4"]
  },
  "version": "3.0.5",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/algoliasearch/3.0.5",
  "branch": "algoliasearch/3.0.5"
}
```

### CODE REVIEW

**Comment by vvo** [comment]
@tomByrer Why does the bot thinks our minified file is not optimal? We are using closure compiler.

**Comment by vvo** [comment]
Also, I pushed a tag https://github.com/algolia/algoliasearch-client-js/tree/2.9.5 and hoped it would also be pulled.

Basically, I want to publish 3.0.5 and 2.9.5 to jsDelivr. We have v2 and v3 and both need to be updated.

Can this be done?

**Comment by jimaek** [comment]
No, the point of the bot was to upload the latest available version. v2 would have to be uploaded manually.

Im also going to make sure that the bot will auto-merge your PR in the future, right now it thinks it didnt get minified correctly.

**Comment by vvo** [comment]
Awesome, so how do I update/submit V2 manually? LIke this: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md#advanced?

**Comment by jimaek** [comment]
Yes, unfortunately thats the only way. But your PR wont be auto-merged, is that ok or its extremely important to have instant merge?

Btw here is the fix for the minification bug https://github.com/jsdelivr/bot/pull/37

**Comment by vvo** [comment]
> But your PR wont be auto-merged, is that ok or its extremely important to have instant merge?

In this particular case it will be ok if it takes a couple hours?

So how does jQuery 1.x 2.x handles it? Do they also update manually the V1? Only curious here.

**Comment by jimaek** [comment]
Yes, we manually update upload older versions.
Given that Algolia uses jsDelivr exclusively and pushes the most traffic I could make one of you guys a mod with privileges to merge PRs (after learning all the rules of course). How does that sound?

**Comment by vvo** [comment]
Sounds awesome. Also we are now recommending to use jsDelivr because you have the /2/ /3/ feature on your cdn. That's really a great thing for us.

Add me, I will follow your rules.

**Comment by jimaek** [comment]
Done. When uploading your files please dont push to master. Create a PR and let the bot check for any errors you might have missed. Once everything is ok or the warnings can be ignored you can merge.
Follow the README and CONTRIBUTING rules and ping me if you have any questions.

**Comment by vvo** [comment]
Thanks a lot, will do it today and double check (will get inspiration from jQuery v1)

**Pull request merged**
