### PR TITLE
create info.ini for my project: ureka_theme

### PR DESCRIPTION
**Pull request by propertunist**
this is a theme for my own website ureka.org - based on the open source PHP project 'elgg'. elgg plugins will be added soon.

### CODE REVIEW

**Comment by jimaek** [comment]
Sorry but it doesnt meet the requirements

**Comment by propertunist** [comment]
@jimaek i did look around to see if any requirements were not met, but am not sure what specifically you are referring to. can you clarify what is not being met here? thanks

**Comment by jimaek** [comment]
Not really an open source project. No documentation. No tagged versions. Too fresh and not production ready.

**Comment by propertunist** [comment]
i see. i do have open source plugins for the elgg network which would fit into that description, but i thought my own website's theme would be ok too after reading the descriptions here: http://www.jsdelivr.com/free-open-source-cdn/javascript-cdn
where can i read a more precise and detailed description of what the requirements are for hosting on the jsdelivr network?
thanks

**Comment by jimaek** [comment]
I dont think we publish the requirements anywhere, its up to each mod to decide if a projects can be hosted on jsDelivr

**Pull request closed without merging**
