### PR TITLE
Add jquery.filterjitsu plugin to jsdelivr files

### PR DESCRIPTION
**Pull request by marcusmolchany**
This PR adds `info.ini` and `update.json` for jquery.filterjitsu

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
@marcusmolchany good to go… let me know when it's there!

**Comment by megawac** [comment]
Looks good, you guys just need to tag a release on the filterjitsu repo for this to work

**Comment by marcusmolchany** [comment]
ah, will do thanks!

**Comment by marcusmolchany** [comment]
@megawac just tagged release [`v1.0.0`](https://github.com/Fullscreen/filterjitsu/releases/tag/v1.0.0). Thanks!

**Comment by marcusmolchany** [comment]
hey, haven't seen our file pop up on the cdn yet. does it take a minute to propagate?

**Pull request merged**
