### PR TITLE
add: koala-html library stable 1.0.0 minified

### PR DESCRIPTION
**Pull request by DiegoYungh**
Adding my last repo HTML entities builder helper to CDN
This way I can provide jsbin|jsfiddle|codepen examples by providing the CDN

### CODE REVIEW

**Comment by jimaek** [comment]
Please squash your commits into 1

**Comment by DiegoYungh** [comment]
Done :+1:

**Comment by jimaek** [comment]
thank you

**Comment by DiegoYungh** [comment]
Thanks, this can be closed now ;)

**Pull request merged**
