### PR TITLE
roundSlider - unminified sources are added

### PR DESCRIPTION
**Pull request by soundar24**
roundSlider - unminified sources are added under the version 1.0

### CODE REVIEW

**Comment by soundar24** [comment]
updated the info.ini file

**Comment by soundar24** [comment]
Need to add the roundslider.js and roundslider.css files in the CDN.

**Comment by megawac** [comment]
@jsdelivrbot squash

**Comment by soundar24** [comment]
What problem with this ? Can you please let me know the details. How can i add my unminified file ?

**Comment by jimaek** [comment]
Your project is already hosted http://www.jsdelivr.com/#!jquery.roundslider
And it doesnt need the unminified files

**Comment by soundar24** [comment]
@jimaek Thanks for your response. But most of the controls having both minified and non-minified sources in the CDN. For example consider,

http://www.jsdelivr.com/#!jquery.basic-slider
http://cdn.jsdelivr.net/jquery.basic-slider/1.3/jquery.bjqs.js
http://cdn.jsdelivr.net/jquery.basic-slider/1.3/jquery.bjqs.min.js

http://www.jsdelivr.com/#!bxslider
http://cdn.jsdelivr.net/bxslider/4.2.5/jquery.bxslider.js
http://cdn.jsdelivr.net/bxslider/4.2.5/jquery.bxslider.min.js

Like this me also tried to update both the files in the CDN. This is useful for the remote debugging.

**Comment by jimaek** [comment]
The unminified files in other projects are mostly because of legacy reasons. We try to host only minified files now. There is no benefit to them. For debugging its best to load the file locally or directly from Github

**Pull request closed without merging**
