### PR TITLE
EXT-2121 - 2016 Volume 3 and Volume 2 SP-2 release changes merged.

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**
Hi Team,

We have moved our latest version CSS and Script files. Please move this to jsDelivr master. 

Thanks

### CODE REVIEW

**Comment by Syncfusion-JavaScript** [comment]
HI Team,

Can you please update us the the root cause of this failure ?

**Comment by megawac** [comment]
Looks good, just github API bug this time

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac ,

Thanks for the quick response. What are the items we need to follow in our repository for auto-publish from your bot ?

**Comment by megawac** [comment]
https://github.com/jsdelivr/jsdelivr#auto-updating

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac ,

Thank again for the guidance.  As per the steps from user guide documentation we have modified our update.json file from our repository. Find the pull request below,

https://github.com/jsdelivr/jsdelivr/pull/14217

Kindly check this from your end and update us if we done anything wrong.

**Pull request merged**
