### PR TITLE
Add SPDY note

### PR DESCRIPTION
**Pull request by megawac**

### CODE REVIEW

**Comment by jimaek** [comment]
SPDY and HTTP2 are different things. Our CDNs only support SPDY based on Nginx's spdy module

**Comment by megawac** [comment]
Ah drat - I'll amend that

**Comment by pnommensen** [comment]
the performance with SPDY for single/few static file delivery is questionable.

**Comment by jimaek** [comment]
Yes, but we want to make sure people know we support SPDY so that if they use SPDY on their website jsDelivr wont be the slow player.

**Pull request merged**
