### PR TITLE
Bootstrap Modallery

### PR DESCRIPTION
**Pull request by lhcgoncalves**

### CODE REVIEW

**Comment by lhcgoncalves** [comment]
All conflicts has been solved

**Comment by lhcgoncalves** [comment]
Finished :)

**Comment by lhcgoncalves** [comment]
Tjis is my first plugin, so help me if a made a mistake :)

**Comment by lhcgoncalves** [comment]
Any news?

**Comment by megawac** [comment]
looks good, thanks

**Pull request merged**
