### PR TITLE
don't export sfx bundles

### PR DESCRIPTION
**Pull request by rosendi**

### CODE REVIEW

**Comment by jimaek** [comment]
Why? We already host these files so this change would require a major version change to make sure we dont break any sites.

**Comment by rosendi** [comment]
Well, the SFX-bundles are redundant and I won't provide them once 0.2.0 is landed. Having of the UMD-bundles is enough, since the library is used in the Angular 2 ecosystem and the recommended loader is SystemJS. The public api can be changed without a major version bumping until the 1.0.0 release.

**Comment by jimaek** [comment]
If the next update will be 0.2.x then sure. But if you plan to release some 0.1.x versions then I cant merge this yet

**Comment by rosendi** [comment]
Ah, OK! I thought that I have to update `update.json` before the upcoming release.

**Comment by rosendi** [comment]
Yes, the next update is 0.2.0.

**Comment by rosendi** [comment]
@jimaek thank you!

**Pull request merged**
