### PR TITLE
Update project clappr to 0.2.14

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project clappr to 0.2.14.

@clappr

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "clappr",
    "repo": "clappr/clappr",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/clappr",
    "localVersions": ["0.0.57", "0.0.58", "0.0.59", "0.0.60", "0.0.61", "0.0.63", "0.0.65", "0.0.66", "0.0.68", "0.0.69", "0.0.70", "0.0.71", "0.0.73", "0.0.74", "0.0.75", "0.0.76", "0.0.77", "0.0.78", "0.0.79", "0.0.80", "0.0.81", "0.0.82", "0.0.83", "0.0.84", "0.0.85", "0.0.86", "0.0.87", "0.0.88", "0.0.89", "0.0.91", "0.0.105", "0.0.107", "0.0.108", "0.0.109", "0.0.110", "0.0.111", "0.0.112", "0.0.113", "0.0.114", "0.0.115", "0.1.0", "0.1.1", "0.1.2", "0.1.3", "0.1.4", "0.1.5", "0.1.6", "0.1.7", "0.1.8", "0.1.9", "0.1.10", "0.1.11", "0.1.12", "0.1.13", "0.2.1", "0.2.2", "0.2.3", "0.2.4", "0.2.5", "0.2.6", "0.2.7", "0.2.8", "0.2.9", "0.2.10", "0.2.11", "0.2.12", "0.2.13"],
    "remoteVersions": ["0.0.47", "0.0.48", "0.0.49", "0.0.50", "0.0.51", "0.0.52", "0.0.53", "0.0.54", "0.0.55", "0.0.56", "0.0.57", "0.0.58", "0.0.59", "0.0.60", "0.0.61", "0.0.62", "0.0.63", "0.0.64", "0.0.65", "0.0.66", "0.0.67", "0.0.68", "0.0.69", "0.0.70", "0.0.71", "0.0.72", "0.0.73", "0.0.74", "0.0.75", "0.0.76", "0.0.77", "0.0.78", "0.0.79", "0.0.80", "0.0.81", "0.0.82", "0.0.83", "0.0.84", "0.0.85", "0.0.86", "0.0.87", "0.0.88", "0.0.89", "0.0.90", "0.0.91", "0.0.92", "0.0.93", "0.0.94", "0.0.95", "0.0.96", "0.0.97", "0.0.98", "0.0.99", "0.0.100", "0.0.101", "0.0.102", "0.0.103", "0.0.104", "0.0.105", "0.0.106", "0.0.107", "0.0.108", "0.0.109", "0.0.110", "0.0.111", "0.0.112", "0.0.113", "0.0.114", "0.0.115", "0.1.0", "0.1.1", "0.1.2", "0.1.3", "0.1.4", "0.1.5", "0.1.6", "0.1.7", "0.1.8", "0.1.9", "0.1.10", "0.1.11", "0.1.12", "0.1.13", "0.2.0", "0.2.1", "0.2.2", "0.2.3", "0.2.4", "0.2.5", "0.2.6", "0.2.7", "0.2.8", "0.2.9", "0.2.10", "0.2.11", "0.2.12", "0.2.13", "0.2.14"],
    "branchVersions": ["0.2.4", "0.2.12"]
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/clappr/update.json",
  "version": "0.2.14",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/clappr/0.2.14",
  "branch": "clappr/0.2.14"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@leandromoreira Hey, is this correct?

**Comment by leandromoreira** [comment]
@jimaek we had a little problem while releasing the newer version of clappr, so this is wrong ;( . We'll fix it soon, I'm sorry.

**Comment by jimaek** [comment]
Ok, thank you

**Comment by leandromoreira** [comment]
@jimaek  we're live! (once again, I'm sorry)

**Comment by jimaek** [comment]
no probs :)

**Pull request closed without merging**
