### PR TITLE
Update project qoopido.js to 3.7.4

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project qoopido.js to 3.7.4.

@dlueth

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "qoopido.js",
    "repo": "dlueth/qoopido.js",
    "files": {
      "basePath": "dist/latest/min",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/qoopido.js",
    "localVersions": ["3.5.2", "3.5.3", "3.5.4", "3.5.5", "3.5.6", "3.5.7", "3.5.8", "3.5.9", "3.6.0", "3.6.1", "3.6.2", "3.6.3", "3.6.4", "3.6.5", "3.6.6", "3.6.7", "3.6.8", "3.6.9", "3.7.0", "3.7.1", "3.7.2", "3.7.3"],
    "remoteVersions": ["support", "1.1.7", "1.1.8", "1.1.9", "2.0.0", "2.0.1", "2.0.2", "2.0.3", "2.0.4", "2.0.5", "2.0.6", "2.0.7", "2.0.8", "2.0.9", "2.0.10", "2.1.0", "2.1.1", "2.1.2", "2.1.3", "2.1.4", "2.1.5", "2.1.6", "2.1.7", "2.1.8", "3.0.0", "3.0.1", "3.0.2", "3.0.3", "3.0.4", "3.0.5", "3.0.6", "3.0.7", "3.0.8", "3.0.9", "3.1.0", "3.1.1", "3.1.2", "3.1.3", "3.1.4", "3.1.5", "3.1.6", "3.1.7", "3.1.8", "3.1.9", "3.2.0", "3.2.1", "3.2.2", "3.2.3", "3.2.4", "3.2.5", "3.2.6", "3.2.7", "3.2.8", "3.2.9", "3.3.0", "3.3.1", "3.3.2", "3.3.3", "3.3.4", "3.3.5", "3.3.6", "3.3.7", "3.3.8", "3.3.9", "3.4.0", "3.4.1", "3.4.2", "3.4.3", "3.4.4", "3.4.5", "3.4.6", "3.4.7", "3.4.8", "3.4.9", "3.5.0", "3.5.1", "3.5.2", "3.5.3", "3.5.4", "3.5.5", "3.5.6", "3.5.7", "3.5.8", "3.5.9", "3.6.0", "3.6.1", "3.6.2", "3.6.3", "3.6.4", "3.6.5", "3.6.6", "3.6.7", "3.6.8", "3.6.9", "3.7.0", "3.7.1", "3.7.2", "3.7.3", "3.7.4"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/qoopido.js/update.json",
  "version": "3.7.4",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/qoopido.js/3.7.4",
  "branch": "qoopido.js/3.7.4"
}
```

### CODE REVIEW

**Comment by dlueth** [comment]
Sorry for the recurring inconvenience - added some more things to the lib and had to adjust some filenames...

**Comment by jimaek** [comment]
People dont link directly to these changed files?

**Comment by dlueth** [comment]
They should in the future, but not yet I would say

**Comment by jimaek** [comment]
If you are 100% sure that no websites will break then I can merge. But in the future breaking changes like that should equal to a major version change 3x->4.x

**Comment by dlueth** [comment]
Yeah, sorry for that - I just added these files in one of the latest versions :) Will promise to keep changes like this for major releases in the future!

**Pull request merged**
