### PR TITLE
Monkberry

### PR DESCRIPTION
**Pull request by elfet**
### Monkberry — JavaScript DOM Template Engine
Monkberry compile template to JavaScript code for creating nodes with DOM API and helper methods for updating content of these nodes.

https://github.com/monkberry/monkberry

### CODE REVIEW

**Comment by elfet** [comment]
Please, approve!

**Comment by jimaek** [comment]
Whats the difference between this and the standalone?

**Comment by elfet** [comment]
This is just runtime library, it's can be used with compiled code by monkberry cli. monkberry-standalone contains runtime and compiler.

**Comment by jimaek** [comment]
So which one is supposed to work in the browser?

**Comment by elfet** [comment]
Both. But for this users need to precompile their templates.

**Comment by elfet** [comment]
Cool, thanks!

**Pull request merged**
