### PR TITLE
Adding Library Breakpoints v 1.0

### PR DESCRIPTION
**Pull request by abishekrsrikaanth**
Trigger jQuery events for your responsive design breakpoints!

Repo: https://github.com/xoxco/breakpoints
URL: http://xoxco.com/projects/code/breakpoints/

### CODE REVIEW

**Comment by jimaek** [comment]
There are not version tags https://github.com/xoxco/breakpoints/releases
The bot wont work

**Comment by jimaek** [comment]
Looks good, can you rename the directory to `jquery.breakpoints`?

**Comment by abishekrsrikaanth** [comment]
Renamed the directory as requested

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
