### PR TITLE
Update info for CodeMirror

### PR DESCRIPTION
**Pull request by anshumanf**
Website and Github owner/URL have changed

### CODE REVIEW

**Comment by jimaek** [comment]
Please dont create multiple PRs for each file. 1 PR should contain everything https://github.com/jsdelivr/jsdelivr/pull/5930

**Comment by anshumanf** [comment]
Merged the changes from the other PR and made fixes to maintain folder structure.

**Comment by jimaek** [comment]
It wont work because the repo doesnt contain `codemirror.min.js`

**Comment by anshumanf** [comment]
Should I manually upload the files for the new version instead? I can create a minimised ``codemirror.min.js``.

**Comment by jimaek** [comment]
Yes, thats the only option. The bot cant auto-update the project unless they add the min file

**Pull request closed without merging**
