### PR TITLE
Add inferno

### PR DESCRIPTION
**Pull request by jdalton**
This PR adds [inferno](https://infernojs.org/), the extremely fast React-like JavaScript library for building modern user interfaces.

### CODE REVIEW

**Comment by jdalton** [comment]
\cc @trueadm to sanity check.

**Comment by megawac** [comment]
gracias

**Comment by jdalton** [comment]
Ah, I think there's a bit of a bug:

It says the main file is this, which points to a 404
https://cdn.jsdelivr.net/inferno/1.1.1/packages/inferno/dist/inferno.min.js

**Comment by jdalton** [comment]
The "mainfile" entry needs to be changed to the based-path of:
```txt
mainfile = "inferno.min.js"
```

**Comment by megawac** [comment]
Ah thanks, will fix

**Pull request merged**
