### PR TITLE
Update project threejs to r71

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project threejs to r71.

@mrdoob

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "threejs",
    "repo": "mrdoob/three.js",
    "files": {
      "basePath": "build/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/threejs",
    "localVersions": ["0.0.0-r9", "0.0.0-r56", "0.0.0-r58", "0.0.0-r61", "0.0.0-r62", "0.0.0-r67", "0.0.0-r69", "0.0.0-r70"],
    "remoteVersions": ["r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15", "r16", "r17", "r18", "r25", "r28", "r29", "r30", "r31", "r32", "r33", "r34", "r35", "r36", "r37", "r38", "r39", "r40", "r42", "r43", "r44", "r45", "r46", "r47", "r48", "r49", "r50", "r51", "r52", "r53", "r54", "r55", "r56", "r57", "r58", "r59", "r60", "r61", "r62", "r63", "r64", "r65", "r66", "r67", "r68", "r69", "r70", "r71"],
    "branchVersions": []
  },
  "version": "r71",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/threejs/0.0.0-r71",
  "branch": "threejs/r71"
}
```

### CODE REVIEW

**Comment by hubdotcom** [comment]
I think this should be a priority as one of the top repo's on github https://github.com/search?o=desc&q=javascript&ref=searchresults&s=stars&type=Repositories&utf8=%E2%9C%93

**Comment by megawac** [comment]
@hubdotcom what do you mean? Do you mean for auto-merging?

`libgrabber` in charge of creating these pull requests respects patch releases and the version style `threejs` and almost every other lib uses through https://github.com/megawac/SemVish but its a bit more complicated for auto merging cause that bot can't use this package

**Comment by hubdotcom** [comment]
Ah, Is the problem is occurring with issues https://github.com/jsdelivr/jsdelivr/pull/3867#issuecomment-81358355 rather than the version numbers?

**Comment by megawac** [comment]
Yeah,the validator just doesn't properly handle patch releases

**Pull request merged**
