### PR TITLE
Adding Cutback Library

### PR DESCRIPTION
**Pull request by jlaran**
Create info.ini
Create update.json

### CODE REVIEW

**Comment by jlaran** [comment]
Hi @megawac could you help me with this one? Thanks!

**Comment by megawac** [comment]
Looks good or do you want to include both authors full names?

**Comment by megawac** [comment]
Hey @jlaran the structure of your repo is currently incorrect. You should use `git tag` to label a version as 2.0 instead of having a 2.0 folder. The bot will currently not work the way your project is set up

**Comment by jlaran** [comment]
Thank you! I prefer to include both full names, is there any way to add a git tag by the git hub interface?

**Comment by megawac** [comment]
https://github.com/blog/1547-release-your-software

**Comment by megawac** [comment]
Did you push your tags https://github.com/jlaran/cutback-js/releases

**Comment by jlaran** [comment]
ops! Already pushed! Sorry I am new here on Github

**Comment by jlaran** [comment]
Now is ok?

**Comment by rupomcool** [comment]
ok

**Comment by jlaran** [comment]
Hi @megawac, is something missing on this one?

**Pull request closed without merging**
