### PR TITLE
Add StackBlur

### PR DESCRIPTION
**Pull request by as-com**

### CODE REVIEW

**Comment by jimaek** [comment]
1. Remove the unminified file
2. Your file doesnt match the official one https://raw.githubusercontent.com/flozz/StackBlur/1.2.0/dist/stackblur.min.js

**Comment by as-com** [comment]
About canvg bundling StackBlur - I realized their version is different from the one from the official source. I suppose we should still keep it there?

**Comment by jimaek** [comment]
You didnt remove the unminified file.

**Comment by as-com** [comment]
File deleted

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
