### PR TITLE
Added Moblify

### PR DESCRIPTION
**Pull request by CosmicWebServices**
http://cosmicsearch.org/Moblify

### CODE REVIEW

**Comment by megawac** [comment]
Ping @CosmicWebServices can you rename the folder `files/moblify` also the files should exist under `files/moblify/{version}` instead of `files/mobilify`

**Comment by CosmicWebServices** [comment]
I will do that!

**Comment by CosmicWebServices** [comment]
Did it.

**Comment by megawac** [comment]
I think you misunderstood @CosmicWebServices - `mobilify` cannot be capitalized in the folder name

**Pull request closed without merging**
