### PR TITLE
feat(new lib): add docsearch.js

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by jimaek** [comment]
you need the update.json file as well

**Comment by vvo** [comment]
Yep added

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by vvo** [comment]
I do not remember if there's some more delay than the usual libgrabber 30min for a lib to show up?

**Comment by jimaek** [comment]
Its live now https://github.com/jsdelivr/jsdelivr/pull/8516

**Comment by vvo** [comment]
awesome

**Pull request closed without merging**
