### PR TITLE
update update.json for trip.js

### PR DESCRIPTION
**Pull request by EragonJ**
as title.

### CODE REVIEW

**Comment by EragonJ** [comment]
I did uploaded a new version on my repo, but I just noticed that the path is wrong because I did change it in my latest version. I am not quite sure this new version will be updated or not, hmmm !?

**Comment by jimaek** [comment]
First of all I dont see it at all here https://github.com/EragonJ/Trip.js/releases

**Comment by EragonJ** [comment]
@jimaek what you mean ? For me, all versions are under `https://github.com/EragonJ/Trip.js/releases`.

**Comment by jimaek** [comment]
strange, when I checked there was no 3.0.0 on there

**Comment by EragonJ** [comment]
@jimaek thanks !! :) ありがとう

**Pull request merged**
