### PR TITLE
Update MediaElement Plugins info.ini

### PR DESCRIPTION
**Pull request by ron666**

### CODE REVIEW

**Comment by ron666** [comment]
Thanks!

**Comment by megawac** [comment]
my pleasure

**Comment by ron666** [comment]
Just for curiosity, how long does ti take to update your website? Just to confirm hat I see the changes

**Comment by megawac** [comment]
I think the API the site uses checks commits in this repo every 30 minutes

**Comment by ron666** [comment]
Perfect. Thanks

**Pull request merged**
