### PR TITLE
Add StreamSaver.js

### PR DESCRIPTION
**Pull request by lewisgoddard**
> StreamSaver writes stream to the filesystem directly asynchronous.
>  https://jimmywarting.github.io/StreamSaver.js/example.html

### CODE REVIEW

**Comment by lewisgoddard** [comment]
No minified version is available, so I hope this is okay.

**Comment by megawac** [comment]
Hey @lewisgoddard! This project as is isn't going to work as they aren't currently using `git tags` or github releases. You can see if they have a bower or npm repo or contact the author

**Comment by lewisgoddard** [comment]
`npm install file-saver` but I'm not sure how to implement this?

**Comment by megawac** [comment]
https://github.com/jsdelivr/libgrabber#add-updatejson-schema
See packageManager definition

**Comment by lewisgoddard** [comment]
Looks like they might start using those tonight.

**Comment by lewisgoddard** [comment]
@megawac They are now using releases.

**Pull request merged**
