### PR TITLE
added angular wizard version 0.5.1

### PR DESCRIPTION
**Pull request by jacobscarter**

### CODE REVIEW

**Comment by jacobscarter** [comment]
.less is there to match previous file structure

**Comment by jimaek** [comment]
You already added it https://github.com/jsdelivr/jsdelivr/pull/5102
Why are you adding it agian?

**Comment by jacobscarter** [comment]
This is a new version, 0.5.1, the less file is in the 0.5.1 folder because it is in all the other folders and your documentation says to mimic folder structure of previous versions

**Comment by jimaek** [comment]
You have 8 commits in this PR. Please clean them up

**Pull request closed without merging**
