### PR TITLE
Added typed.js

### PR DESCRIPTION
**Pull request by fatbattk**
Adding typed.js jquery plugin.

### CODE REVIEW

**Comment by fatbattk** [comment]
How long before the bot add the files? Still do not see it on site.

**Comment by jimaek** [comment]
```
info: Updating typed.js to v1.1
info: Copied 0 files name=typed.js, version=v1.1, files=[]
warn: Something might be wrong with update.json name=typed.js, version=v1.1
```

There is some error with your update.json. I will look into it a bit later when I come back home

**Comment by jimaek** [comment]
@fatbattk There is no `dist/` folder https://github.com/mattboldt/typed.js/tree/v1.1

**Comment by fatbattk** [comment]
Somehow missed this notification!
Turns out v1.1 release does not have that folder so I have updated to remedy it.
https://github.com/jsdelivr/jsdelivr/pull/4551

**Pull request merged**
