### PR TITLE
Add algoliasearch.helper library

### PR DESCRIPTION
**Pull request by bobylito**
Algoliasearch helper is the companion for the algoliasearch that brings
advanced search features and search state management. This is the
initial release as an independent module.

### CODE REVIEW

**Comment by pnommensen** [comment]
Hello, the non minified file is not necessary for production. Perhaps it's best to specify the .min.js file. Then, please squash your commits. Thanks

**Comment by vvo** [comment]
@pnommensen Hi, I cannot see the non-minified versions in @bobylito commits?

**Comment by jimaek** [comment]
I guess he removed them? Looks good, in the future please squash your commits into 1 :)

**Comment by vvo** [comment]
Thanks :)

**Comment by bobylito** [comment]
Sure! thanks @jimaek !

**Pull request merged**
