### PR TITLE
Update project phaser to v2.3.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project phaser to v2.3.0.

@photonstorm

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "phaser",
    "repo": "photonstorm/phaser",
    "files": {
      "basePath": "build/",
      "include": ["phaser.js", "phaser.min.js", "phaser.map"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/phaser",
    "localVersions": ["2.0.0", "2.0.3", "2.0.4", "2.0.5", "2.0.6", "2.0.7", "2.1.0", "2.1.1", "2.1.2", "2.1.3", "2.2.0", "2.2.1", "2.2.2"],
    "remoteVersions": ["0.9.1", "0.9.2", "0.9.3", "0.9.4", "0.9.5", "0.9.6", "0.9.7", "1.0", "1.0.1", "1.0.2", "1.0.3", "1.0.4", "1.0.5", "1.0.6", "1.1", "1.1.1", "1.1.2", "1.1.3", "1.1.4", "1.1.5", "1.1.6", "v2.0.0", "v2.0.1", "v2.0.2", "v2.0.3", "v2.0.4", "v2.0.5", "v2.0.6", "v2.0.7", "2.1.0", "v2.1.0", "v2.1.1", "v2.1.2", "v2.1.3", "v2.2.0", "v2.2.1", "v2.2.2", "v2.3.0"],
    "branchVersions": []
  },
  "version": "v2.3.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/phaser/2.3.0",
  "branch": "phaser/v2.3.0"
}
```

### CODE REVIEW

**Comment by photonstorm** [comment]
I don't understand why it thinks the file structure has changed? The same 3 files exist in 2.3.0 as they did in the previous version, in the same folder.

**Comment by jimaek** [comment]
@megawac Got time to check out this bug?

**Comment by photonstorm** [comment]
Thanks for the merge. Will be curious to know why it baulked out though!

**Comment by megawac** [comment]
not a bug https://github.com/jsdelivr/jsdelivr/tree/a593865fd76925c1b6b4aa4cfdf59567649275a9/files/phaser/2.2.2

**Comment by photonstorm** [comment]
https://github.com/jsdelivr/jsdelivr/pull/3383

**Pull request merged**
