### PR TITLE
Add projects using web interface

### PR DESCRIPTION
**Pull request by jimaek**
Added instructions regarding the easier web interface method to add projects

### CODE REVIEW

**Comment by megawac** [comment]
Looks good, still think it belongs in a contributing.md file

**Comment by jimaek** [comment]
Do you want me to remove all contributing related parts and just link the file in README?

**Comment by tomByrer** [comment]
Fine if adding a brand-new project.  Might want to mention prefixes for lib-dependant projects (`angular.thing`, `jquery.widget`).
If updating existing lib, need to have workaround for "Sorry, we had to truncate this directory to 1,000 files. 403 entries were omitted from the list. " error.

README is getting long, +1 `CONTRIBUTING.md`.

**Comment by jimaek** [comment]
How about this https://github.com/jsdelivr/jsdelivr/pull/4048 ?

**Pull request closed without merging**
