### PR TITLE
Inclusion of Zsocial

### PR DESCRIPTION
**Pull request by MaxMillion**

### CODE REVIEW

**Comment by jimaek** [comment]
You named the folder `zsocial` but the file is named `zocial.css`
Did you make a type somewhere?

**Comment by MaxMillion** [comment]
Yes. I forgot that the folder should include the ".css".  Should I redo it to reflect that?

**Comment by jimaek** [comment]
No, the problem is not the .css part. Its the `s`.
One says zsocial and the other zocial. Which one is correct?

**Comment by MaxMillion** [comment]
"Zocial"

**Comment by jimaek** [comment]
Then fix the folder name, it says zsocial

**Pull request closed without merging**
