### PR TITLE
Sync patch

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**
Update info.ini and update.json files

### CODE REVIEW

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
Can you Please merge this commits asap.

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
Can you Please Update this Changes in jsDeliver Website? its Possible to Update commits in Current Release Version ?
Can you please Update reason for committed changes not reflected in current Syncfusion-javascript Package  -jsDeliver website

**Comment by megawac** [comment]
Tag another release on your repo and the bot will pick it up

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
I have added new Tag in Git hub repository (https://github.com/syncfusion/JavaScript-Widgets/releases) -14.2.28 .but JsDeliver not yet Update. Can you Please tell step to automatic update jsDeliver repository?

**Pull request merged**
