### PR TITLE
Adding lodash 3.2.0

### PR DESCRIPTION
**Pull request by jtmueller**
Adding lodash 3.2.0

### CODE REVIEW

**Comment by jtmueller** [comment]
I do not understand the bot's objections at all. I'm just adding a missing version of an existing library. Why should "lodash.com" be expected to match "fronteers.nl" in the first place?

**Comment by jimaek** [comment]
Looks like a bug, pinging @megawac to check it out.

**Comment by megawac** [comment]
@jtmueller the `isMinimized` check isn't very clever, it literally just looks at line numbers. Maybe I should bold **Might be nothing** to make it clear that those checks are skeptical

**Comment by jimaek** [comment]
@megawac What about the website thing? Im curious where fronteers.nl comes from

**Comment by megawac** [comment]
Its something off about the certificate I suppose

**Comment by megawac** [comment]
Looks like a temporary bug on the issuers end, the certificate was fixed

**Pull request merged**
