### PR TITLE
bootstrap-material-datetimepicker

### PR DESCRIPTION
**Pull request by ricardopolo**

### CODE REVIEW

**Comment by ricardopolo** [comment]
Can you please explain me the bot error, I cannot understand it. Thanks :)

**Comment by megawac** [comment]
You're missing the `"files"` to included in the update.json

https://github.com/jsdelivr/libgrabber#add-updatejson-schema

**Comment by ricardopolo** [comment]
@megawac in the docs (https://github.com/jsdelivr/libgrabber#add-updatejson-schema) it says basePath, include and exclude, are optional. Thays why I dont put `files`. 
In this case the base path is the root, so, put just a `/`?

**Comment by megawac** [comment]
`files` is not optional. The properties inside files are though

**Comment by ricardopolo** [comment]
@megawac fixed :)

**Comment by megawac** [comment]
@jsdelivrbot squash and merge

**Comment by ricardopolo** [comment]
@megawac after a PR that has been approved how log it takes to appear in jsDelivr?

**Comment by megawac** [comment]
Bot checks for updates/new libraries every 30 minutes @ricardopolo

**Comment by ricardopolo** [comment]
@megawac after about one hour, it still does not appear (https://www.jsdelivr.com/?query=bootstrap%20material%20datetimepicker). Something maybe wrong or is just a matter of time?

**Comment by jimaek** [comment]
1. When installing using bower it asks for user input, I dont think the bot can handle it
```
Unable to find a suitable version for jquery, please choose one:
    1) jquery#1.11.0 which resolved to 1.11.0 and is required by bootstrap-material-datetimepicker#2.5.3
    2) jquery#~2.1.1 which resolved to 2.1.4 and is required by bootstrap-material-design#0.3.0
    3) jquery#1.9.1 - 2 which resolved to 2.1.4 and is required by bootstrap#3.3.6
    4) jquery#* which resolved to 2.1.4 and is required by jquery.serializeJSON#2.6.1

```
2. The `files` parameter is empty

**Pull request merged**
