### PR TITLE
Update project instantsearch.js to 0.11.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project instantsearch.js to 0.11.1.

@algolia

### Metadata information

```json
{
  "metadata": {
    "packageManager": "npm",
    "name": "instantsearch.js",
    "repo": "algolia/instantsearch.js",
    "files": {
      "basePath": "dist/",
      "exclude": ["debug.css"],
      "include": ["**/*"]
    },
    "path": "/home/jsdelivr/files/instantsearch.js",
    "localVersions": ["0.2.2", "0.3.0", "0.4.0", "0.4.1", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.4", "0.6.5", "0.7.0", "0.8.0", "0.8.1", "0.8.2", "0.9.0", "0.10.0"],
    "remoteVersions": ["0.1.0", "0.2.2", "0.3.0", "0.4.0", "0.4.1", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.3", "0.6.4", "0.6.5", "0.7.0", "0.8.0", "0.8.1", "0.8.2", "0.9.0", "0.10.0", "0.11.0", "0.11.1"],
    "branchVersions": ["0.8.0", "0.11.0"]
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/instantsearch.js/update.json",
  "version": "0.11.1",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/instantsearch.js/0.11.1",
  "branch": "instantsearch.js/0.11.1"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@vvo ping again. If you want send a manual PR with the correct files for the new version

**Comment by vvo** [comment]
Can I merge both of the versions? We are still in beta mode so yes we have moving files (additions/deletions) in the build but that's expected here.

Even in the future we might add new files from time to time (givent the new features), is that ok?

**Comment by jimaek** [comment]
Sure, do as you wish. Its your project, im just making sure there are no bugs/problems

**Comment by vvo** [comment]
> Sure, do as you wish. Its your project, im just making sure there are no bugs/problems

Okay as for me I do not want to do things that are bad for jsdelivr, but here its really about "beta" mode (still published in jsdelivr to test everything is good).

Thanks a lot for the rapid feedback :)

**Pull request merged**
