### PR TITLE
Add OpenLayers 3.8.2.

### PR DESCRIPTION
**Pull request by mstenta**

### CODE REVIEW

**Comment by megawac** [comment]
Thanks

**Comment by drupol** [comment]
@mstenta could you provide a update.json file so we can have the library auto updated ?
See: https://github.com/jsdelivr/jsdelivr/blob/master/README.md

**Comment by mstenta** [comment]
@drupol - I'm not sure that's possible with the ol3 Github, because the ./build folder doesn't exist in the repo. Only in the packaged released. Unless that's what jsDelivr is looking at... not sure...

**Comment by drupol** [comment]
Indeed, sorry for the mislead.

**Comment by jimaek** [comment]
We also support npm/bower if you release the compiled files there

**Comment by drupol** [comment]
Hi @jimaek, could you tell me more about that ?
Maybe @elemoine can help ?

**Comment by drupol** [comment]
CDNJS does it I think already : https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/ol3/package.json

**Comment by mstenta** [comment]
I think that file is the equivalent of info.ini in jsDelivr - it is for general library information - not for updating.

**Comment by drupol** [comment]
mh mmh, we need to find a way to get Openlayers automatically updated on cdnjs and jsDelivr.

**Comment by drupol** [comment]
Looks like ol3 is also available with npm, i'll check deeper tomorrow.

**Comment by drupol** [comment]
Weird, ol3 is no more available :(

http://api.jsdelivr.com/v1/jsdelivr/libraries/ol3

**Comment by mstenta** [comment]
Yes it is: http://cdn.jsdelivr.net/ol3/3.8.2/ol.js

Where did you get that URL from?

**Comment by mstenta** [comment]
Wait - your URL works too now.

**Comment by drupol** [comment]
Indeed, now it works... weird :(

**Comment by jimaek** [comment]
@drupol You can find more info here regarding the auto-updates https://github.com/jsdelivr/libgrabber
Our bot can download new versions and files from github/bower/npm

**Pull request merged**
