### PR TITLE
Update links for WhitestormJS

### PR DESCRIPTION
**Pull request by jackdalton**
We migrated to an organization rather than keeping it as one of @sasha240100's repositories.

### CODE REVIEW

**Comment by sasha240100** [comment]
@jackdalton Thank you

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge
Thank you

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge right now!

**Comment by jimaek** [comment]
Good bot

**Pull request closed without merging**
