### PR TITLE
Update project scrollReveal to v3.0.5

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project scrollReveal to v3.0.5.

@jlmakes

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "scrollReveal",
    "repo": "jlmakes/scrollReveal.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/scrollreveal.js",
    "localVersions": ["0.1.2", "2.3.2", "3.0.0", "3.0.2", "3.0.3", "3.0.4"],
    "remoteVersions": ["v2.0.0", "v2.0.1", "v2.0.2", "v2.0.3", "v2.0.4", "v2.0.5", "v2.1.0", "v2.2.0", "v2.3.0", "v2.3.1", "v2.3.2", "v3.0.0", "v3.0.1", "v3.0.2", "v3.0.3", "v3.0.4", "v3.0.5"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/scrollreveal.js/update.json",
  "version": "v3.0.5",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/scrollreveal.js/3.0.5",
  "branch": "scrollReveal/v3.0.5"
}
```

### CODE REVIEW

**Comment by jlmakes** [comment]
@jimaek Can I add the minified versions of the problematic versions just so I can stop bugging you with patches? :bow: 

Dealing with the `jsDelivr` repo was painfully slow on my machine—but would I just clone and upload the minified files to those directories?

**Comment by jimaek** [comment]
You can use the Github web interface to modify the repo. Its easy and fast.
And yes you can do that, it would be a great temp fix :)

**Comment by jlmakes** [comment]
@jimaek I changed the filename case, which is why it can't seem to find `scrollreveal.min.js` since legacy versions use `scrollReveal.min.js`

What do you suggest? Just upload a lower case minified alternative to silence the bot?

**Comment by jimaek** [comment]
Yes. Just make sure they work, because the files will appear on the site.

**Comment by jlmakes** [comment]
@jimaek Can deprecate/remove unsupported versions of the library? especially 0.1.x… that’s over years old!

**Comment by jimaek** [comment]
No, we never remove anything to be safe.

**Pull request merged**
