### PR TITLE
Add xterm.js

### PR DESCRIPTION
**Pull request by jagadeeshv16**
xtermjs is a popular browser terminal software.

### CODE REVIEW

**Comment by jagadeeshv16** [comment]
hi @megawac, i am unable to get ci test run on it, is there something i missed.

**Comment by megawac** [comment]
bot probs just crashed or the github api failed to push the notificationpr

**Comment by megawac** [comment]
Change update.info to update.json

**Comment by jagadeeshv16** [comment]
@megawac , completed the requested changes.

**Pull request merged**
