### PR TITLE
Update project kute.js to 0.9.5

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project kute.js to 0.9.5.

@thednp

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "kute.js",
    "repo": "thednp/kute.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/kute.js",
    "localVersions": ["0.9.0", "0.9.1", "0.9.2", "0.9.3", "0.9.4"],
    "remoteVersions": ["0.9.0", "0.9.1", "0.9.2", "0.9.3", "0.9.4", "0.9.5"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/kute.js/update.json",
  "version": "0.9.5",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/kute.js/0.9.5",
  "branch": "kute.js/0.9.5"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@thednp I am afraid this change could break websites for people that use those files. I would recommend changing the file structure only between major version changes

**Comment by thednp** [comment]
this should be a major update, but I feel no need to make it 1.0.0 yet.

**Comment by thednp** [comment]
this should be a major update, but I feel no need to make it 1.0.0 yet.

**Comment by jimaek** [comment]
Its up to you but I cant merge this PR right now. People trust us to not break their sites.

**Pull request merged**
