### PR TITLE
Fix mainfile for jsTree

### PR DESCRIPTION
**Pull request by as-com**

### CODE REVIEW

**Comment by jimaek** [comment]
You will also need to add a mainfile overide to pre1.0 where the old format is located. Example https://github.com/jsdelivr/jsdelivr/blob/master/files/sweetalert/0.1.2/mainfile

**Comment by as-com** [comment]
Alright, fixed that. The bot still complains though.

**Comment by jimaek** [comment]
Yeah the bot is not smart enough yet :)

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Pull request closed without merging**
