### PR TITLE
Update project video.js to 5.8.4

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project video.js to 5.8.4.

@videojs

### Metadata information

```json
{
  "metadata": {
    "packageManager": "npm",
    "name": "video.js",
    "repo": "videojs/video.js",
    "files": {
      "basePath": "dist/",
      "include": ["video-js.css", "video-js.min.css", "video-js.swf", "video.dev.js", "video.js", "video.min.js", "./lang/**/*", "./font/**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/videojs",
    "localVersions": ["3.2.0", "4.1.0", "4.2.1", "4.3.0", "4.4.3", "4.5.1", "4.6.0", "4.6.3", "4.7.2", "4.8.4", "4.10.2", "4.11.1", "4.11.2", "4.11.3", "4.11.4", "4.12.0", "4.12.1", "4.12.2", "4.12.3", "4.12.4", "4.12.5", "4.12.6", "4.12.7", "4.12.8", "4.12.9", "4.12.10", "4.12.11", "4.12.12", "4.12.13", "4.12.14", "4.12.15", "5.0.0-rc.1", "5.0.0-rc.2", "5.0.0-rc.3", "5.0.0-rc.4", "5.0.0-rc.5", "5.0.0-rc.6", "5.0.0-rc.7", "5.0.0-rc.9", "5.0.0-rc.10", "5.0.0-rc.11", "5.0.0-rc.12", "5.0.0-rc.13", "5.0.0-rc.14", "5.0.0-rc.15", "5.0.0-rc.16", "5.0.0-rc.17", "5.0.0-rc.18", "5.0.0-rc.19", "5.0.0-rc.20", "5.0.0-rc.21", "5.0.0-rc.22", "5.0.0-rc.23", "5.0.0-rc.24", "5.0.0-rc.25", "5.0.0-rc.27", "5.0.0-rc.29", "5.0.0-rc.31", "5.0.0-rc.32", "5.0.0-rc.33", "5.0.0-rc.34", "5.0.0-rc.35", "5.0.0-rc.36", "5.0.0-rc.37", "5.0.0-rc.38", "5.0.0-rc.39", "5.0.0-rc.40", "5.0.0-rc.43", "5.0.0-rc.44", "5.0.0-rc.46", "5.0.0-rc.47", "5.0.0-rc.48", "5.0.0-rc.49", "5.0.0-rc.51", "5.0.0-rc.52", "5.0.0-rc.53", "5.0.0-rc.54", "5.0.0-rc.55", "5.0.0-rc.57", "5.0.0-rc.58", "5.0.0-rc.59", "5.0.0-rc.60", "5.0.0-rc.62", "5.0.0-rc.63", "5.0.0-rc.64", "5.0.0-rc.66", "5.0.0-rc.68", "5.0.0-rc.69", "5.0.0-rc.70", "5.0.0-rc.71", "5.0.0-rc.72", "5.0.0-rc.73", "5.0.0-rc.74", "5.0.0-rc.75", "5.0.0-rc.76", "5.0.0-rc.77", "5.0.0-rc.78", "5.0.0-rc.79", "5.0.0-rc.80", "5.0.0-rc.81", "5.0.0-rc.82", "5.0.0-rc.83", "5.0.0-rc.84", "5.0.0-rc.85", "5.0.0-rc.86", "5.0.0-rc.89", "5.0.0-rc.90", "5.0.0-rc.91", "5.0.0-rc.92", "5.0.0-rc.93", "5.0.0-rc.94", "5.0.0-rc.96", "5.0.0-rc.97", "5.0.0-rc.98", "5.0.0-rc.99", "5.0.0-rc.100", "5.0.0-rc.101", "5.0.0-rc.102", "5.0.0-rc.103", "5.0.0-rc.104", "5.0.0-17", "5.0.0-18", "5.0.0-19", "5.0.0-20", "5.0.0-21", "5.0.0-22", "5.0.0-23", "5.0.0-24", "5.0.0-25", "5.0.0-26", "5.0.0-27", "5.0.0-28", "5.0.0-29", "5.0.0-30", "5.0.0-31", "5.0.0-32", "5.0.0-33", "5.0.0-34", "5.0.0", "5.0.2", "5.1.0", "5.2.0", "5.2.1", "5.2.2", "5.2.3", "5.2.4", "5.3.0", "5.4.0", "5.4.2", "5.4.3", "5.4.4", "5.4.5", "5.4.6", "5.5.0", "5.5.1", "5.5.2", "5.5.3", "5.6.0", "5.7.0", "5.7.1", "5.8.0", "5.8.1", "5.8.2", "5.8.3"],
    "remoteVersions": ["4.1.0", "4.2.0", "4.2.1", "4.2.2", "4.3.0", "4.4.0", "4.4.1", "4.4.2", "4.4.3", "4.5.0", "4.5.1", "4.5.2", "4.6.0", "4.6.1", "4.6.2", "4.6.3", "4.6.4", "4.7.0", "4.7.1", "4.7.2", "4.7.3", "4.8.0", "4.8.1", "4.8.2", "4.8.3", "4.8.4", "4.8.5", "4.9.0", "4.9.1", "4.10.0", "4.10.1", "4.10.2", "4.11.0", "4.11.1", "4.11.2", "4.11.3", "4.11.4", "4.12.0", "4.12.1", "4.12.2", "4.12.3", "4.12.4", "4.12.5", "4.12.6", "4.12.7", "4.12.8", "4.12.9", "4.12.10", "4.12.11", "4.12.12", "4.12.13", "4.12.14", "4.12.15", "5.0.0-rc.1", "5.0.0-rc.2", "5.0.0-rc.3", "5.0.0-rc.4", "5.0.0-rc.5", "5.0.0-rc.6", "5.0.0-rc.7", "5.0.0-rc.8", "5.0.0-rc.9", "5.0.0-rc.10", "5.0.0-rc.11", "5.0.0-rc.12", "5.0.0-rc.13", "5.0.0-rc.14", "5.0.0-rc.15", "5.0.0-rc.16", "5.0.0-rc.17", "5.0.0-rc.18", "5.0.0-rc.19", "5.0.0-rc.20", "5.0.0-rc.21", "5.0.0-rc.22", "5.0.0-rc.23", "5.0.0-rc.24", "5.0.0-rc.25", "5.0.0-rc.26", "5.0.0-rc.27", "5.0.0-rc.28", "5.0.0-rc.29", "5.0.0-rc.30", "5.0.0-rc.31", "5.0.0-rc.32", "5.0.0-rc.33", "5.0.0-rc.34", "5.0.0-rc.35", "5.0.0-rc.36", "5.0.0-rc.37", "5.0.0-rc.38", "5.0.0-rc.39", "5.0.0-rc.40", "5.0.0-rc.41", "5.0.0-rc.42", "5.0.0-rc.43", "5.0.0-rc.44", "5.0.0-rc.45", "5.0.0-rc.46", "5.0.0-rc.47", "5.0.0-rc.48", "5.0.0-rc.49", "5.0.0-rc.50", "5.0.0-rc.51", "5.0.0-rc.52", "5.0.0-rc.53", "5.0.0-rc.54", "5.0.0-rc.55", "5.0.0-rc.56", "5.0.0-rc.57", "5.0.0-rc.58", "5.0.0-rc.59", "5.0.0-rc.60", "5.0.0-rc.61", "5.0.0-rc.62", "5.0.0-rc.63", "5.0.0-rc.64", "5.0.0-rc.65", "5.0.0-rc.66", "5.0.0-rc.67", "5.0.0-rc.68", "5.0.0-rc.69", "5.0.0-rc.70", "5.0.0-rc.71", "5.0.0-rc.72", "5.0.0-rc.73", "5.0.0-rc.74", "5.0.0-rc.75", "5.0.0-rc.76", "5.0.0-rc.77", "5.0.0-rc.78", "5.0.0-rc.79", "5.0.0-rc.80", "5.0.0-rc.81", "5.0.0-rc.82", "5.0.0-rc.83", "5.0.0-rc.84", "5.0.0-rc.85", "5.0.0-rc.86", "5.0.0-rc.87", "5.0.0-rc.88", "5.0.0-rc.89", "5.0.0-rc.90", "5.0.0-rc.91", "5.0.0-rc.92", "5.0.0-rc.93", "5.0.0-rc.94", "5.0.0-rc.95", "5.0.0-rc.96", "5.0.0-rc.97", "5.0.0-rc.98", "5.0.0-rc.99", "5.0.0-rc.100", "5.0.0-rc.101", "5.0.0-rc.102", "5.0.0-rc.103", "5.0.0-rc.104", "5.0.0-1", "5.0.0-2", "5.0.0-3", "5.0.0-4", "5.0.0-5", "5.0.0-6", "5.0.0-7", "5.0.0-8", "5.0.0-9", "5.0.0-10", "5.0.0-11", "5.0.0-12", "5.0.0-13", "5.0.0-14", "5.0.0-15", "5.0.0-16", "5.0.0-17", "5.0.0-18", "5.0.0-19", "5.0.0-20", "5.0.0-21", "5.0.0-22", "5.0.0-23", "5.0.0-24", "5.0.0-25", "5.0.0-26", "5.0.0-27", "5.0.0-28", "5.0.0-29", "5.0.0-30", "5.0.0-31", "5.0.0-32", "5.0.0-33", "5.0.0-34", "5.0.0", "5.0.2", "5.1.0", "5.2.0", "5.2.1", "5.2.2", "5.2.3", "5.2.4", "5.3.0", "5.4.0", "5.4.2", "5.4.3", "5.4.4", "5.4.5", "5.4.6", "5.5.0", "5.5.1", "5.5.2", "5.5.3", "5.6.0", "5.7.0", "5.7.1", "5.8.0", "5.8.1", "5.8.2", "5.8.3", "5.8.4"],
    "branchVersions": ["5.0.0-rc.41", "5.0.0-rc.45", "5.0.0-rc.87"]
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/videojs/update.json",
  "versions": ["5.8.4"],
  "updateRemote": true,
  "version": "5.8.4",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/videojs/5.8.4",
  "branch": "video.js/5.8.4"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@megawac The bot didnt check this for some reason. Can you check?

**Comment by megawac** [comment]
Looking into it

**Comment by jimaek** [comment]
I think its related to Google DNS downtime. Hopefully we can catch the real bug sometime (if it still exists)

**Comment by megawac** [comment]
Yeah, the logs say that the server received the pull request hook, but
don't state the error which occurred. anyway it's odd

**Pull request merged**
