### PR TITLE
add my repo

### PR DESCRIPTION
**Pull request by laike9m**
Do I need to do anything else?

### CODE REVIEW

**Comment by megawac** [comment]
Repository is empty? https://github.com/laike9m/zhihu-cards

**Comment by laike9m** [comment]
Yes, just created this repo. I saw you wrote
> Don't add any project related files. Our bot will add them after your PR gets merged.
So I didn't add any files……Did I misunderstand?

**Comment by megawac** [comment]
Oh, we mean in this pull request. In the github repository that is linked and watched by the bot there should be content. Just manage your zhihu-cards repo as you otherwise normally would

**Comment by laike9m** [comment]
So I'm supposed to create project files first? I was intended to set up jsdelivr first then start coding.

**Comment by megawac** [comment]
jsDelivr won't do much for you until your files are ready for production. Let us know when you get your project out and documented and we'll add it to the cdn

**Comment by laike9m** [comment]
Alright. :smile:

**Comment by laike9m** [comment]
@megawac Hi, I've added my project files, what's next?

**Comment by laike9m** [comment]
@jimaek@megawac documentation is added. Mind take a look and merge this PR?

**Comment by megawac** [comment]
Thanks looks good

**Pull request merged**
