### PR TITLE
Create info.ini

### PR DESCRIPTION
**Pull request by goessner**
start committing ...

### CODE REVIEW

**Comment by goessner** [comment]
start to commit g2 ..

**Comment by goessner** [comment]
starting to commit g2 the first time ...

**Comment by goessner** [comment]
please commit ..

**Comment by goessner** [comment]
please commit

**Comment by goessner** [comment]
commit please ..

**Comment by megawac** [comment]
Thanks

**Comment by goessner** [comment]
thanks for your human help ...

**Pull request merged**
