### PR TITLE
Update project bootstrap.table to 1.8.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project bootstrap.table to 1.8.0.

@wenzhixin

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "bootstrap.table",
    "repo": "wenzhixin/bootstrap-table",
    "files": {
      "basePath": "dist/",
      "include": ["*.min.*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/bootstrap.table",
    "localVersions": ["1.7.0"],
    "remoteVersions": ["1.0.1", "1.0.2", "1.0.3", "1.0.4", "1.0.5", "1.0.6", "1.1.0", "1.1.1", "1.1.2", "1.1.3", "1.1.4", "1.1.5", "1.2.0", "1.2.1", "1.2.2", "1.2.3", "1.2.4", "1.3.0", "1.4.0", "1.5.0", "1.6.0", "1.7.0", "1.8.0"],
    "branchVersions": []
  },
  "version": "1.8.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/bootstrap.table/1.8.0",
  "branch": "bootstrap.table/1.8.0"
}
```

### CODE REVIEW

**Comment by wenzhixin** [comment]
Hi @jimaek, there are many changes in v 1.8.0, what is the problem?

**Comment by jimaek** [comment]
You added a lot of un-minified files so I am trying to configure the update.json file to exclude them and host only the min files. The next PR should be correct

**Comment by wenzhixin** [comment]
Sorry, because the PR before was not created by myself, so need I submit a new PR?

**Comment by jimaek** [comment]
No, our bot will do everything

**Pull request closed without merging**
