### PR TITLE
Update project Gridlex to 2.0.5

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project Gridlex to 2.0.5.

@devlint

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "Gridlex",
    "repo": "devlint/gridlex",
    "files": {
      "include": ["dist/gridlex.min.css"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/gridlex",
    "localVersions": [],
    "remoteVersions": ["1.0.0", "1.0.1", "2.0.0", "2.0.1", "2.0.2", "2.0.3", "2.0.4", "2.0.5"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/gridlex/update.json",
  "versions": ["1.0.0", "1.0.1", "2.0.0", "2.0.1", "2.0.2", "2.0.3", "2.0.4", "2.0.5"],
  "version": "2.0.5",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/gridlex/2.0.5",
  "branch": "Gridlex/2.0.5"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@UnbounDev Same bug. Added a new project and now bot tries to add every single version

**Comment by devlint** [comment]
@jimaek Hello, is there something I can do in my project to help fixing the version (2.0.5)? 
And thank you for the merge!

**Comment by jimaek** [comment]
No, its a bug with our bot. Your project is normally auto-updates

**Comment by devlint** [comment]
Yep I see that the new version is now accessible!
Thank you very much.

**Pull request closed without merging**
