### PR TITLE
Update project jquery.trip.js to v3.1.2

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project jquery.trip.js to v3.1.2.

@eragonj

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "repo": "eragonj/trip.js",
    "name": "jquery.trip.js",
    "files": {
      "basePath": "dist/",
      "include": ["trip.min.js", "trip.min.css", "trip.nodep.min.css"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/jquery.trip.js",
    "localVersions": ["1.3.0", "2.0.0", "2.0.1", "2.0.2", "3.0.0", "3.1.0", "3.1.1"],
    "remoteVersions": ["v1.1.0", "v1.1.1", "v1.1.2", "v1.2.0", "v1.2.2", "v1.2.3", "v1.2.4", "v1.2.5", "v1.3.0", "v2.0.0", "v2.0.1", "v2.0.2", "v3.0.0", "v3.1.0", "v3.1.1", "v3.1.2"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/libgrabber/jsdelivr/files/jquery.trip.js/update.json",
  "version": "v3.1.2",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/jquery.trip.js/3.1.2",
  "branch": "jquery.trip.js/v3.1.2"
}
```

### CODE REVIEW

**Comment by EragonJ** [comment]
@jsdelivrbot noooooo !!! no idea about how to fix this ..

**Comment by EragonJ** [comment]
@jimaek is there any bug in the bot ? it seems that it's not working well sometimes XD It's hard to know what's going on from the error message it provided hmmm

**Comment by jimaek** [comment]
Its not a bug. There was an extra file and the bot notified me to make sure everything is fine.

**Comment by EragonJ** [comment]
ok thanks, so if there are some extra files coming up, it will need your permission to merge manually, right ? Sounds reasonable :)

**Comment by jimaek** [comment]
yes, to avoid breaking stuff :)

**Pull request merged**
