### PR TITLE
new wavesufer.js

### PR DESCRIPTION
**Pull request by tomByrer**
I should really automate this someday...

### CODE REVIEW

**Comment by jimaek** [comment]
In this case ` wavesurfer-js-map.json` is useless because it tries to load files form /src which we dont host. So you should update update.json to load only wavesurfer.min.js

**Comment by tomByrer** [comment]
> update update.json to load only wavesurfer.min.js

Browsers (at least Chrome) will [error](http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found).  Let me contact dev first please.

**Comment by jimaek** [comment]
Well it will error in any case since we dont host src/

**Comment by tomByrer** [comment]
Sorry about the 3 commits; still using web client.

**Comment by megawac** [comment]
@tomByrer why don't you just fork from the initial commit xD

https://github.com/megawac/jsdelivr

**Pull request merged**
