### PR TITLE
Add fontawesome update.json

### PR DESCRIPTION
**Pull request by hubdotcom**
Excluded font-awesome.css.map

### CODE REVIEW

**Comment by jimaek** [comment]
Great job!

**Comment by hubdotcom** [comment]
Think there should be a push for the top 10 then top 100 most requested files to have the update.json included - could you provide a list?

**Comment by jimaek** [comment]
I cant generate an accurate list but here is an example:
https://www.dropbox.com/s/2svawf8wfdp44hi/Screenshot%202015-04-14%2016.19.24.png?dl=0
https://www.dropbox.com/s/s1l1rvprit5rg1o/Screenshot%202015-04-14%2016.20.20.png?dl=0

**Comment by hubdotcom** [comment]
Great! will start working through these

**Pull request merged**
