### PR TITLE
Angular Material 0.8.3

### PR DESCRIPTION
**Pull request by jcockhren**
Adding Angular Material JS and CSS files.

### CODE REVIEW

**Comment by jimaek** [comment]
Before I review it please squash all your commits into 1.

**Comment by jcockhren** [comment]
@jimaek squashed!! :smiley:

**Comment by jimaek** [comment]
1. Can you rename the directory to `angular.material` please?
2. What is your source for these files?
3. I dont think we need the css/ js/ folders. Just put all of them inside the version. Make sure you update info.ini as well
4. Please squash the commits after you've done everything :)

thank you

**Comment by jcockhren** [comment]
> What is your source for these files?

@jimaek I got these files from [Google Hosted Libraries CDN](https://developers.google.com/speed/libraries/devguide#angularmaterial). Their repo doesn't contain the releases.

**Comment by jimaek** [comment]
Thank you

**Pull request merged**
