### PR TITLE
Update project codemirror-spell-checker to 1.0.1

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project codemirror-spell-checker to 1.0.1.

@NextStepWebs

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "codemirror-spell-checker",
    "repo": "NextStepWebs/codemirror-spell-checker",
    "files": {
      "include": ["spell-checker.min.js", "spell-checker.min.css", "en_US.aff", "en_US.dic"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/codemirror.spell-checker",
    "localVersions": ["1.0.0"],
    "remoteVersions": ["1.0.0", "1.0.1"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/codemirror.spell-checker/update.json",
  "version": "1.0.1",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/codemirror.spell-checker/1.0.1",
  "branch": "codemirror-spell-checker/1.0.1"
}
```

### CODE REVIEW

**Comment by WesCossick** [comment]
Same as before, @jimaek. Is there a way around this? Hopefully this will be the last release for a little while though.

**Comment by jimaek** [comment]
@megawac Can you update the bot to include these 2 file extensions?

**Comment by megawac** [comment]
Can a browser use those file types in a meaningful way?

**Comment by WesCossick** [comment]
They're data files used by the plugin. It's a spell checker and those are the dictionary files. They're read in through a function, so yes, the browser uses them.

**Pull request merged**
