### PR TITLE
Update project instantsearch.js to 0.11.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project instantsearch.js to 0.11.0.

@algolia

### Metadata information

```json
{
  "metadata": {
    "packageManager": "npm",
    "name": "instantsearch.js",
    "repo": "algolia/instantsearch.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/instantsearch.js",
    "localVersions": ["0.2.2", "0.3.0", "0.4.0", "0.4.1", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.4", "0.6.5", "0.7.0", "0.8.0", "0.8.1", "0.8.2", "0.9.0", "0.10.0"],
    "remoteVersions": ["0.1.0", "0.2.2", "0.3.0", "0.4.0", "0.4.1", "0.5.0", "0.5.1", "0.6.0", "0.6.1", "0.6.2", "0.6.3", "0.6.4", "0.6.5", "0.7.0", "0.8.0", "0.8.1", "0.8.2", "0.9.0", "0.10.0", "0.11.0"],
    "branchVersions": ["0.8.0"]
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/instantsearch.js/update.json",
  "version": "0.11.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/instantsearch.js/0.11.0",
  "branch": "instantsearch.js/0.11.0"
}
```

### CODE REVIEW

**Comment by jimaek** [comment]
@vvo I dont think it makes sense to host debug.css. Do you need it? If you want add an exclude parameter to update.json

**Comment by vvo** [comment]
Thanks for fast feedback @jimaek, Ill remove this file and then make sure we do not have it anymore. How can I remove it from the current PR? Just edit in github? :D

**Comment by jimaek** [comment]
Edit the update.json and I will close this PR. The bot will send a new one without this file

**Comment by vvo** [comment]
> Edit the update.json and I will close this PR. The bot will send a new one without this file

Ok and then I will again update the update.json to remove the ignore because the file will no more be here next time. Thanks

**Comment by vvo** [comment]
ok https://github.com/jsdelivr/jsdelivr/pull/7847

**Pull request closed without merging**
