### PR TITLE
Update project zhihu-card to 0.0.2

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project zhihu-card to 0.0.2.

@laike9m

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "zhihu-card",
    "repo": "laike9m/zhihu-card",
    "files": {
      "basePath": "jsdelivr/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/libgrabber/jsdelivr/files/zhihu-cards",
    "localVersions": [],
    "remoteVersions": ["0.0.1", "0.0.2"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/zhihu-cards/update.json",
  "versions": ["0.0.2"],
  "updateRemote": true,
  "version": "0.0.2",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/zhihu-cards/0.0.2",
  "branch": "zhihu-card/0.0.2"
}
```

### CODE REVIEW

**Comment by laike9m** [comment]
@megawac I made a mistake that I changed my project name from `zhihu-cards` to `zhihu-card` but forgot to change folder's name in #12003, and it's causing validation failure. :cry:What am I supposed to do now……

**Comment by laike9m** [comment]
Is it possible to change folder name in jsdelivr now?

**Comment by megawac** [comment]
@laike9m we're not hosting zhihu card until this pr is merged, so feel free to just rename the folder and send a pull request.

**Comment by laike9m** [comment]
Thx@megawac, new PR #12352

**Pull request closed without merging**
