### PR TITLE
Revealjs v3.0.0

### PR DESCRIPTION
**Pull request by isaackwan**
If I am not mistaken, the author is no longer producing a compressed version.

The PR contains the css, js, lib and plugin folders unextracted from the GitHub release, with:
- minified js by UglifyJS2 by refresh-sf.com
- minified css by clean-css by refresh-sf.com
- deleted some readme / license type files

Please bear with me if I had made a mistake coz I'm in need of coffeeeeeee. 

-Isaac

### CODE REVIEW

**Comment by jimaek** [comment]
What about the missing fonts and plugins?

**Comment by isaackwan** [comment]
I didn't do anything to them. Here is my guess:

### Fonts:
They were restructured, as you can see, they are now grouped into folders.

### Plugins:
No clue, but then I didn't modify anything.

**Comment by jimaek** [comment]
Can you please squash your commits into 1?

**Comment by isaackwan** [comment]
The commits are now merged. Please let me know if I had done anything wrong since I am new to git.;)

**Comment by jimaek** [comment]
Thank you

**Comment by edrex** [comment]
Is there a policy for releases requiring post processing (minification etc)? It seems safer if the actual post processing happened on the project's infrastructure. Also more repeatable. 

3.1.0 is out, do the same manual steps?

**Comment by megawac** [comment]
We definitely prefer if there is official minified code, otherwise we ask contributors to minify using it the *"safe"* minifier settings (i.e. not closure advanced compiler :). Isaacs steps seem fine and reasonable

**Comment by megawac** [comment]
Actually @edrex it looks like their grunt file contains scripts to minify the code - they just don't publish it to github. Two options, a) file an issue asking them to push the built code (and we can setup auto updating) b) build it yourself and submit a PR here

https://github.com/hakimel/reveal.js/blob/3.1.0/Gruntfile.js

Looks like it would be these commands to build the minified files

```
grunt js
grunt css
```

**Comment by edrex** [comment]
I guess I was thinking wondering whether jsdelivr's bot might grow the ability to run postprocessing tasks (ie, `grunt`) on travis or similar as part of auto update.

**Pull request merged**
