### PR TITLE
Moved lib jquery-form

### PR DESCRIPTION
**Pull request by kevindb**
http://www.jsdelivr.com/projects/jquery.form
The jquery-form/form project has changed ownership from malsup/form.

Also added auto-update config

### CODE REVIEW

**Comment by kevindb** [comment]
Thank you for the merge! I hope I set up the auto-update feature properly.

How long should it take from the PR merge to see the updated library on the CDN? This line from the README indicates that it's pretty quick:
> All changes made to this repo are synced to the CDN. It can take a few minutes for the changes to appear on the website.

The CDN is still showing an old version: http://www.jsdelivr.com/projects/jquery.form

**Comment by megawac** [comment]
Hey @MartinKolarik any ideas?

**Comment by MartinKolarik** [comment]
It should take about two minutes but I also noticed it took much longer several times before. Not sure why.
@jimaek do we store any logs from [jsdelivr/www.jsdelivr.com](https://github.com/jsdelivr/www.jsdelivr.com) right now?

**Comment by jimaek** [comment]
The site is cached by a CDN, thats why changing stuff takes a while to purge.

**Comment by MartinKolarik** [comment]
Project data are loaded via JS directly from Algolia and not cached.

**Comment by megawac** [comment]
Regardless, shouldnt libgrabber have synced v4.0.1 by now?

**Comment by MartinKolarik** [comment]
CDN gets updated correctly, it's just the website.

**Comment by kevindb** [comment]
The website has updated with 4.0.1. Thank you all!

**Pull request merged**
