### PR TITLE
jCider- An extensive and responsive jQuery plugin for sliders/carousels.

### PR DESCRIPTION
**Pull request by Pratinav**
Using the web-interface method recommended. Thanks.

### CODE REVIEW

**Comment by Pratinav** [comment]
Updated again...

**Comment by megawac** [comment]
Should this be hosted as `jquery.jcider` (see contributing.md)

**Comment by Pratinav** [comment]
Thanks!

**Comment by Pratinav** [comment]
Should I close this pull request?

**Comment by Pratinav** [comment]
and yeah... i forgot to answer your question. :P

**Comment by Pratinav** [comment]
Can I get the full url for the file once it is hosted.

**Comment by jimaek** [comment]
>Also you'll need to add some documentation to your project before we can host it.

We cant merge before that

**Comment by Pratinav** [comment]
Yup, just finished up the README file.

**Comment by Pratinav** [comment]
Hey, have you hosted the files? if so, can I get the full url for them?

**Comment by Pratinav** [comment]
Anyone there....

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by jimaek** [comment]
sorry it took so long

**Pull request closed without merging**
