### PR TITLE
Add autoupdate for cookieconsent2

### PR DESCRIPTION
**Pull request by ping**
Also included the latest 1.0.9 release.

### CODE REVIEW

**Comment by jimaek** [comment]
We cant remove the file between minor versions, it could break sites.

**Comment by ping** [comment]
@jimaek So what are the options then? No auto updates?

Also, is there a place where these "rules" like no removal of files between minor versions are documented for contributors?

**Comment by jimaek** [comment]
Yes, no auto-updates. No way around that, too much risk.
There is no documentation for this but we need to add it.

**Comment by ping** [comment]
Reverted changes for auto-update. Manual update for 1.0.9.

**Comment by ping** [comment]
@jimaek The 1.0.9 release is returning not found for me.

```
$ curl -I "http://cdn.jsdelivr.net/cookieconsent2/1.0.9/cookieconsent.min.js"
HTTP/1.1 404 Not Found
Date: Fri, 23 Oct 2015 12:16:21 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Cache-Control: no-cache
Access-Control-Allow-Origin: *
CF-Cache-Status: MISS
Server: cloudflare-nginx
CF-RAY: 239d5f6547a721e6-EWR

$ curl -I "http://jsdelivr3.dak.netdna-cdn.com/cookieconsent2/1.0.9/cookieconsent.min.js"
HTTP/1.1 404 Not Found
Date: Fri, 23 Oct 2015 12:19:13 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Server: NetDNA-cache/2.2
```

**Comment by jimaek** [comment]
The webhook failed because of timeout. Either Github or our deploy service was having issues. Sorry about that

**Comment by ping** [comment]
Works fine now. Thanks for the fix.

**Pull request merged**
