### PR TITLE
added

### PR DESCRIPTION
**Pull request by DBJDBJ**

### CODE REVIEW

**Comment by DBJDBJ** [comment]
Ooops sory closed too soon....

**Comment by DBJDBJ** [comment]
micro library of core JS things I use every day ....

**Comment by jimaek** [comment]
1. No version tags
2. I dont completely understand what it does. It looks more like a private collection of functions for personal use rather than a library meant to be used by everyone

**Comment by DBJDBJ** [comment]
Hi jimaek, why not just kindly pointing me to the “Custom CDN Hosting” section of the README?
That is exactly what I want. Can we please arrange for that to happen for dbj.microlib.js

Otherwise:


1.       What are “version tags” in this context?

2.       yes my  library it is precisely that: “private collections of functions for personal use”

a.       Can anyone of these anonymous parties please point me to some introduction to the purpose of jsdeliver and precise description of the process involved?

b.      Github readme says in the first sentence: “jsDelivr is an open source CDN that allows developers to host their own projects…”.

                                                               i.      So that is precisely my aim.

3.       This whole way of anonymous communication is rather “Kafkian” “process”.

                                                               i.      Who is “Dimitriy Akulov”? Ah ok this is jimaek. It is OK then.

                                                             ii.      Why are the identities of all parties in this email “hidden”? Link to jimaeks page might help.

b.      Etc …

Regards …



Dusan Jovanovic, cto
+44 20 33 55 89 85
dbj@dbj.org<mailto:dbj@dbj.org>
Innovation Disruption Architecture Profit™
[dbj2_blue_100x100]

**Comment by jimaek** [comment]
I replied to you in the email you sent me.

**Pull request closed without merging**
