### PR TITLE
Add new angular/jquery files

### PR DESCRIPTION
**Pull request by redox**
Since 2.9.0, our library includes more files.

### CODE REVIEW

**Comment by jimaek** [comment]
Do you need the unminified files too? Or we can just host the min.js?

**Comment by redox** [comment]
I'm used to use the non-minified version of the libraries I'm using in my development environments. Let me know if you want me to remove them, I understand it could cost too much bandwidth.

**Comment by jimaek** [comment]
I can't merge your PR `We can’t automatically merge this pull request. ` so I update the file myself https://github.com/jsdelivr/jsdelivr/commit/504a5443bff9b3659f905f5cb9beadd69b3ee314

The bot will include all the files in `dist/` including un-minified. bandwidth is not an issue for us so feel free to use jsDelivr as much as possible :)

**Comment by redox** [comment]
Will do, thanks! :+1:

**Comment by jimaek** [comment]
The bot will include the files only from the next version but if you want the new files in 2.9.0 let me know and I will upload them too.

**Comment by redox** [comment]
@jimaek Just saw your message, yes including them from this version (2.9.0) would be cool. Thank you for your help!

**Comment by jimaek** [comment]
@redox Done http://www.jsdelivr.com/#!algoliasearch

**Comment by redox** [comment]
:+1: Thank your for the swift reply

**Pull request closed without merging**
