### PR TITLE
Updated bootstrap-filestyle to 1.1.2 & Added Switchery.js

### PR DESCRIPTION
**Pull request by D144**

### CODE REVIEW

**Comment by jimaek** [comment]
you are missing the info.ini file

**Comment by D144** [comment]
The info.ini file didn’t change. There’s nothing to commit

**Comment by jimaek** [comment]
You are correct, I thought it was a new submission, sorry about that. 
Unfortunately you will  have to remove update.json because the repo does not include the min file that is currently the mainfile https://github.com/markusslima/bootstrap-filestyle/tree/v1.1.2/src

**Comment by D144** [comment]
I removed update.json like you asked

**Comment by jimaek** [comment]
Please dont submit multiple projects in one PR, it makes it harder to review.
In switchery can you remove `switchery/0.7.0/switchery.js`, the min file is enough

**Comment by D144** [comment]
Sorry about that. I removed the files as requested.

**Comment by jimaek** [comment]
Ok, finally please squash your commits into 1

**Pull request closed without merging**
