### PR TITLE
add fancy-maps

### PR DESCRIPTION
**Pull request by osxi**

### CODE REVIEW

**Comment by osxi** [comment]
Failing check says that that fancy-maps.min.js might not be properly minified. Ran it through `yuicompressor` and it looks/feels good to me.

**Comment by jimaek** [comment]
if this is a plugin for react then rename the folder to `react.fancy-maps` please

**Comment by osxi** [comment]
The project is not a React plugin but a library that wraps Leaflet.js *using* React with JSX.

Is it OK to place this PR on hold until I figure out a better way to build/minify the JS?

**Comment by jimaek** [comment]
Sure. Leave a comment when you want to continue

**Comment by osxi** [comment]
Thanks! It'll be sooner than later.

**Comment by osxi** [comment]
@jimaek OK looks like the check passed this time! I'm ready.

**Pull request merged**
