### PR TITLE
Updates jquery.hosted-payments.js

### PR DESCRIPTION
**Pull request by etsms**

### CODE REVIEW

**Comment by jimaek** [comment]
Why are you updating existing files?
Btw you can enable auto-updates https://github.com/jsdelivr/jsdelivr#auto-updating

**Comment by etsms** [comment]
@jimaek - I'm not quite sure what you mean by that question. I have not touched existing files. There was a point in-time last week where one of our team members jumped the gun and decided to add the "update.json" file. Essentially telling jsDelivr to check the repo for updates automatically. While that is where we want to be... We're not quite ready for that scenario. We'd like to maintain control of what's being added and updated.

That said...

We've fixed a few bugs and have released several patches to address the issues. I apologize for the confusion with the addition and then removal of "update.json" file. It was a premature decision. Please ignore.

Let me know if there is anything I can do to explain the changes further.

**Comment by jimaek** [comment]
Your PR contains updates to existing files without any reason and creates conflicts to the repo. You are doing 13 commits for some reason.

**Comment by etsms** [comment]
Let's start over shall we?

**Pull request closed without merging**
