### PR TITLE
CodeMirror spell checker

### PR DESCRIPTION
**Pull request by WesCossick**

### CODE REVIEW

**Comment by WesCossick** [comment]
The homepage will be created once jsDelivr hosts the CDN

**Comment by jimaek** [comment]
You dont have any tagged versions, the bot will fail.
We also require a good documentation before approving a project to ensure the current version is production ready.

**Comment by WesCossick** [comment]
Okay, working on it...

**Comment by WesCossick** [comment]
Documentation is up, plus release 1.0.0.

**Comment by jimaek** [comment]
Since this is a plugin please rename the directory to `codemirror.spell-checker`

**Comment by WesCossick** [comment]
Done.

**Comment by jimaek** [comment]
I have a question, what these files are doing exactly? "en_US.aff", "en_US.dic"
Are they needed in production?

**Comment by WesCossick** [comment]
They are needed. They are the dictionaries for the spell checker to use, since it does the spell checking client side.

**Comment by jimaek** [comment]
@jsdelivrbot squash and merge

**Comment by WesCossick** [comment]
Thanks!

**Pull request closed without merging**
