### PR TITLE
Update project mousetrap to 1.6.3

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project mousetrap to 1.6.3.

@ccampbell

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "mousetrap",
    "repo": "ccampbell/mousetrap",
    "files": {
      "include": ["mousetrap.min.js", "mousetrap.js", "./plugins/**/*.min.js"],
      "exclude": ["**/tests/"]
    },
    "path": "/home/libgrabber/jsdelivr/files/mousetrap",
    "localVersions": ["1.3", "1.4.2", "1.4.5", "1.4.6", "1.5.3"],
    "remoteVersions": ["1.0", "1.1", "1.1.1", "1.1.2", "1.1.3", "1.1.4", "1.2", "1.2.1", "1.2.2", "1.3", "1.3.2", "1.4.0", "1.4.1", "1.4.2", "1.4.3", "1.4.4", "1.4.5", "1.4.6", "1.5.0", "1.5.1", "1.5.2", "1.5.3", "1.6.3"],
    "branchVersions": []
  },
  "metadataPath": "/home/libgrabber/jsdelivr/files/mousetrap/update.json",
  "versions": ["1.6.3"],
  "updateRemote": true,
  "version": "1.6.3",
  "updated": true,
  "updatePath": "/home/libgrabber/jsdelivr/files/mousetrap/1.6.3",
  "branch": "mousetrap/1.6.3"
}
```

### CODE REVIEW

**Comment by ccampbell** [comment]
Hey @jimaek is there any way to revert this/change it to `1.6.0`? I made a mistake and published `1.6.3` without thinking (previous version was `1.5.3` and it should have been `1.6.0`. I deleted the remote tag and retagged at `1.6.0` but your bot was too fast for me.

**Comment by jimaek** [comment]
Reverted. But it will take a while for cache to clean

**Comment by ccampbell** [comment]
Thank you! Will the version for 1.6.0 get kicked off automatically?

**Comment by jimaek** [comment]
It will when the cache gets purged. If you want it live faster I recommend sending a manual PR

**Comment by ccampbell** [comment]
I'm not in a rush. :smile: thanks

**Pull request merged**
