### PR TITLE
Add sync fusion 14.2.32 css and script files

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**

### CODE REVIEW

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
We have get error like below screenshot.I don't delete that files but its show like delete those files. 
jsdeliver_error

We have already  faced this type issue and @megawac  suggest some steps like below ,it's work fine.

git checkout <branch of this pr>
git remote add jsdelivr git@github.com:jsdelivr/jsdelivr
git fetch jsdelivr
git reset --soft jsdelivr/master
git reset -q
git add files/syncfusion-javascript/14.2.32/
git commit -am "Add sync fusion 14.2.232"
git push -f origin <branch> 

But now same error occurred when i have used above steps for commit in JsDelivr- master repository 

Please give suggestion asap.

**Comment by megawac** [comment]
`git commit -am "Add sync fusion 14.2.232"` change to `git commit -m "Add sync fusion 14.2.232"`

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac  -Thanks for response 
I have tried like git commit -m "Add sync fusion 14.2.32".but its showing same error.Please refer screenshot below.
jsdeliver_error

**Comment by Syncfusion-JavaScript** [comment]
Hi @megawac ,
Can you please update solution asap

**Comment by megawac** [comment]
Sorry very hard for me to work with the information provided. Perhaps a stackoverflow question would be more fitting?

**Pull request closed without merging**
