### PR TITLE
Update project dll.js to 0.9.0

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project dll.js to 0.9.0.

@thednp

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "dll.js",
    "repo": "thednp/dll.js",
    "files": {
      "basePath": "dist/",
      "include": ["**/*"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/dll.js",
    "localVersions": [],
    "remoteVersions": ["0.9.0"],
    "branchVersions": []
  },
  "version": "0.9.0",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/dll.js/0.9.0",
  "branch": "dll.js/0.9.0"
}
```

### CODE REVIEW

**Comment by thednp** [comment]
This can also be merged.

**Comment by thednp** [comment]
dll.js has no info.ini, REALLY?

**Comment by jimaek** [comment]
The API takes some time to update you can ignore it

**Comment by thednp** [comment]
@jimaek Thanks for the info.

**Pull request merged**
