### PR TITLE
CSS for library

### PR DESCRIPTION
**Pull request by ecoslado**

### CODE REVIEW

**Comment by jimaek** [comment]
We already host it http://www.jsdelivr.com/projects/doofinder

**Comment by ecoslado** [comment]
Yep, but I'd need to add a css file from this project. Would it be possible?

**Comment by jimaek** [comment]
There is no css file here https://github.com/doofinder/js-doofinder/tree/v0.6.1/dist

**Comment by ecoslado** [comment]
Yes, but it is in here:

https://github.com/doofinder/js-doofinder/tree/0.17.10/dist

2016-01-20 17:04 GMT+01:00 Dmitriy Akulov <notifications@github.com>:

> There is no css file here
> https://github.com/doofinder/js-doofinder/tree/v0.6.1/dist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsdelivr/jsdelivr/pull/8983#issuecomment-173250670>.
>



-- 
*Kike Coslado*
Software Engineer

*DOOFINDER*
Lopez de Hoyos 135, 4A
28002 - Madrid
http://www.doofinder.com

**Comment by jimaek** [comment]
Ok. I added the css file https://github.com/jsdelivr/jsdelivr/blob/master/files/doofinder/update.json
The bot will add it in the next version

**Comment by ecoslado** [comment]
Ok thanks so much.

2016-01-20 17:13 GMT+01:00 Dmitriy Akulov <notifications@github.com>:

> Ok. I added the css file
> https://github.com/jsdelivr/jsdelivr/blob/master/files/doofinder/update.json
> The bot will add it in the next version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsdelivr/jsdelivr/pull/8983#issuecomment-173253381>.
>



-- 
*Kike Coslado*
Software Engineer

*DOOFINDER*
Lopez de Hoyos 135, 4A
28002 - Madrid
http://www.doofinder.com

**Pull request closed without merging**
