### PR TITLE
updated the source - v1.0 tag.

### PR DESCRIPTION
**Pull request by soundar24**

### CODE REVIEW

**Comment by soundar24** [comment]
I want to add some additional changes in my version 1.0 files, so that i am again updated in the same version source. So can you please include these changes.

**Comment by soundar24** [comment]
Can you please let me know what should i do now ?

**Comment by jimaek** [comment]
Why are you doing that? Just release a new version with the new changes

**Comment by soundar24** [comment]
Actually this is a small minor changes only.. for each changes creating a new version is not good.. and also i have some milestones.. when i complete each at that time only i planned to publish a new version.. And also recently only i published my plugin, still it does't reach with peoples, so that we can add this in the same version also..

**Comment by soundar24** [comment]
@jimaek : here you have mentioned as merged, but still the changes are not updated in the cdn link. Can you please let me know the details ?

**Comment by jimaek** [comment]
The old version was cached on the CDN.
I purged the cache for your files

**Comment by soundar24** [comment]
@jimaek : Thank you so much, now it was updated in the CDN also.. :+1:

**Pull request merged**
