### PR TITLE
Sync patch

### PR DESCRIPTION
**Pull request by Syncfusion-JavaScript**

### CODE REVIEW

**Comment by Syncfusion-JavaScript** [comment]
Hi Team,
We have faced the problem while publishing our updated javascript assets in jsDelivr repo. When we give Pull request its showing validation issue Please refer pull request link below.

https://github.com/jsdelivr/jsdelivr/pull/13048 

We have checked the file structure for files which one get validation error like 
“We try to keep the file structure as consistent as possible between versions; there were some changes in file structure from previous versions.. “

ex.  jsrender.min.js 
Location in v14.2.26 : “jsdelivr\files\syncfusion-javascript\14.2.26\Scripts”
Location in v14.2.28 : “jsdelivr\files\syncfusion-javascript\14.2.28\Scripts”
We don’t have any modifications in file structures. Can you check and suggest us to resolve this issue ?

**Comment by megawac** [comment]
@Syncfusion-JavaScript this happens with pull requests with > 500 files. Feel free to ignore it. The issue that we need you to address is the branch conflicts with master. We can't merge with the current git conflicts

**Comment by Syncfusion-JavaScript** [comment]
@megawac - Thanks for the update. We have added only new version directory with latest files in our branch and update that pull request to master. Is there any steps needed follow to publish the new version directory  ? Can you point out the exact issue if possible ?

**Comment by megawac** [comment]
The issue is that the pull request has merge conflicts



Please see https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/ or another resource in order to fix the issue

**Comment by Syncfusion-JavaScript** [comment]
@megawac   - Thanks for the update.
 
I have check jsDelivr  with master branch using  “$ git status” its showing conflict others file in  jsDelivr - master branch too. 
jsdelivr conflicterror

File structure conflict occurred jsDelivr master branch too, so we cannot able to merge our pull request too. 
Can you update us on this if we misunderstood anything ?

**Comment by megawac** [comment]
Can you run the following

```js
git checkout <branch of this pr>
git remote add jsdelivr git@github.com:jsdelivr/jsdelivr
git fetch jsdelivr
git reset --soft jsdelivr/master
git add files/syncfusion-javascript/14.2.28/
git commit -am "Add sync fusion 14.2.28"
git push -f origin <branch>
```

**Comment by Syncfusion-JavaScript** [comment]
@megawac - Thanks for the update.
I have check above your given steps, 
1. I get error like below screenshot when using `git fetch jsdelivr` 

gitfetch_error

2. I have use fetch command in local repository  like `git fetch` ,its working fine and I have committed files using below  steps in local repository.
`git checkout `
`git remote add jsdelivr git@github.com:jsdelivr/jsdelivr `
`git fetch `
`git reset --soft `
`git add files/syncfusion-javascript/14.2.28`
`git commit -am "Add sync fusion 14.2.28"`
`git push -f origin master`
Finally i have create pull request in jsDelivr repository. but its get same issue like below screenshot.

pullrequesterror

Can you update us on this if we misunderstood anything ?

**Comment by megawac** [comment]
Looks like you don't have your ssh keys setup properly. Just change the jsdelivr git url to the https version of the link.

**Pull request closed without merging**
