### PR TITLE
Lytebox js library for pic galleries

### PR DESCRIPTION
**Pull request by Fede72**
Lytebox js library for pic galleries

### CODE REVIEW

**Comment by Fede72** [comment]
The files are correct

**Comment by jimaek** [comment]
1. You have 11 commits in this PR. There should be only 1
2. This is a very old project, I dont see any point to host it. If anyone was using it he should stop.

**Comment by tomByrer** [comment]
There is a newer version: `[Lytebox v5.5 (01-26-2012)](http://lytebox.com/index.php?launch=true&page=history)`
[d/l](http://lytebox.com/howTo.php)

**Comment by Arg0n4th** [comment]
I create a new commit with fulla packages (also with images) with version 5.5.
Waiting for approval

**Pull request closed without merging**
