### PR TITLE
Updated code-highlighter to v1.1.0

### PR DESCRIPTION
**Pull request by avielfedida**

### CODE REVIEW

**Comment by jimaek** [comment]
Consider using auto-updates https://github.com/jsdelivr/jsdelivr#auto-updating

**Comment by avielfedida** [comment]
@jimaek Hey, so I should pull another request with the auto-update(update.json) file and that's it?, I mean whenever I update my project, you will auto-sync my latest version?

**Comment by jimaek** [comment]
Yes thats correct

**Comment by avielfedida** [comment]
@jimaek Thank you.

**Pull request merged**
