### PR TITLE
Update project chassis to 1.0.0b

### PR DESCRIPTION
**Pull request by jsdelivrbot**
libgrabber updated project chassis to 1.0.0b.

@ngnjs

### Metadata information

```json
{
  "metadata": {
    "packageManager": "github",
    "name": "chassis",
    "repo": "ngnjs/chassis-lib",
    "files": {
      "basePath": "dist/",
      "include": ["*.min.js"],
      "exclude": []
    },
    "path": "/home/jsdelivr/files/chassis",
    "localVersions": [],
    "remoteVersions": ["1.0.0a", "1.0.0b"],
    "branchVersions": []
  },
  "updateRemote": true,
  "metadataPath": "/home/jsdelivr/files/chassis/update.json",
  "version": "1.0.0b",
  "updated": true,
  "updatePath": "/home/jsdelivr/files/chassis/1.0.0-b",
  "branch": "chassis/1.0.0b"
}
```

### CODE REVIEW

**Comment by coreybutler** [comment]
Not sure why the bot isn't picking up on the info.ini file. It exists at [https://github.com/jsdelivr/jsdelivr/blob/master/files/chassis/info.ini](https://github.com/jsdelivr/jsdelivr/blob/master/files/chassis/info.ini)

**Comment by megawac** [comment]
I was talking about the minification issues. The info.ini is just the api taking a bit to long to sync

**Comment by megawac** [comment]
The api syncs every 30 minutes and auto updates are also done every 30 minutes, so the info.ini is often missed the first time a project is synced :)

**Comment by coreybutler** [comment]
Gotcha - thanks for the insight. I've updated the `update.json` to only pull the main file (which I've confirmed is minified... PR was already merged). Apparently there was a problem in my build process that failed to minify the individual component files, so I've stripped them out until I have time to resolve that.

**Pull request closed without merging**
